### ISSUE TITLE
My house just got deleted and I need it back!

### ISSUE THREAD

**Issue by Sammyueru** [Uuvana-Studios/longvinter-windows-client#533] opened 2022-03-20 20:17 UTC
**Describe the bug**
I went to back to where my house was and it wasn't there

**To Reproduce**
I really don't know my house was just deleted

**Expected behavior**
For my house to not just get deleted

**Screenshots**
I wish I had some

**Desktop (please complete the following information):**
 - OS: Windows
 - Game Version: 1.0.1
 - Steam Version: IDK

**Comment by faketucker** [comment] 2022-03-27 02:57
Duplicate of #508

**Closed by faketucker** 2022-03-27 02:57 UTC
Labels: bug, Not Tested
