### ISSUE TITLE
I cant upgrade my home. 

### ISSUE THREAD

**Issue by silahendaz** [Uuvana-Studios/longvinter-windows-client#1117] opened 2022-07-30 12:25 UTC
ERROR in picture. 

![longvinter error](https://user-images.githubusercontent.com/71545435/181914096-9ee1d3fd-3e4c-4a54-845d-d375f9729db5.png)

**Comment by faketucker** [comment] 2022-08-02 06:41
Duplicate of #1131

**Closed by faketucker** 2022-08-02 06:41 UTC
Labels: Bug, Not Tested
