### ISSUE TITLE
Other players appear inside my house

### ISSUE THREAD

**Issue by Yukita7** [Uuvana-Studios/longvinter-windows-client#586] opened 2022-03-25 18:39 UTC
**Describe the bug**
Other players appear inside my house and are taking things out of my containers.

**To Reproduce**
1. i enter the game
2. i see that my containers are almost empty
3. i come out of the house and see a backpack with my things in it.
4. i dont know how they have escaped with things because i have a lot of turrets outside.

**Expected behavior**
i was hoping that the containers were safe inside the houses, because severan times y had to go back to recover and look for materials again.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: windows 10
 - Game Version 1.0.2
 - Steam Version v020

**Additional context**

**Comment by faketucker** [comment] 2022-03-26 06:41
Duplicate of #562

**Closed by faketucker** 2022-03-26 06:41 UTC
Labels: bug, Not Tested
