### ISSUE TITLE
MY invotory has reset ....

### ISSUE THREAD

**Issue by Sneeazy** [Uuvana-Studios/longvinter-windows-client#237] opened 2022-03-06 20:49 UTC
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Game Version [e.g. 1.0]
 - Steam Version [e.g. 1.0]

**Additional context**

**Comment by sirNugg3ts** [comment] 2022-03-06 20:59
Duplicate of #120

**Closed by sirNugg3ts** 2022-03-06 20:59 UTC
Labels: bug, Not Tested
