### ISSUE TITLE
Speed Buffs and Swimming Speed Bug

### ISSUE THREAD

**Issue by ilrathCXV** [Uuvana-Studios/longvinter-windows-client#197] opened 2022-03-05 13:01 UTC
**Describe the bug**
When a speed buff disappears while swimming, you move at normal (running) speed while in water. When getting out of water, it can sometimes cause jittery movement or give you swimming speed on land. Weird jitter/slow movement can be fixed by aiming a weapon.

**Reproducable:**
1. Drink Energy Drink or related items that give speed boost
2. Be in water while buff expires
3. Running speed in water
4. (Possible) Normal but jittery running speed on land -OR- slow, swimming speed on land
5. Step 4 can be fixed with aiming a weapon (AR, Semi, SG, SMG, Chainsaw, Hatchet)

**Comment by sirNugg3ts** [comment] 2022-03-07 17:53
Duplicate of #11

**Closed by sirNugg3ts** 2022-03-07 17:53 UTC
Labels: bug, Not Tested
