### ISSUE TITLE
Game Breaking bug that disconnects the user and deletes their items

### ISSUE THREAD

**Issue by ToobTime** [Uuvana-Studios/longvinter-windows-client#127] opened 2022-03-01 22:40 UTC
when ever i join the uuvana 5 server i spawn fresh with all my progress gone. when ever i go around and pick up more items and then i leave and rejoin, the items are gone. the server also periodically kicks me randomly and then deletes my items. the whole player data gets wiped, like money, items, the resource book achievements etc.

**Comment by sirNugg3ts** [comment] 2022-03-01 23:23
Duplicate of #120

**Closed by sirNugg3ts** 2022-03-01 23:23 UTC
Labels: bug, Not Tested
