### ISSUE TITLE
save file restarts everytime i leave

### ISSUE THREAD

**Issue by dud647** [Uuvana-Studios/longvinter-windows-client#186] opened 2022-03-04 20:38 UTC
Everytime I leave the game i lose all my stuff including my money. It always restarts me back at the first island with $100. I'm playing on uuvana 1 and I had this issue last night after leaving. I had no problems on the server before playing, but it randomly started happening. I'm mad because i actually had a decent save going and a lot of nice people on this server, now i cant play on it because im basically blocked since my save file keeps restarting. It still kept my house so if i'm able to fix this problem and I can continue on.

I expected my save to work properly.

**Screenshots**
![image](https://user-images.githubusercontent.com/100967590/156837649-a5a6cbdf-a580-45e5-8722-075704207a38.png)
![image](https://user-images.githubusercontent.com/100967590/156837756-bc9a6299-b524-4659-b33e-fdc3555e5c82.png)
the first image is showing me grabbing wheat. the next image shows what happens after i disconnect, my inventory is gone and i am reset back to the first position.

**Desktop (please complete the following information):**
 - OS: Windows
 - Game Version Latest
 - Steam Version Latest

**Additional context**
I hope i can get this problem fixed so i can continue to play on this server. this game is great this bug is just blocking me from playing it. if there is a way i can get my stuff back that would be great too, (i had 6k cash on me, a chainsaw, a shotgun and like 3 or 4 cloudberries) but i'm also fine with grinding to get my stuff back i just want to not have it reset everytime.

**Comment by dud647** [comment] 2022-03-04 20:42
Forgot to mention i also tried uninstalling and reinstalling my game, verifying files, and even tried switching to the new experimental mode but none of these have changed my problem at all.

**Comment by aiiabon** [comment] 2022-03-05 04:21
this happened to me just now

**Comment by Kainzuki** [comment] 2022-03-05 11:18
this happened to me today

**Comment by sirNugg3ts** [comment] 2022-03-05 14:59
Duplicate of #120 

This is a bug with the saving system and we are working on it

**Closed by sirNugg3ts** 2022-03-05 14:59 UTC
Labels: bug, Not Tested
