### ISSUE TITLE
The Vendor stuck (can't see your character)

### ISSUE THREAD

**Issue by BTA10** [Uuvana-Studios/longvinter-windows-client#724] opened 2022-04-09 20:47 UTC
**Describe the bug**
When I go to open the vending machine then accidentally tap Esc button the vendor tab is stuck which I doesn't allow you to see yourself but your still be able to play but with the vendor screen. 

**To Reproduce**
1. Go to 'vendor'
2. Click on 'Esc'
3. Then close the options and the vendor screen will be bug

**Expected behavior**
I'm expecting that the vendor screen will be remove when you go to menu

**Screenshots**
![image](https://user-images.githubusercontent.com/103336082/162591104-a04477a4-f477-4189-aa70-c99d68c7d6bc.png)

**Desktop (please complete the following information):**
 - Windows 11
 - Game Version [ Beta 1.0.2]
 - Steam Version [e.g. UpToDate steam version]

**Additional context**
No other problems game is awesome but it's the only problem I have because I have to reset the whole game again.

**Comment by peterdaly13** [comment] 2022-04-09 20:58
I have the same issue

**Comment by ZEONIAM** [comment] 2022-04-09 21:13
SAME I'M ON STREAM AND THIS IS MAKING ME REALLY SAD. It appears that it accidentally opens multiple instances of the vendor window and then doesn't know how to close the extra window, or ignore the double click thus opening 2 instances. Or, I think a way of fixing this could be having the game react to the second instance of being opened by quickly closing the vendor window completely rather than opening a second instance. THIS IS A HUGE PROBLEM THOUGH

**Comment by ZEONIAM** [comment] 2022-04-09 22:04
okay

so the fix for right now is FOR THE LOVE OF GOD DONT DOUBLE CLICK THE WINDOW. then you're good

**Comment by faketucker** [comment] 2022-04-09 22:29
Duplicate of #410

**Closed by faketucker** 2022-04-09 22:29 UTC
Labels: Bug, Not Tested
