### ISSUE TITLE
Vanished Chest

### ISSUE THREAD

**Issue by TertraMer** [Uuvana-Studios/longvinter-windows-client#504] opened 2022-03-19 15:49 UTC
**Describe the bug**
2 Chest in my house deasapered and my inventory too

**To Reproduce**
1.  Get 3 chest 
2. Disconnect
3. Reconnect 
4. Now only one chest left and my invotory became empty 

**Expected behavior**
I was hopping my chest and inventory still after i deconnected 

**Screenshots**
![image](https://user-images.githubusercontent.com/101939563/159127699-d4aeea16-01b7-45cb-a31f-a0aa04c215ed.png)
![image](https://user-images.githubusercontent.com/101939563/159128047-ff9b1536-1641-4c82-8630-0e6259a42be5.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Game Version 1.0.1
 - Steam Version v020

**Comment by faketucker** [comment] 2022-03-28 05:28
Duplicate of #600

**Closed by faketucker** 2022-03-28 05:28 UTC
Labels: Bug, Not Tested
