### ISSUE TITLE
Vendor UI stuck on screen

### ISSUE THREAD

**Issue by AndresRengifo** [Uuvana-Studios/longvinter-windows-client#709] opened 2022-04-08 01:52 UTC
After pausing the game, the vendor screen wouldn't dissappear once i got far away from it, and it remained completely functional, being able to sell the fish caught even whilst far away.

**Comment by faketucker** [comment] 2022-04-08 02:52
Duplicate of #410

**Closed by faketucker** 2022-04-08 02:52 UTC
