### ISSUE TITLE
Right after the lasted update. My avatar appeared in the river and couldn't move. 

### ISSUE THREAD

**Issue by poonuood** [Uuvana-Studios/longvinter-windows-client#471] opened 2022-03-18 16:00 UTC
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Game Version [e.g. 1.0]
 - Steam Version [e.g. 1.0]

**Additional context**

**Comment by JcYYYYY** [comment] 2022-03-19 13:21
Same issue with me, the moment I got dc and reconnected I got stuck in the middle of the water


![unknown](https://user-images.githubusercontent.com/101933804/159122756-9992fb56-fdd4-440d-b644-025555e7bb20.png)

**Comment by Aiwii** [comment] 2022-03-21 06:50
Am I doomed to become the sage of the river
(Occured after DC and reconnect)
![image](https://user-images.githubusercontent.com/53021785/159215995-d5c607eb-33c7-4db2-97f4-7bb0203b0b80.png)

**Comment by faketucker** [comment] 2022-03-26 15:40
This can happen when you get disconnected from the server and the server rolls back your character when you are in the water. And if you disconnect while in the water, when you log back on, you're unable to move.

**Comment by faketucker** [comment] 2022-03-26 15:40
Duplicate of #565

**Closed by faketucker** 2022-03-26 15:40 UTC
Labels: bug, Not Tested
