### ISSUE TITLE
Right after fishing, got some fishes but doesn't appear in backpack.

### ISSUE THREAD

**Issue by poonuood** [Uuvana-Studios/longvinter-windows-client#472] opened 2022-03-18 16:02 UTC
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Game Version [e.g. 1.0]
 - Steam Version [e.g. 1.0]

**Additional context**

**Comment by GreenySunny** [comment] 2022-03-20 11:26
This bug is solved

**Comment by faketucker** [comment] 2022-03-25 13:57
Duplicate of #469

**Closed by faketucker** 2022-03-25 13:57 UTC
Labels: bug, Not Tested
