### ISSUE TITLE
CHARACTER WIPED - Everytime i log out or exit game!! 

### ISSUE THREAD

**Issue by ItsKiwi88** [Uuvana-Studios/longvinter-windows-client#134] opened 2022-03-02 06:19 UTC
**Describe the bug**
Every time i log out, or close the game and come back my entire character progress has been reset, compendium gone and inventory gone!!

This is worse then the last wipe bug - ive restarted my character about 14-15 times since these bugs started happening, this one is happening to all of my friends too - since the last update!!

I get its the beta and theres going to be bugs, but this is getting a little frustrating having to restart every single time.. tired of looking for fish and feathers and plants over and over.

**To Reproduce**
1. Log out / Close game
2. Log in - Character wiped.

**Expected behavior**
I expect my hours and hours of work to stay saved when i log out, not sure i can keep restarting its getting painful.

**Screenshots**
Pretty self explanatory - N/A

**Desktop (please complete the following information):**
 - OS: Win 10
 - Game Version 1.0.0

**Additional context**
Character only, houses stay - friends all quit because they cant be bothered re doing everything 5 times over

**Comment by sirNugg3ts** [comment] 2022-03-02 10:54
Duplicate of #59

**Closed by sirNugg3ts** 2022-03-02 10:54 UTC
Labels: bug, Not Tested
