### ISSUE TITLE
Cabins disappearing and cabin turned into tent

### ISSUE THREAD

**Issue by SlicedBreadBoi** [Uuvana-Studios/longvinter-windows-client#561] opened 2022-03-23 16:02 UTC
**Describe the bug**
Joined on today and found my friends cabin gone and mine turned into a tent. A fence post was also on the ground.

**To Reproduce**
1. Spend hours making a base
2. Wait for base to get destroyed due to a bug.

**Expected behavior**
For my cabins to not be gone? I don't know how hard it is.

**Screenshots**
![ccaa](https://user-images.githubusercontent.com/102109287/159742584-b04c7323-c17b-4898-9df5-7f691483827e.PNG)

**Desktop (please complete the following information):**

 - OS: Windows
 - Game Version 1.0.1
 - Steam Version Doesn't really matter its an issue with the game not steam.

**Additional context**
Payed 15 dollars for a game. I know its in the earliest stages of early access but still expected the base of the game to be stable. I mean base building is an essential part of the game along with the combat system. You'd think that it would be fixed before anything else since its the only thing that makes people want to play the game this early on.

**Comment by faketucker** [comment] 2022-03-27 02:58
Duplicate of #508

**Closed by faketucker** 2022-03-27 02:58 UTC
Labels: bug, Not Tested
