### ISSUE TITLE
hello, i put my gas stove inside the tent, I can see it before. But then it become invisible but when i want to cook, it can be used but it cant be seen. 

### ISSUE THREAD

**Issue by 10809318a** [Uuvana-Studios/longvinter-windows-client#1003] opened 2022-07-04 10:27 UTC
**Describe the bug**

**To Reproduce**
4. See an error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Game Version [e.g. 1.0]
 - Steam Version [e.g. 1.0]

**Additional context**

**Comment by faketucker** [comment] 2022-07-04 10:46
Duplicate of #978

**Closed by faketucker** 2022-07-04 10:46 UTC
Labels: Bug, Not Tested
