### ISSUE TITLE
shop window bug

### ISSUE THREAD

**Issue by jeongchan-smc** [Uuvana-Studios/longvinter-windows-client#593] opened 2022-03-26 09:46 UTC
**Describe the bug**
shop window bug A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior: The shop window does not disappear after using the shop
1. Go to 'WASD'
2. Click on 'shop'

**Expected behavior**
The shop window does not disappear after using the shop
**Screenshots**
![png](https://user-images.githubusercontent.com/66096382/160234071-e1f63076-4277-47eb-9af3-992a8c56fbed.png)
**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Game Version [e.g. 1.0]
 - Steam Version [e.g. 1.0]

**Additional context**

**Comment by faketucker** [comment] 2022-03-26 09:49
Duplicate of #410

**Closed by faketucker** 2022-03-26 09:49 UTC
Labels: bug, Not Tested
