### ISSUE TITLE
My Farmhouse disappeared & my first house that disappeared, reappeared

### ISSUE THREAD

**Issue by MrsMinzi** [Uuvana-Studios/longvinter-windows-client#1207] opened 2022-09-05 02:18 UTC
**Describe the bug**
1. My house in Peacock Island, disappeared! All the exterior items were still there. No timer, so I'm guessing it didn't decay. I also put in wood 2 days ago. When I entered the Sauna, I see my items with a black screen background. Hoping not to lose that spot, I placed a tent on the same location where the house uses to be. Somehow the items are now in the tent. Please help, I'm really sick of building another house.   

2. My first house disappeared after changing the new intel 12th gen cpu servers. I wasn't able to pick the exact location, but it was very close to it. That house was also near POI and water. Anyways, after couple days, I decided to dismantle that house, and find a new location and the old base was dismantled. 1 or 2 days later, my old house reappeared! I assumed someone placed a house when I left but was curious if this was a bug or a test house. I pressed space at the entrance thinking I would have to enter a code, but to my surprise I entered without a code into a empty house.  

**Expected behavior**
I just expect my farmhouse not to disappear, and my old house disappear? I feel like my account is cursed. Please help me. T_T 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Game Version [e.g. 1.0.8b]
 - Steam Version [current version)

![steamuserimages-a akamaihd](https://user-images.githubusercontent.com/111882439/188348158-ad213029-1e31-455c-a0f0-eb4fa75b98f2.jpg)
![steamuserimages-a akamaihd](https://user-images.githubusercontent.com/111882439/188348189-bb93e655-95ea-4997-be54-3011c6f1bb1a.jpg)
![steamuserimages-a akamaihd](https://user-images.githubusercontent.com/111882439/188348229-79c8a56e-5356-42c6-ac3a-1094cb966af5.jpg)

![steamuserimages-a akamaihd](https://user-images.githubusercontent.com/111882439/188348210-8ff86100-1889-44a3-9100-53ca89833058.jpg)
![steamuserimages-a akamaihd](https://user-images.githubusercontent.com/111882439/188348262-3ccc2685-5c4a-4b40-a58f-473bd866c1ee.jpg)

**Comment by faketucker** [comment] 2024-09-03 11:22
Duplicate of #600

**Closed by faketucker** 2024-09-03 11:22 UTC
Labels: Bug, Not Tested
