### ISSUE TITLE
Game freeze and don't responding 

### ISSUE THREAD

**Issue by AidanPic** [Uuvana-Studios/longvinter-windows-client#1054] opened 2022-07-11 19:38 UTC
**Describe the bug**
The game freeze (i'm french sorry for the spelling mistakes) and i have to open the task manager to close it. it happens two or tree times per hour. 

**Expected behavior**
Not crashing. 

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Game Version : 1.0.8
 - Steam Version Jun 6 2022

**Additional context**
if it helps : 
- ryzen 7 3700 x 
- 2060 super 8 gb 
- 32 gb ram

Also, thank you for the game it is amazing!

**Comment by faketucker** [comment] 2022-07-12 05:24
Did the game use up all of your RAM?

**Comment by faketucker** [comment] 2022-07-12 11:11
Duplicate of #1036

**Closed by faketucker** 2022-07-12 11:11 UTC
Labels: Bug, Not Tested
