### ISSUE TITLE
Stealing items off a property even though when placed, they are Green.

### ISSUE THREAD

**Issue by Lyradessa** [Uuvana-Studios/longvinter-windows-client#199] opened 2022-03-05 13:59 UTC
**Describe the bug**
When placing items, when an item is GREEN it means only you can pick up. When returning to my house after a day, all of my items that I had placed outside on my property have been taken, even though when they were placed they were GREEN, not BLUE. I went and tested this at other people's properties who had open fences, and I was unable to pick up anything because it says it it on someone else's property.

**To Reproduce**
1. Place items on your property.
2. Place them when they show up as GREEN
3. Wait until someone comes to steal it, I guess.

**Expected behavior**
Items you place in GREEN on your property should not be able to be picked up by anyone else but you.

**Screenshots**

Before, when everything had initially been placed and decorated.
![20220304034519_1](https://user-images.githubusercontent.com/100701687/156886068-622d70a7-56a3-4ce8-a2ce-cd9be20e0e18.jpg) 

What I logged in to.
![20220305083013_1](https://user-images.githubusercontent.com/100701687/156886098-27a858be-164d-4153-8bb5-7037f0a414fc.jpg)

Double checking to see if indeed, the green box says "Only you can pick up."
![20220305083305_1](https://user-images.githubusercontent.com/100701687/156886395-9c325f8e-ad02-4ba7-8565-9a43d60602b4.jpg)

Testing to see if I can pick up items on someone else's property. I cannot. The prompt is in the top left corner.
![20220305083414_1](https://user-images.githubusercontent.com/100701687/156886114-968722d5-87a6-427a-8d2a-59fc7314a291.jpg)

Test number two of trying to pick up items on someone else's property. I cannot. The prompt is in the top left corner.
![20220305083430_1](https://user-images.githubusercontent.com/100701687/156886158-5904dd12-214b-43e6-a53a-125e7c3334db.jpg)

**Desktop (please complete the following information):**
 - OS: Windows: 10
 - Game Version: 1.0.0
 - Steam Version:  v020 (I think)

**Additional context**

**Comment by PocketDragon108** [comment] 2022-03-05 21:32
I believe this is someone actually raiding you, looking at your fence the hole is where they go it, anyone with a chain saw can break the item within about a minute and take it. Best advice is to get a turret :)

**Comment by Lyradessa** [comment] 2022-03-06 06:27
> I believe this is someone actually raiding you, looking at your fence the hole is where they go it, anyone with a chain saw can break the item within about a minute and take it. Best advice is to get a turret :)

Then I feel like it should be made more apparent that people raiding can take your stuff. It seems pointless to decorate and gather items if someone can just come along and take it when the prompt says "Only you can pick up". Defeats the purpose of gathering/collecting items unless you get a turret. Which, not a lot of beginners know at all how.

**Comment by PocketDragon108** [comment] 2022-03-06 07:06
yes i agree that there needs to be more information at the start briefing about turrets and whats safe/not. like atlease advised you need a house to be counted as safe property and that you can break things on others property but at the same time advised how you can protect it all with turrets ect

**Comment by faketucker** [comment] 2022-03-26 08:52
I'll close this since it's not a bug

**Closed by faketucker** 2022-03-26 08:52 UTC
Labels: bug, Not Tested
