### ISSUE TITLE
Character Deleted AGAIN!?

### ISSUE THREAD

**Issue by ItsKiwi88** [Uuvana-Studios/longvinter-windows-client#218] opened 2022-03-06 04:40 UTC
**Describe the bug**
Logged on and character had been reset again (after being away only a couple hours)
Ive lost many characters so far but this is by far the most annoying, with over 5 hours of fishing alone, plus completing the full compendium ive lost my character again.

Its been a few good days since the wipe but today i lost it all again :( if theres going to be this many wipes and resets of my character can we please atleast increase fish drop rate its painful doing it over and over :( (the Arctic fish is very hard to get)

i like the game alot but this reset issue is getting old fast :( and with not much end game (yet?) its getting a bit hard to wanna restart time and time again.

keep up the good work devs i know youre working hard.

**To Reproduce**
1. Log out
2. Re enter the game/server and character items and compendium all reset.

**Expected behavior**
To never have character loss ever again ever

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - OS:  W10
 - Game 1.0.0

**Additional context**
N/A

**Comment by sirNugg3ts** [comment] 2022-03-06 13:37
Duplicate of #211

**Closed by sirNugg3ts** 2022-03-06 13:37 UTC
Labels: bug, Not Tested
