### ISSUE TITLE
Broken save file in Uuvana 4 KR

### ISSUE THREAD

**Issue by mjkoh76** [Uuvana-Studios/longvinter-windows-client#1670] opened 2024-08-21 02:49 UTC
From yesterday night, August 20th, Uuvana 4 server frequently load back the old server. The server got fixed when I reloaded the game yesterday, but today morning, it is not fixing. My money when from 7,111,000 to 6,238,000. Please fix this issue. Everyone else in this server is experiencing the same thing. Please don't wipe the server yet. I am so close to rep 3.

**Comment by faketucker** [comment] 2024-09-03 11:54
Duplicate of #600

**Closed as completed by faketucker** 2024-09-03 11:54 UTC
Labels: Bug, Not Tested
