### ISSUE TITLE
Game keeps disconnecting 

### ISSUE THREAD

**Issue by Sammieyy** [Uuvana-Studios/longvinter-windows-client#502] opened 2022-03-19 15:34 UTC
**Describe the bug**
The game keeps disconnecting at random moments and then it takes some time to reconnect.

**To Reproduce**
1. Open the game 
2. Play for a while 
3. Random disconnect 
4. Reconnect again after its loading for a few min
5. Steps 2-4 repeat 

**Expected behavior**
Have the game not disconnect 

**Desktop (please complete the following information):**
 - OS: Windows
 - Game Version: 1.0.1
 - Steam Version: most recent, idk which version

**Comment by faketucker** [comment] 2022-03-27 06:17
Duplicate of #600

**Closed by faketucker** 2022-03-27 06:17 UTC
Labels: bug, Not Tested
