### ISSUE TITLE
Keep losing all progress when joining same server

### ISSUE THREAD

**Issue by ghostgrant96** [Uuvana-Studios/longvinter-windows-client#209] opened 2022-03-05 23:43 UTC
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Game Version [e.g. 1.0]
 - Steam Version [e.g. 1.0]

**Additional context**

**Comment by ghostgrant96** [comment] 2022-03-05 23:44
i play the same official server everytime everytime i rejoin after a couple hours i lose all quests and all money i have saved up. but my home and all my loot remain. so i can go home and still access my things but lose all my money

**Comment by biancawins** [comment] 2022-03-06 14:45
This is driving me crazy too. I log off in my home, and then when i log back in im at an outpost with none of my items or money anymore.

**Comment by sirNugg3ts** [comment] 2022-03-06 14:57
Duplicate of #211

**Closed by sirNugg3ts** 2022-03-06 14:57 UTC
Labels: bug, Not Tested
