### ISSUE TITLE
The bug where all the boxes at home disappear.

### ISSUE THREAD

**Issue by binnir** [Uuvana-Studios/longvinter-windows-client#621] opened 2022-03-29 04:24 UTC
**Describe the bug**
When I opened the door this morning, all the boxes were gone.
I don't know why. There were a lot of things there. Please fix it.
**To Reproduce**
4. See an error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Game Version [e.g. 1.0]
 - Steam Version [e.g. 1.0]

**Additional context**

**Comment by faketucker** [comment] 2022-03-29 04:28
Duplicate of #600

**Closed by faketucker** 2022-03-29 04:28 UTC
Labels: Bug, Not Tested
