### ISSUE TITLE
All Players Kicked / Inventory Rewind / Recently Picked Up Placeables Gone

### ISSUE THREAD

**Issue by jehoshua02** [Uuvana-Studios/longvinter-windows-client#576] opened 2022-03-25 03:09 UTC
**Describe the bug**
Server kicked everyone off. When I reconnected, seemed like I was rewinded like 8 minutes, but my tent, which was on the ground 8 minutes ago, wasn't there. Wasn't purely just a rewind. Some data saved, some didn't.
I had recently picked up my tent and everything that was in it. Now all that stuff is gone.

**To Reproduce**
1. Not sure?

**Expected behavior**
If game history is lost after a crash, would expect all game state, including placeables, not just inventory, to rewind.

**Screenshots**
NA

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Game Version 1.0.1
 - Steam Version Up to date

**Additional context**
NA

**Comment by Kiju-Jager** [comment] 2022-03-25 10:03
j ai eu le meme problème sauf que moi c est toute ma progression qui a disparue mais j ai encore 1 de mes 2 maison mais plus d inventaire d argent ou quoi que ce soit top

**Comment by faketucker** [comment] 2022-03-27 03:46
Duplicate of #600

**Closed by faketucker** 2022-03-27 03:46 UTC
Labels: bug, Not Tested
