### ISSUE TITLE
바다가 하얀색이여서 낙시를 못하겠어요

### ISSUE THREAD

**Issue by yuonge** [Uuvana-Studios/longvinter-windows-client#1300] opened 2022-11-14 14:13 UTC
![KakaoTalk_20221114_231109908](https://user-images.githubusercontent.com/118191364/201681835-502039ee-7cb7-44e0-a5aa-607552ff6402.jpg)
3일째 이래요 좀 고쳐주세요!

**Comment by faketucker** [comment] 2022-11-18 09:35
Toggle DX11 water in the settings.

**Comment by faketucker** [comment] 2022-11-18 09:35
Duplicate of #13

**Closed by faketucker** 2022-11-18 09:35 UTC
Labels: Bug, Not Tested
