### ISSUE TITLE
Item lavitation and lost my turret.

### ISSUE THREAD

**Issue by sdengzaku** [Uuvana-Studios/longvinter-windows-client#838] opened 2022-04-30 10:13 UTC
ID : sdengzaku
Surver : [KR/NEW][HOT]Twitch 24H / NORESET!
Place : 3N 32.5W

It was happened just now.
I placed my turret.
But, turret placed another place.
So, I disbanded the turret.
But I couldn't take my turret. Because the turret pocket is lavitating and I coundn't reach the turret pocket.
Finally, my turret is disappeared..

please return my turret ;(

**Comment by sdengzaku** [comment] 2022-04-30 10:14
![longvinter bug](https://user-images.githubusercontent.com/93140837/166101427-d85175c8-7162-4b05-9bdc-76900c533956.png)
![longvinter bug spot](https://user-images.githubusercontent.com/93140837/166101436-4bacbe32-6f9d-40b0-b764-a8830f46ab2f.png)

**Comment by biffotmc** [comment] 2022-04-30 10:55
Sorry, but we cannot return any items to you

**Comment by sdengzaku** [comment] 2022-04-30 11:32
It happend again and again there. Don't you think fix this bug?

**Comment by faketucker** [comment] 2022-05-01 04:30
Duplicate of #492

**Closed by faketucker** 2022-05-01 04:30 UTC
