### ISSUE TITLE
Cant close vendor menu

### ISSUE THREAD

**Issue by ReikoNyann** [Uuvana-Studios/longvinter-windows-client#371] opened 2022-03-12 05:32 UTC
**Describe the bug**
Vendor menu pops up but cant close even by pressing escape.

**To Reproduce**
1. Go to any outpost
2. Click on any vendor machine
3. Try and close menu
4. Menu still showing even if not near the vendor machineA
5. Menu unable to close unless disconnecting server an reentering

**Expected behavior**
Menu to close once escape key is pressed 

**Screenshots**
![image](https://user-images.githubusercontent.com/97742630/158005277-5a7bafc2-bc92-401e-beae-8c5215009a75.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Game Version [e.g. 1.0]
 - Steam Version [e.g. 1.0]

**Additional context**

**Comment by Mcdonaldsis** [comment] 2022-03-12 20:46
OS: [Linux using steam play]
Game Version [1.00]
Steam Version [v020]

**Comment by mysticmasterfin** [comment] 2022-03-15 03:16
https://user-images.githubusercontent.com/100821214/158299018-1419914e-8951-4a90-a379-ae7d2bb8d1d6.mp4

**Comment by faketucker** [comment] 2022-03-25 14:35
Duplicate of #410

**Closed by faketucker** 2022-03-25 14:35 UTC
Labels: bug, Tested
