### ISSUE TITLE
When you click vendor and are trying to leave vendor, issue arise

### ISSUE THREAD

**Issue by SteamNinjaLord** [Uuvana-Studios/longvinter-windows-client#681] opened 2022-04-05 04:31 UTC
**Describe the bug**
The vendor pop-up box won't close itself when you move your character away or clicking LMB on empty area.

**To Reproduce**
1. Go to 'any vendor area '
2. Click on 'vendor fridge(?) or vendor box '
3. Scroll down to 'when you are done and trying to leave by moving the character or clicking empty area'
4. See an error

**Expected behavior**
It is suppose to let me leave and exit the pop-up box but apparently there is a bug disabling me to exit

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 64bit (rtx 2080 graphics, 64gb ram, built in 2018 custom)
 - Game Version [1.0.2]
 - Steam Version [latest; March 14th 2022 / 12:51:31 / v020]

**Additional context**
I know its paramount to adding more contents and broadening the purpose of the game itself so people keep playing.
but i think balancing the need to adding more reason* for playing and fixing the bug that is disabling you from playing* game is very very very very very very important.

Yes, adding more reason to build a house and connecting electricity and expanding the space inside the house, and having more turrets range upgrade bullet upgrade armors .. you know basically like Minecraft and Rust

but with all those basic intrinsic interface malfunctioning.. you really dont get to play beyond respawn area lol..

Thank you guys!

**Comment by SteamNinjaLord** [comment] 2022-04-05 04:32
![image](https://user-images.githubusercontent.com/103017518/161679232-e4838e4b-4ae1-48c9-9292-59539fd69ce4.png)

**Comment by faketucker** [comment] 2022-04-05 04:33
Duplicate of #410

**Closed by faketucker** 2022-04-05 04:33 UTC
Labels: Bug, Not Tested
