### ISSUE TITLE
Can't get into house

### ISSUE THREAD

**Issue by piakjummpy** [Uuvana-Studios/longvinter-windows-client#683] opened 2022-04-05 05:45 UTC
**Describe the bug**
I click onto my house, and it loads like normal but only to show up still outside my house. At first after three tries, I got into my house, but then now I'm stuck outside my house no matter how many tries. 

**To Reproduce**
1. Go to my house
2. Click on to my house door
3. Scroll down to '.....'
4. See an error: still stuck outside my house

**Expected behavior**
Be able to enter my house

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows] 10
 - Game Version [e.g. 1.0] 1.0.2
 - Steam Version [e.g. 1.0]

**Additional context**

**Comment by faketucker** [comment] 2022-04-05 05:50
Did you place a lot of tihngs in your house?

**Comment by piakjummpy** [comment] 2022-04-05 05:51
> Did you place a lot of things in your house?

Yeah actually quite a lot of things

**Comment by faketucker** [comment] 2022-04-05 05:57
That might be a problem because the game can't teleport you to the spot where you placed things, so it kicks you out. I'm gonna leave this for the devs to look into.

**Comment by piakjummpy** [comment] 2022-04-05 05:58
Ah alright, thanks again faketucker

**Comment by natamru** [comment] 2022-04-12 03:10
I found this out, its sort of the same thing with the teleportation bug.

**Comment by faketucker** [comment] 2022-05-12 11:14
Duplicate of #810

**Closed by faketucker** 2022-05-12 11:14 UTC
Labels: Bug, High Priority
