### ISSUE TITLE
Lost bins full of stuff from inside house

### ISSUE THREAD

**Issue by MJR1972** [Uuvana-Studios/longvinter-windows-client#887] opened 2022-05-19 14:07 UTC
**Describe the bug**
Lost a few bins full of stuff disappeared from inside house.

**To Reproduce**
I'm not sure how to reproduce. Just a few of my containers just vanished with everything inside of them in my house. I stack containers in my house to put things in. I logged in this morning and a couple of the bins were just gone along with everything inside them.

**Expected behavior**
Bins should not disappear and shouldn't lose what is inside

**Screenshots**

**Desktop (please complete the following information):**
 - OS: win 11
 - Game Version 1.0.6
 - Steam Version 1.0.6

**Additional context**

**Comment by faketucker** [comment] 2022-05-19 16:09
May I know which server you are playing on?

**Comment by MJR1972** [comment] 2022-05-19 16:14
[US-WEST] Uuvana 2

Thanks for all your help. Keep up the great work.

**Comment by faketucker** [comment] 2022-05-22 03:14
This can happen, but it appears to be very rare now, and it's difficult to debug when it's rare. I'll put this with the same issue that is still open.

**Comment by faketucker** [comment] 2022-05-22 03:14
Duplicate of #600

**Closed by faketucker** 2022-05-22 03:14 UTC
Labels: Bug, Not Tested

**Comment by syk117** [comment] 2022-12-26 15:36
After getting kicked from DAON-Official Asia server, all item gone, all compendium gone, all money gone except 100 dollars (had like 40,000). Spent days not sleeping, farming, fishing, and now everything is gone.

OS: [Windows]
Game Version [1.0.9.c]
Steam Version [The most updated version]
Steam ID: 76561198409919842
