### ISSUE TITLE
[US] Uuvana 1 progress lost and disconnect on login

### ISSUE THREAD

**Issue by ScoutZozak** [Uuvana-Studios/longvinter-windows-client#50] opened 2022-02-27 16:54 UTC
**Describe the bug**
- [US] Uuvana 1 is constantly disconnecting me. When I logged in initially this morning, I logged in inside of my house. Now every time I attempt connection to [US] Uuvana 1 I spawn at the starting dock with no items/progress and I get disconnected within 5-10 seconds. I believe this issue on [US] Uuvana 1 is not isolated to me because there are 1-2/50 players at all times on the server, but it is server that averages 20 players. 

**To Reproduce**
1 - Log into [US] Uuvana 1
2 - Get immediately disconnected. :(

**Desktop (please complete the following information):**
 - OS: Windows
 - Game Version [e.g. 1.0]
 - Steam Version [e.g. 1.0]

**Comment by JonnyTwoTimez** [comment] 2022-02-27 17:14
This is happening to me right now as well

**Comment by captain-yesterday** [comment] 2022-02-27 17:36
Same thing happening to me just now

**Comment by sirNugg3ts** [comment] 2022-03-01 19:07
disconnect on login was fixed.
Progress lost is a duplicate of #120

**Closed by sirNugg3ts** 2022-03-01 19:07 UTC
Labels: bug, High Priority
