### ISSUE TITLE
Boat not working. [Snow's outpost bug]

### ISSUE THREAD

**Issue by Himgirish** [Uuvana-Studios/longvinter-windows-client#774] opened 2022-04-16 15:58 UTC
**Describe the bug**
If you travel to snow's outpost from a boat then you cannot use any boat from anywhere unless you restart the game or reconnect.
Since Snow's outpost is an important outpost from selling fish it is causing a major issue for me.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to ' any outpost'
2. Click on 'Travel to snow's outpost'
3. Try 'use any boat it won't work'
4. See an error

**Expected behaviour**
Nothing happens when you click on travel to... any outpost.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Game Version [e.g. 1.0]
 - Steam Version [e.g. 1.0]

**Additional context**

**Comment by faketucker** [comment] 2022-04-16 15:59
Duplicate of #666

**Closed by faketucker** 2022-04-16 15:59 UTC
Labels: Bug, Not Tested

**Comment by Himgirish** [comment] 2022-04-16 16:00
That issue was not replicable this one is.
