### ISSUE TITLE
gets stuck in vendor menu 

### ISSUE THREAD

**Issue by hunterbun** [Uuvana-Studios/longvinter-windows-client#673] opened 2022-04-04 03:11 UTC
**Describe the bug**
If you open the vendor menu, you will randomly get stuck in it. The only way to get out of it is to disconnect. Hitting escape does not take you out of it. 

**To Reproduce**
1. Go to vendor
2. Click on vendor
3. get stuck

**Expected behavior**
not get stuck.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Game Version [e.g. 1.0]
 - Steam Version [e.g. 1.0]

**Additional context**

**Comment by faketucker** [comment] 2022-04-04 03:26
Duplicate of #410

**Closed by faketucker** 2022-04-04 03:26 UTC
Labels: Bug, Not Tested
