### ISSUE TITLE
Can't exit vendor menu

### ISSUE THREAD

**Issue by MondayMourning** [Uuvana-Studios/longvinter-windows-client#641] opened 2022-04-01 03:15 UTC
**Describe the bug**

**To Reproduce**
1. Go to Vendor
2. Click on Vendor
4. See an error: If you walk away vendor menu stays stuck and takes you to esc button menu if you click out of it.

**Expected behavior**
If you walk away vendor menu stays stuck and takes you to esc button menu if you click out of it.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Latest version
Latest version. Day one purchase

**Comment by faketucker** [comment] 2022-04-01 03:49
The only way now is to close the game and reopen it again.

**Comment by faketucker** [comment] 2022-04-01 03:49
Duplicate of #410

**Closed by faketucker** 2022-04-01 03:49 UTC
Labels: Bug, Not Tested
