### ISSUE TITLE
Containers missing

### ISSUE THREAD

**Issue by FinnUnreliable** [Uuvana-Studios/longvinter-windows-client#557] opened 2022-03-22 13:01 UTC
**Describe the bug**
6 containers inside my house just vanished, all full of stuff and at random times. 4 earlier in the week, and 2 that I placed literally yesterday.

**To Reproduce**
I have no idea how to replicate it. it just happens whenever I log back into the game the next day.

**Screenshots**
![20220322085005_1](https://user-images.githubusercontent.com/101912185/159485944-6a1a9ef8-7112-48cf-8772-c299eb1e68cf.jpg)
All the empty spots on the backwall are supposed to be containers

**Desktop:**
 - OS: Windows 10 Home
 - Game Version: Beta 1.0.1

**Comment by sirNugg3ts** [comment] 2022-03-22 15:11
Duplicate of #527

**Closed by sirNugg3ts** 2022-03-22 15:11 UTC
Labels: bug, Not Tested
