### ISSUE TITLE
[US] uuvana 1- Lost all progression of items, mk, and compendium upon logging in.

### ISSUE THREAD

**Issue by TBanksT** [Uuvana-Studios/longvinter-windows-client#517] opened 2022-03-20 01:11 UTC
Upon logging in to [US] uuvana 1, I had lost hours worth of items, mk, and compendium progress. 

I expected to log back in to the server with my regular progression, but instead my inventory and the inside of the my house were completely different. I had a total of 5 or 6 containers inside my house, but when I logged in, I only had one. 

Windows 10
Longvinter 1.0.1

My game has glitched many times before where I either disconnect manually or alt + f4 myself to relaunch the game, but this particular time I was disconnected by the game and when I logged back in, a lot of my progression was gone.

**Comment by faketucker** [comment] 2022-03-27 03:47
Duplicate of #600

**Closed by faketucker** 2022-03-27 03:47 UTC
Labels: bug, Not Tested
