### ISSUE TITLE
Achievements not unlocking properly.

### ISSUE THREAD

**Issue by jaschr** [Uuvana-Studios/longvinter-windows-client#691] opened 2022-04-06 00:11 UTC
**Describe the bug**
Certain achievements not unlocking when completing their requirements.

**Expected behavior**
Having a satellite communicator equipped, crafting an item, having a certain amount of mk, etc. would unlock achievement.

I have the 20k mk achievement and not the 5k mk one.

**Screenshots**
![Screenshot 2022-04-05 200946](https://user-images.githubusercontent.com/45179788/161870937-1ff04771-7fc4-457c-9464-3cafff6a5fdd.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Game Version: Beta 1.0.2

**Comment by faketucker** [comment] 2022-04-06 02:39
Duplicate of #421

**Closed by faketucker** 2022-04-06 02:39 UTC
Labels: Bug, Not Tested
