### ISSUE TITLE
server constantly crash every 10 mins, can't pick up woods or harvest once in a while, tent dissapeared with all the items inside.

### ISSUE THREAD

**Issue by gracenlee940** [Uuvana-Studios/longvinter-windows-client#563] opened 2022-03-23 18:05 UTC
I downloaded this game because a couple of streamers in Korea introduced it recently, it has all the potential to get the attention it deserves, however, there are way too many bugs that make ppl run away. First whatever server I play in (the official servers that you created) ppl are getting disconnected every 15~20 mins. If I have the patience to come back a couple of times after reopening the game several times, the left click wouldn't work for only picking up the woods, harvest, and items. Eating still works. The worst bug I've experienced so far is my tent and all the items in them completely vanished after I came back the next day. Since it takes some work and luck for a newbie to build a tent and settle down, I almost deleted this game but I understand it's early access, and you guys are working hard on it.  I've played 2000 + hrs on ACNH so if the server issues get fixed and players are able to open their own servers within the game, I have no doubts that it will be the next hit in the market.

**Comment by faketucker** [comment] 2022-03-27 06:11
Duplicate of #600

**Closed by faketucker** 2022-03-27 06:11 UTC
Labels: bug, Not Tested
