### ISSUE TITLE
Autodefender disappearing when placed

### ISSUE THREAD

**Issue by PadoPool** [Uuvana-Studios/longvinter-windows-client#811] opened 2022-04-20 13:51 UTC
**Describe the bug**
I can place fences, planter box, etc, but when I placed my most expensive autodefenders it just disappears. I finally got electricity and placed the autodefenders for the first time to have all 3 of them disappear into thin air. I tried to place them around my house in the green zone, but when I "successfully" placed them they just disappeared, neither on the ground nor in my inventory. I spent a long long time getting them so this really bugs me out. At first I thought I placed it wrong cause I placed it on a fence, did the second on the fence and did the third on ground. rip all three.

**To Reproduce**
1. Click on inventory near the house
2. Click on autodefender
3. Place in the green zone around the house
4. *Poof* hard work to get them gone.

**Expected behavior**
Autodefender placed

**Screenshots**
No SS. They literally just disappeared before I even knew what was happening. 

**Desktop (please complete the following information):**
 - Windows
 - 1.0.3
 - 1647446817

**Additional context**
I really hope this gets fixed before the next wipe. Like I started few days ago and grinded up to these. If the wipe wasn't so close, in two days, I probably would have quit or sth.

**Comment by faketucker** [comment] 2022-04-20 14:03
Duplicate of #492

**Closed by faketucker** 2022-04-20 14:03 UTC
Labels: Bug, Not Tested
