### ISSUE TITLE
Can't enter house and random bodies in my base

### ISSUE THREAD

**Issue by MentiBruhhhhh** [Uuvana-Studios/longvinter-windows-client#488] opened 2022-03-19 03:07 UTC
**Describe the bug**
I killed one person at the top of the snow area, died bc turrets. When I respawned that person was in my base. I left my base. Died to someone else. Respawned in base and another body is in there. When I left the second time I tried to reenter my own house and I cannot get in. It just tries to load me in and then stays outside.

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/101913515/159104372-18f9a17d-012a-461e-8b1b-cdf988028a00.png)
bottom one is me, middle one is person I killed, top is also me but not active.

**Desktop (please complete the following information):**
 - OS: Windows
 - Game Version Beta 1.0.1
 - Steam Version [e.g. 1.0]

**Additional context**

**Comment by LysianeCroissant** [comment] 2022-03-19 08:50
J'ai le même problème  I have the same problem

**Comment by faketucker** [comment] 2022-03-27 06:22
This might be caused by a server lag, and it's hard to replicate. You should not face this problem if the server is stable. I'm going to close this for now. If you have got anymore info or an exact way to replicate this, feel free to reopen this issue or file a new bug report.

**Comment by faketucker** [comment] 2022-03-27 06:22
Duplicate of #538

**Closed by faketucker** 2022-03-27 06:22 UTC
Labels: bug, Not Tested
