### ISSUE TITLE
LAN Server not saved?

### ISSUE THREAD

**Issue by Gometh-chan** [Uuvana-Studios/longvinter-windows-client#1683] opened 2024-09-15 16:14 UTC
On a LAN hosted server we put in several hours of play, we had cabins, several chests full of stuff, a small farm, and we decided to stop for the night but simply disconnecting and shutting down the client. Upon relaunching we found that the server had reverted by by several hours and we were all the way back to when we had simple tents. But our characters had everything that they had on them when we disconnected.

**Comment by phloyddd** [comment] 2024-09-15 16:27
yeah make sure the host goes into admin panel and clicks the save button before shutting everything down, I think that is what caused this issue for you here.

**Comment by faketucker** [comment] 2024-10-29 03:36
You can follow the steps provided above for now

**Comment by faketucker** [comment] 2024-10-29 03:36
Duplicate of #600

**Closed as completed by faketucker** 2024-10-29 03:36 UTC
Labels: Bug, Not Tested
