### ISSUE TITLE
Save file disappeared

### ISSUE THREAD

**Issue by ginab092** [Uuvana-Studios/longvinter-windows-client#1115] opened 2022-07-29 21:43 UTC
I was disconnected from a West US PVE server and when I finally got back to the main screen, my file was completely gone. There was no continue option...

**Comment by faketucker** [comment] 2022-08-02 06:44
Yeah, this can happen because of a server update, crash or restart.

**Comment by faketucker** [comment] 2022-08-02 06:45
Duplicate of #600

**Closed by faketucker** 2022-08-02 06:45 UTC
