### ISSUE TITLE
Player teleporting and menus not closing

### ISSUE THREAD

**Issue by Invisitn** [Uuvana-Studios/longvinter-windows-client#769] opened 2022-04-16 04:43 UTC
Player character teleporting a few ‘feet’ around map. Direction is not usually tied to direction player was travelling, but often when near water it sends players out for a swim which almost caused me to die from lack of energy. Ping usually around 30-50ms and averages players on server at time between 5-10 so not likely to be linked to an overloaded sever.

Also had issues with new Julia’s mystery shop where after opening shop and purchasing an item for the first time (location directly above Sgt Lakes Outpost just below snow region) menu would not close. It also wasn’t forced to close on moving too far away and even when returning to home and entering/exiting house.

**Comment by faketucker** [comment] 2022-04-16 04:48
Relog the game and it might fix your teleporting problem. For the menu bug, it happens when you double click the vendor.

**Comment by faketucker** [comment] 2022-04-16 04:49
Duplicate of #410

**Closed by faketucker** 2022-04-16 04:49 UTC
Labels: Bug, Not Tested
