### ISSUE TITLE
the water isn't transparent

### ISSUE THREAD

**Issue by Blackearth2** [Uuvana-Studios/longvinter-windows-client#382] opened 2022-03-12 17:03 UTC
**Describe the bug**
I can't see in the water. she is white .
**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [21H2 Windows]
 - Game Version [latest version]
 - Steam Version [latest version]

**Additional context**
I have installed the game since Friday 11/03 and the water has always been opaque I have restarted, reinstalled but nothing has changed. So I can't see the fish in the water  
![2022-03-12](https://user-images.githubusercontent.com/72274363/158027469-a1fa8c2e-a5ee-4709-9e6c-76e5eea6b3e2.png)

**Comment by sirNugg3ts** [comment] 2022-03-12 19:41
Duplicate of #13

**Closed by sirNugg3ts** 2022-03-12 19:41 UTC
Labels: bug, Not Tested
