### ISSUE TITLE
Customization of character changes when loading into game

### ISSUE THREAD

**Issue by blushyjenny** [Uuvana-Studios/longvinter-windows-client#958] opened 2022-06-25 05:48 UTC
**Describe the bug**
Whenever I load into the game through "continue with the recent server", my character customization changes to the default character.

**To Reproduce**
1. Click on "customize your style"
2. Click on "quit"
3. Click "continue (previous server)"
4. See the default character instead of the character you styled/customized

**Expected behavior**
I expected to see the character I customized.

**Screenshots**
![unknown](https://user-images.githubusercontent.com/108168836/175760108-31062e6f-79fc-4b6b-80fb-0d846ae2976e.png)
![unknown](https://user-images.githubusercontent.com/108168836/175760111-d10310bd-93b0-48d8-aa50-d5970bbb2eec.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Game Version 1.0.7b
 - Steam Version 1.0.7b

**Comment by Hataruu** [comment] 2022-06-26 15:45
Same bug as yours

**Comment by faketucker** [comment] 2022-07-11 06:14
Custom skins not showing can happen when the server receives the customization data too late.

**Comment by faketucker** [comment] 2022-07-11 06:14
Duplicate of #1031

**Closed by faketucker** 2022-07-11 06:14 UTC
Labels: Bug, Not Tested
