### ISSUE TITLE
Conteneers in personnal house disapears

### ISSUE THREAD

**Issue by Bertoniaks** [Uuvana-Studios/longvinter-windows-client#330] opened 2022-03-10 10:41 UTC
Hello ! 

During the night, 3 of my personal conteneers desapears ! There were full of weapons, tools, weapon's plan and items to craft them.

I play on Beta 1.00.00.

Thanks for help !

**Comment by sirNugg3ts** [comment] 2022-03-10 11:43
Duplicate of #283

**Closed by sirNugg3ts** 2022-03-10 11:43 UTC
Labels: bug, Not Tested
