### ISSUE TITLE
Hairstyle / Eyebrows set to default.

### ISSUE THREAD

**Issue by kuicani** [Uuvana-Studios/longvinter-windows-client#1153] opened 2022-08-07 20:28 UTC
Can't change Hairstyle or Eyebrows on Uuvana 1. It works on other servers, but when logging in the server I play on, my style is set back to Default.

**Comment by faketucker** [comment] 2022-09-18 12:49
Duplicate of #1031

**Closed by faketucker** 2022-09-18 12:49 UTC
Labels: Bug, Not Tested
