### ISSUE TITLE
Shop screen remains open and will not go away

### ISSUE THREAD

**Issue by LadyKorie11** [Uuvana-Studios/longvinter-windows-client#692] opened 2022-04-06 02:19 UTC
When I go to the shop with the J sometimes the shop screen won't go away and it blocks my view no matter if I hit tab, enter or click off the screen. I also press the x button in the corner and it doesn't work either. I've had to stop log off and sometimes even restart my PC.

**Comment by cherryblossom2020** [comment] 2022-04-06 02:26
Duplicate of #410

**Closed by cherryblossom2020** 2022-04-06 02:26 UTC
Labels: Bug, Not Tested
