### ISSUE TITLE
Cabinet stock in the wall(tried workingbench)

### ISSUE THREAD

**Issue by kevinan2** [Uuvana-Studios/longvinter-windows-client#1104] opened 2022-07-28 15:48 UTC
**Describe the bug**

all my cabinet stock to wall so 
I’v tried to resintall workingbench and upgrade to second floor and it shows that its already upgraded to second floor althou i didnt do anything yet.
My cabinet stock to wall and i dnt have second floor either. All my items r there.
![15E227F1-A913-4F57-80A7-4760031C3856](https://user-images.githubusercontent.com/106910721/181581397-f327825e-a1c0-4b7e-a30b-ceda11feca07.jpeg)
![0EDF012D-283C-458C-92A8-B2F43AEFF149](https://user-images.githubusercontent.com/106910721/181581449-3aeeaa7c-e1fe-4f48-8b16-5fa26761e6d8.jpeg)

**To Reproduce**
4. See an error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Game Version [e.g. 1.0]
 - Steam Version [e.g. 1.0]

**Additional context**

**Comment by kbs4674** [comment] 2022-07-28 15:51
hello, please look at this comment. 
https://github.com/Uuvana-Studios/longvinter-windows-client/issues/1099

안녕하세요. 위에 올린 링크에 해결법이 있으니 참고 부탁드립니다.

**Comment by kevinan2** [comment] 2022-07-28 16:11
> hello, please look at [#1099 (comment)](https://github.com/Uuvana-Studios/longvinter-windows-client/issues/1099#issuecomment-1198308412) this comment. you can find how to solve problem.
> 
> 안녕하세요. [#1099 (comment)](https://github.com/Uuvana-Studios/longvinter-windows-client/issues/1099#issuecomment-1198308412) 여기에 해결법이 있으니 참고 부탁드립니다.

U don’t get my point. I’ve already tried all what they told me and even with MOD. 
i didn’t even fill up any item to upgrade second floor but it shows i already upgraded to it. So all my cabitnet r still outside of wall and its not upgraded to second floor. After this update, my item and money and compendium r reset to 0. And also house happen like this. And many players r experiencing same as me. I knw its early access and beta but this makes players frustrating and disappoint.

**Comment by kbs4674** [comment] 2022-07-28 18:03
@Sillvvvv 
Actually, `Second Floor` house has not been upgraded, but it seems bug that the `Secod floor` installed.
실제로 2층집이 업그레이드 되지 않았으나, 2층집이 설치된 상태로 있는것도 하나의 버그로 보여집니다..

since there have been many bugs since the update, As a Korean manager, I apologize `1.0.8b` update issue.
일단 이번 업데이트 이후로 많은 버그가 있다보니.. 한국 관리자로서도 이렇게 사과드립니다..

I'd like to help you with this issue, but I don't have official server authorized. Currently, there are some difficulties restore house , items due to the our game running Early Access. I'm really sorry about this...
저도 이부분에 대해선 도와드리고 싶으나, 공식서버 권한이 없으면서도.. 현재 Early Access로 운영되는 정책 상 아이템 복구 관련해서는 어려운 부분이 있습니다.. 정말 이부분에 대해선 죄송합니다...

**Comment by Sillvvvv** [comment] 2022-07-28 18:08
> @Sillvvvv Actually, `Second Floor` house has not been upgraded, but it seems bug that the `Secod floor` installed. currently for solve problem, you should decay house & build house again. 실제로 2층집이 업그레이드 되지 않았으나, 2층집이 설치된 상태로 있는것도 하나의 버그로 보여집니다. 지금으로서 해결방법은 집을 철거하고 다시 짓는 수 밖에 없습니다..
> 
> since there have been many bugs since the update, As a Korean manager, I apologize `1.0.8b` update issue. 일단 이번 업데이트 이후로 많은 버그가 있다보니.. 한국인 관리자로서도 이렇게 사과드립니다..
> 
> I'd like to help you with this issue, but I don't have official server authorized. Currently, there are some difficulties restore house , items due to the our game running Early Access. I'm really sorry about this... 저도 이부분에 대해선 도와드리고 싶으나, 공식서버 권한이 없으면서도.. 현재 Early Access로 운영되는 정책 상 집&아이템 복구 관련해서는 어려운 부분이 있습니다.. 정말 이부분에 대해선 죄송합니다...

It's okay, devs in the discord server said they'll fix it tomorrow <3

**Comment by kevinan2** [comment] 2022-07-28 18:40
> @Sillvvvv Actually, `Second Floor` house has not been upgraded, but it seems bug that the `Secod floor` installed. currently for solve problem, you should decay house & build house again. 실제로 2층집이 업그레이드 되지 않았으나, 2층집이 설치된 상태로 있는것도 하나의 버그로 보여집니다. 지금으로서 해결방법은 집을 철거하고 다시 짓는 수 밖에 없습니다..
> 
> since there have been many bugs since the update, As a Korean manager, I apologize `1.0.8b` update issue. 일단 이번 `1.0.8b` 업데이트 이후로 많은 버그가 있다보니.. 한국인 관리자로서도 이렇게 사과드립니다..
> 
> I'd like to help you with this issue, but I don't have official server authorized. Currently, there are some difficulties restore house , items due to the our game running Early Access. I'm really sorry any inconvenience... 저도 이부분에 대해선 도와드리고 싶으나, 공식서버 권한이 없으면서도.. 현재 Early Access로 운영되는 정책 상 집&아이템 복구 관련해서는 어려운 부분이 있습니다.. 정말 이부분에 대해선 죄송합니다...

Dev in discord said they will update and fix it tomorrow. No need to decay house and build it again.

**Comment by kbs4674** [comment] 2022-07-28 19:10
https://discord.com/channels/846308806870695967/880859106989178880/1002249269874544700

I just checked few minutes ago,
I apologize wrong answer.
저도 이제사 확인했습니다.
잘못된 답변 드린 점 죄송합니다.

**Comment by faketucker** [comment] 2022-07-29 12:57
Duplicate of #1099

**Closed by faketucker** 2022-07-29 12:57 UTC
Labels: Bug, Not Tested
