### ISSUE TITLE
I CAN'T ENTER MY OWN HOUSE LOL.... THAT BUG WHEN U ENTER U GET KICKED OUT ASAP

### ISSUE THREAD

**Issue by huntergc** [Uuvana-Studios/longvinter-windows-client#981] opened 2022-07-01 20:02 UTC
I CAN'T ENTER MY OWN HOUSE
WHEN I'M GOING IN WILL BE FAST TO KICKED OUTSIDE

**Comment by faketucker** [comment] 2022-07-02 05:01
Is there anything inside that blocks your doorway?

**Comment by huntergc** [comment] 2022-07-02 05:12
No, im in my house and only loading and still outsite

Pada tanggal Sab, 2 Jul 2022 12.01, tucker ***@***.***>
menulis:

**Comment by faketucker** [comment] 2022-07-11 06:25
Duplicate of #943

**Closed by faketucker** 2022-07-11 06:25 UTC
Labels: Bug, Not Tested
