### ISSUE TITLE
Issues on different servers

### ISSUE THREAD

**Issue by zigglesbee** [Uuvana-Studios/longvinter-windows-client#477] opened 2022-03-18 20:05 UTC
In [US] uuvana 1- my character went off the initial dock and is stuck in the water unable to go anywhere.
In [US] uuvana 7- there is a glitch at the fishing outposts showing generators floating near the campfire.
In [US] uuvana 6- There is a glitch in one of the fishing spots by the fishing outposts and there is a bug when selling at James general store at one of the spots on the right big island where the selling window does not close even when walking away.
For some reason, my friend's server is not pulling up either (server 90157225233473539).

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Game Version [e.g. 1.0]
 - Steam Version [e.g. 1.0]

**Additional context**

**Comment by faketucker** [comment] 2022-03-29 04:25
> In [US] uuvana 1- my character went off the initial dock and is stuck in the water unable to go anywhere.

Duplicate of #565

> In [US] uuvana 7- there is a glitch at the fishing outposts showing generators floating near the campfire.

That was a hacker messing with the server.

> In [US] uuvana 6- There is a glitch in one of the fishing spots by the fishing outposts and there is a bug when selling at James general store at one of the spots on the right big island where the selling window does not close even when walking away.

Duplicate of #410

**Closed by faketucker** 2022-03-29 04:25 UTC
Labels: Bug, Not Tested
