### ISSUE TITLE
Can't see any servers or create one

### ISSUE THREAD

**Issue by etrinh96** [Uuvana-Studios/longvinter-windows-client#648] opened 2022-04-01 20:41 UTC
Hi I just bought this game today and I am unable to play the game. There are no servers showing up on the list and I tried logging in and out of the game. I restarted everything and it still hasn't shown up.

**Comment by monkeycheatcom** [comment] 2022-04-02 01:54
same here

**Comment by faketucker** [comment] 2022-04-02 02:56
It takes some time to load all the servers because the game tries to ping every server to get all the response time. And sometimes it makes the server list not show up at all.

**Comment by faketucker** [comment] 2022-04-02 02:56
Duplicate of #238

**Closed by faketucker** 2022-04-02 02:56 UTC
Labels: Bug, Not Tested
