### ISSUE TITLE
House, Fences, bushes disappearing after update

### ISSUE THREAD

**Issue by thevoidsylph** [Uuvana-Studios/longvinter-windows-client#481] opened 2022-03-18 21:36 UTC
**Describe the bug**

I logged in after the update and my boyfriend's house disappeared along with fences, bushes (the squared ones) and actual bushes and plants. Help?

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/101904969/159086083-2bdad5b6-971a-462f-a402-b94891be2407.png)

![image](https://user-images.githubusercontent.com/101904969/159088527-a009a7b8-ff95-4a20-b009-b1c7a03cbcf4.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Game Version [e.g. 1.0]
 - Steam Version [e.g. 1.0]

**Additional context**

**Comment by faketucker** [comment] 2022-03-27 06:26
Duplicate of #600

**Closed by faketucker** 2022-03-27 06:26 UTC
Labels: bug, Not Tested
