### ISSUE TITLE
Game doesn't save? 

### ISSUE THREAD

**Issue by Sammieyy** [Uuvana-Studios/longvinter-windows-client#510] opened 2022-03-19 19:35 UTC
**Describe the bug**
Items I've gathered and chests I've placed down the last few hours are gone. 

**To Reproduce**
1. Play the game, gathered items, bought chests
2. Put them in my house 
3. Logged out 
4. Logged back in few hours later
5. Items from the previous hours are gone 

**Expected behavior**
I'd like the game to save my progress

**Desktop (please complete the following information):**
 - OS: windows 
 - Game Version 1.0.1
 - Steam Version most recent one

**Comment by faketucker** [comment] 2022-03-27 06:14
Duplicate of #527

**Closed by faketucker** 2022-03-27 06:14 UTC
Labels: bug, Not Tested
