### ISSUE TITLE
Rugs placed in house disappear under floor

### ISSUE THREAD

**Issue by BellaJen** [Uuvana-Studios/longvinter-windows-client#687] opened 2022-04-05 16:00 UTC
**Describe the bug**
When placing a rug in a house it does not show on the floor, it's layer appears to be beneath the floor layer.

**To Reproduce**
1. Go to Inventory
2. Click on Any Rug
3. Attempt to place
4. See an error via no visible rug once placed

**Expected behavior**
Rug is not visible

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Game Version Beta 1.0.2

**Comment by sirNugg3ts** [comment] 2022-04-05 16:02
please give us a screenshot or videos

**Comment by faketucker** [comment] 2022-04-05 16:03
Duplicate of #522

**Closed by faketucker** 2022-04-05 16:03 UTC
Labels: Bug, Not Tested

**Comment by Stellet** [comment] 2022-04-06 04:46
Hi!
The same happens here.
In these images you can see that it allows placement, but only at the entrance.

![image](https://user-images.githubusercontent.com/15570848/161897109-d08f800f-f54f-4a4a-b56f-797c92c9b58d.png)

![image](https://user-images.githubusercontent.com/15570848/161897373-bdb972fe-d682-40d9-81c0-ea62aef55862.png)

**Comment by deerfairy** [comment] 2022-04-15 23:05
![image](https://user-images.githubusercontent.com/103790414/163651201-e250abdc-4a0d-4bd7-b874-55ec8d574666.png)
So I just tried to place a rug in my house. I had to remove the bench and stool in order to place it and when I did, it disappeared like the others here. This is after the update so I'm on Beta 1.0.3
