### ISSUE TITLE
Two music tracks playing at the same time

### ISSUE THREAD

**Issue by thiquid** [Uuvana-Studios/longvinter-windows-client#795] opened 2022-04-17 21:32 UTC
Logged in to play today and 2 songs were playing over top each other. And they were in different keys so it was extra annoying. Also when I adjust music volume to 0 and back up, the music never  plays again other than during boat travel

**Comment by faketucker** [comment] 2022-04-17 23:36
Duplicate of #618

**Closed by faketucker** 2022-04-17 23:36 UTC
