### ISSUE TITLE
Add more wood then possible to Base Upkeeping

### ISSUE THREAD

**Issue by DustinDEV2more** [Uuvana-Studios/longvinter-windows-client#883] opened 2022-05-14 15:51 UTC
**Describe the bug**
Players can deposit more wood to the Base Upkeep section to their house then it should be possible. The count is then by (for example) 66/60

**To Reproduce**
1. Deposit 59 wood to the Base Upkeep
2. Get more then one wood in the inventory
3. Depoit them again

**Expected behavior**
All the extra wood has been addet to the house

**Screenshots**
![image](https://user-images.githubusercontent.com/45263590/168439201-27af24f7-675d-4eec-9297-5c0765fdcfb5.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Game Version 1.0.6

**Comment by faketucker** [comment] 2022-05-14 18:46
Duplicate of #880

**Closed by faketucker** 2022-05-14 18:46 UTC
Labels: Bug, Not Tested
