### ISSUE TITLE
Cannot reach my items after I died in the water

### ISSUE THREAD

**Issue by Nosraks** [Uuvana-Studios/longvinter-windows-client#1001] opened 2022-07-03 22:19 UTC
**Describe the bug**
I cannot reach my backpack after I died in the water under a fishing spot
**To Reproduce**
1. Swim on top of a fishing spot
2. Run out of stamina and drown

**Expected behavior**
I thought that I'd be able to reach my items even though they are in the water

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Game Version: 1.0.8

**Comment by faketucker** [comment] 2022-07-04 03:52
Duplicate of #450

**Closed by faketucker** 2022-07-04 03:52 UTC
Labels: Bug, Not Tested
