### ISSUE TITLE
New update 

### ISSUE THREAD

**Issue by DatBoyJa** [Uuvana-Studios/longvinter-windows-client#796] opened 2022-04-17 22:03 UTC
**Describe the bug**

**To Reproduce**
4. See an error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Game Version [e.g. 1.0]
 - Steam Version [e.g. 1.0]

**Additional context**

Ok so i got every upgrade for the electric path yet i only have 60 power still and it fluctuates from 60-80 so when i set up the 3rd turret it will be online sometimes and other times be down

**Comment by faketucker** [comment] 2022-04-17 23:34
Duplicate of #797

**Closed by faketucker** 2022-04-17 23:34 UTC
Labels: Bug, Not Tested
