### ISSUE TITLE
Clicking a shop twice on accident causes GUI to stay permanently

### ISSUE THREAD

**Issue by KGreyJ** [Uuvana-Studios/longvinter-windows-client#670] opened 2022-04-03 20:32 UTC
It's really annoying, if you accidentally even double tap a GUI shop, any of them, it'll open twice and the second one can't be closed without disconnecting entirely.

**Comment by faketucker** [comment] 2022-04-03 22:49
Duplicate of #410

**Closed by faketucker** 2022-04-03 22:49 UTC
