### ISSUE TITLE
 I can't see the water

### ISSUE THREAD

**Issue by aguantechaca** [Uuvana-Studios/longvinter-windows-client#196] opened 2022-03-05 12:54 UTC
After making a couple of changes to the video settings the water just disappeared and i cant fix it.
I tried closing and reopening the game, changing the settings again, restarting my pc, even deleting and reinstalling the game; but nothing works.

![Captura de pantalla (198)](https://user-images.githubusercontent.com/101002429/156883940-4012f56f-4cf3-46ad-a274-d5779acf4fff.png)
![Captura de pantalla (199)](https://user-images.githubusercontent.com/101002429/156883958-bd970a34-e069-4a82-b997-8980a974295f.png)

Longvinter Beta 1.0.0

**Comment by sirNugg3ts** [comment] 2022-03-05 14:49
Duplicate of #13

**Closed by sirNugg3ts** 2022-03-05 14:49 UTC
Labels: bug, Not Tested
