### ISSUE TITLE
I was stuck in the vendor buy menu

### ISSUE THREAD

**Issue by al1encode** [Uuvana-Studios/longvinter-windows-client#639] opened 2022-03-31 15:39 UTC
I dont know what i did, but i couln't click anywhere and the buy menu did not disappear.

**Comment by faketucker** [comment] 2022-03-31 15:40
The only way now is to close the game and reopen it again.

**Comment by faketucker** [comment] 2022-03-31 15:40
Duplicate of #410

**Closed as completed by faketucker** 2022-03-31 15:40 UTC
