### ISSUE TITLE
오늘갑자기 있던집이 눈앞에서 사라졌어여 사우나안에서 봤는데 아이템도 싹다 사라졌습니다 복구부탁드려요

### ISSUE THREAD

**Issue by subugi** [Uuvana-Studios/longvinter-windows-client#1539] opened 2023-08-31 05:26 UTC
**Describe the bug**
첫번째집들어갔다가 두번째집들어갔다가나왔는데 눈앞에서 사라졌어요 혹시나하고 텐트쳐서 안에확인해봤는데 아이템도 사라져있습니다

**To Reproduce**
![image](https://github.com/Uuvana-Studios/longvinter-windows-client/assets/143411327/cf2322dd-d029-42b2-9341-9af62428a735)

4. See an error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Game Version [e.g. 1.0]
 - Steam Version [e.g. 1.0]

**Additional context**

**Comment by faketucker** [comment] 2024-09-07 12:04
Progress and items may be lost during the update or when the server restarts. We cannot fully compensate everyone. Please contact our community manager via [Discord](https://discord.gg/longvinter) or [live chat](https://longvinter.channel.io/home) for further assistance.

**Comment by faketucker** [comment] 2024-09-07 12:04
Duplicate of #600

**Closed as completed by faketucker** 2024-09-07 12:04 UTC
Labels: Bug, Not Tested
