### ISSUE TITLE
Can't access any inventory in house 

### ISSUE THREAD

**Issue by Zealot303** [Uuvana-Studios/longvinter-windows-client#1114] opened 2022-07-29 21:14 UTC
Boxes are yet again behind walls. I had already moved boxes according to where the house interior was yesterday after the update. Now all my boxes are in places they cannot be accessed. I'm in Uuvana 2. 

![20220729150842_1](https://user-images.githubusercontent.com/110201239/181843922-79a63459-245e-4951-abc8-fae45dc9d030.jpg)

![20220729150827_1](https://user-images.githubusercontent.com/110201239/181843950-f51b2426-7b1f-4201-bed8-3de8f6f10eba.jpg)

**Comment by Zealot303** [comment] 2022-07-29 21:16
I also cannot leave my house without disconnecting from the game and reconnecting upon exiting. there's no walls or gates blocking my path either.

**Comment by Zealot303** [comment] 2022-07-31 05:10
Still cannot access any inventory

**Comment by faketucker** [comment] 2022-08-02 06:45
Duplicate of #1099

**Closed by faketucker** 2022-08-02 06:45 UTC
