### ISSUE TITLE
Workbench gives message on opening

### ISSUE THREAD

**Issue by d3dx9** [Uuvana-Studios/longvinter-windows-client#1177] opened 2022-08-20 17:12 UTC
**Describe the bug**
Workbench just gives message with upgrade your research base but sometimes it shows the right thing.

Also when it works you can't deposit anything, it goes white and disappears. The save game is taken from 1.0.8 - after replacing the workbench it seems to work fine again.

**To Reproduce**
1. Open workbench inside your house

**Expected behavior**
Seeing the normal message which worked in 1.0.8

**Screenshots**
![image](https://user-images.githubusercontent.com/6445635/185758709-a50d6a97-8bf1-4220-bf74-d780fa885a32.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows] Windows 11
 - Game Version [e.g. 1.0] 1.0.9
 - Steam Version [e.g. 1.0]

**Comment by Jalsson** [comment] 2022-11-10 13:13
I belive this issue was caused by duplicate workbenches that caused them to not find the house they are placed in. Issue should be fixed in next update where workbench destroys any other workbenches standing on its way

**Closed by Jalsson** 2022-11-10 13:13 UTC
Labels: Bug, Low Priority, Not Tested
