### ISSUE TITLE
Full Inventory Dissapear

### ISSUE THREAD

**Issue by kyler709** [Uuvana-Studios/longvinter-windows-client#1699] opened 2024-10-07 01:54 UTC
**Describe the bug**
I logged a couple hours after playing for a bit and when i got on my entire inventory was wiped clean. Various items and everything i had equipped gone. As if my character died but i didnt as i logged out at a campfire and relogged at the exact same spot. i didnt log out during combat so i shouldnt have "died" as a result of battlelogging.

**To Reproduce**
N/A unknown reason why it happened.

**Expected behavior**
N/A

**Screenshots**
Just a clear inv with my money

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Game Version 1.14
 - Steam Version [e.g. 1.0]

**Additional context**

**Comment by faketucker** [comment] 2024-10-29 03:37
Duplicate of #600

**Closed as completed by faketucker** 2024-10-29 03:37 UTC
Labels: Bug, Not Tested
