### ISSUE TITLE
Chests and cabbinnets dissapierd from house lol 9 hours gone!

### ISSUE THREAD

**Issue by Aralyftg** [Uuvana-Studios/longvinter-windows-client#1008] opened 2022-07-05 11:05 UTC
When ı enter my house my cabbinets are gone
Lost items and cabbinets

**To Reproduce**
4. See an error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Game Version [e.g. 1.0]
 - Steam Version [e.g. 1.0]

**Additional context**

**Comment by faketucker** [comment] 2022-07-05 11:16
Duplicate of #1006

**Closed by faketucker** 2022-07-05 11:16 UTC
Labels: Bug, Not Tested
