### ISSUE TITLE
Turrets Broken?

### ISSUE THREAD

**Issue by OGPDTHUMS** [Uuvana-Studios/longvinter-windows-client#856] opened 2022-05-04 06:13 UTC
I am having concerns last update turrets were defending my base well shooting at people who get too close to my base, now they don't shoot at people at all unless they are using a weapon or chainsaw allowing them to hide behind things or making my turrets shoot my own fence. 

Also being able to place turrets 2 fences high was dope, wondering why that had to go away made the game much more interesting as there is still ways around it for other players to raid base. 

Game is tons of fun just some questions really about the turrets.

**Comment by faketucker** [comment] 2022-05-04 06:20
I already answer you in #836

**Comment by faketucker** [comment] 2022-05-04 06:20
Duplicate of #836

**Closed by faketucker** 2022-05-04 06:20 UTC
Labels: Bug, Not Tested
