### ISSUE TITLE
Camera Zoom

### ISSUE THREAD

**Issue by TaanKeD** [Uuvana-Studios/longvinter-windows-client#693] opened 2022-04-06 03:15 UTC
When entering and leaving a house, sometimes the camera gets stuck zoomed in, zooming out doesn't work.

Longvinter 1.0.2
Windows 11

**Comment by faketucker** [comment] 2022-04-06 03:25
Can you provide us with a video?

**Comment by faketucker** [comment] 2022-04-07 14:49
Duplicate of #36

**Closed by faketucker** 2022-04-07 14:49 UTC
Labels: Bug, Not Tested
