### ISSUE TITLE
Planting in planters: 

### ISSUE THREAD

**Issue by Plurbaybee** [Uuvana-Studios/longvinter-windows-client#460] opened 2022-03-17 21:23 UTC
**Describe the bug**
When I go to plant a poppy in the planter were after theres a full size flower already growing, the seed will plant on a level that isn't in the planter. It's actually above where the height of the regular full grown poppy is. 

**To Reproduce**

**Expected behavior**

We wanted to keep the poppy that was full grown, and plant the poppy seed with it on the same level as the planter soil. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Game Version [e.g. 1.0]
 - Steam Version [e.g. 1.0]

**Additional context**

**Comment by faketucker** [comment] 2022-03-26 07:09
Duplicate of #309

**Closed by faketucker** 2022-03-26 07:09 UTC
Labels: bug, Not Tested
