### ISSUE TITLE
A fence disappears after you place it

### ISSUE THREAD

**Issue by KoalaBoy** [Uuvana-Studios/longvinter-windows-client#404] opened 2022-03-14 04:23 UTC
**Describe the bug**
A fence disappears after you place it

**To Reproduce**
1. Place a fence
2. Wait
3. It disappears

**Expected behavior**
A fence does not disappear

[**Video**](https://youtu.be/vArnlLW60TQ)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Game Version 1.0.0
 - Steam Version Latest

**Additional context**
I'm not sure what causes this. I just ran into someone and they asked me why did their fences keep disappearing. When they place it close to their house it doesn't disappear, but when they place it farther it disappears.

**Comment by jehoshua02** [comment] 2022-03-16 02:56
I am also seeing this. Placed a fence in the green zone. Waited a few seconds. Fence disappears. If you need more info, I can hop on discord and share screen, reproduce the issue, and share server logs and anything else that would be helpful.

**Comment by jehoshua02** [comment] 2022-03-16 03:04
Also, ironic that this is issue #404.

**Comment by sirNugg3ts** [comment] 2022-03-17 12:35
Duplicate of #187

**Closed by sirNugg3ts** 2022-03-17 12:35 UTC
Labels: bug, Not Tested
