### ISSUE TITLE
Duplicated character

### ISSUE THREAD

**Issue by Naert3v** [Uuvana-Studios/longvinter-windows-client#538] opened 2022-03-21 15:41 UTC
**Describe the bug**
My character died and was teleported home. I grabbed a couple items from a container and then my character was teleported back to the death spot and instantly died again (dropping the items I had just picked up). After a moment I was teleported back home, but a copy of my character was there (just standing). I closed and reopened game, character is still there just higher in the air (now on ground again in screenshot below) and a different colour shirt now. 

**To Reproduce**
I am not sure. 

**Expected behavior**

**Screenshots**
 
![image](https://user-images.githubusercontent.com/101681892/159297193-a322229d-a2d7-48e7-bf25-4c1abf6e7ec7.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows] windows 10
 - Game Version [e.g. 1.0] 1.0.1
 - Steam Version [e.g. 1.0]

**Additional context**
Server lag

**Comment by faketucker** [comment] 2022-03-27 03:10
This might be caused by a server lag, and it's hard to replicate. You should not face this problem if the server is stable. I'm going to close this for now. If you have got anymore info or an exact way to replicate this, feel free to reopen this issue or file a new bug report.

**Closed by faketucker** 2022-03-27 03:10 UTC
Labels: bug, Not Tested
