### ISSUE TITLE
vending machine menu

### ISSUE THREAD

**Issue by havster100** [Uuvana-Studios/longvinter-windows-client#474] opened 2022-03-18 17:03 UTC
**Describe the bug**
A when i click on the vending machines around the map every now and then it wont let me close the vending machine menu of the screen and i have to leave the server and come back on two get it two go away 
**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Game Version [e.g. 1.0]
 - Steam Version [e.g. 1.0]

**Additional context**

**Comment by sirNugg3ts** [comment] 2022-03-18 18:48
Duplicate of #410

**Closed by sirNugg3ts** 2022-03-18 18:48 UTC
Labels: bug, Not Tested
