### ISSUE TITLE
Water issues

### ISSUE THREAD

**Issue by anuvys** [Uuvana-Studios/longvinter-windows-client#153] opened 2022-03-03 01:38 UTC
First, the game automatically displays water gray or white, it gets fixed by clicking on the option "toggle DX11 water", today i clicked on the option "auto-detect" (to the left side of toggle DX11 water" of the options menu) and water became transparent, i tried restarted the game and modifyng option but nothing seems to work.
![water_bug](https://user-images.githubusercontent.com/68031227/156479592-1426c145-4038-451e-a359-3fa774ac4c69.png)

Windows 11
Client 1.0.0

**Comment by sirNugg3ts** [comment] 2022-03-03 13:15
Duplicate of #13

**Closed by sirNugg3ts** 2022-03-03 13:15 UTC
Labels: bug, Not Tested
