### ISSUE TITLE
character customization and achievements

### ISSUE THREAD

**Issue by foxuwua** [Uuvana-Studios/longvinter-windows-client#1081] opened 2022-07-25 14:59 UTC
my hair style looks as a default beret style despite having updated it on character customization tab multiple times. the rest of the outfit is correct, only the hair.
i got 2 achievements out of blue today. while i was at my home i got "I am not done yet" and while i was walking in snow region i got "Keep feathering it" despite not having done the achievement requirements. Also sometimes character doesn't walk and floats in the air.

**Comment by bugeyeyork** [comment] 2022-07-27 18:50
I get the hairstyle bug pretty often as well.

**Comment by faketucker** [comment] 2022-08-02 06:55
Duplicate of #1031 and #421

**Closed by faketucker** 2022-08-02 06:55 UTC
