### ISSUE TITLE
Inventory-store bug

### ISSUE THREAD

**Issue by Aka-Me2** [Uuvana-Studios/longvinter-windows-client#529] opened 2022-03-20 16:41 UTC
I was going to the store at one of the docks, but then I couldn't close out of the store, instead it opened my inventory

Go to the dock, spam one of the stores.

it should open up your inventory and the store, so when you try to close it out with tab it doesn't work

![image_2022-03-20_104036](https://user-images.githubusercontent.com/88689769/159172889-ef82a845-5630-4393-8979-8f8ae28efa6f.png)

**Desktop (please complete the following information):**
 - Windows
 - Game Version 1.0.1
 - Steam Version no idea

**Comment by Naert3v** [comment] 2022-03-21 15:46
I have been getting this a lot too!

**Comment by sirNugg3ts** [comment] 2022-03-21 17:56
Duplicate of #410

**Closed by sirNugg3ts** 2022-03-21 17:56 UTC
Labels: bug, Not Tested
