### ISSUE TITLE
player avatar in my house

### ISSUE THREAD

**Issue by alekskid33** [Uuvana-Studios/longvinter-windows-client#511] opened 2022-03-19 20:24 UTC
after my team mate place tent next to my house, a player avatar pop in the midlle of my house and block me for movin in the center of the house

don't know how to reproduce, but now it happen even when re up the game

i excepted that this not happen anymare

![IMG-3591](https://user-images.githubusercontent.com/101949879/159137293-0ec8bd0d-b2f2-4739-9a74-7cf67afd09e9.jpg)

 - OS: windows
 - Game Version 1.01
 - Steam Version : the last one

**Comment by alekskid33** [comment] 2022-03-19 20:39
it disaper

**Comment by faketucker** [comment] 2022-03-27 03:12
Duplicate of #538

**Closed by faketucker** 2022-03-27 03:12 UTC
Labels: bug, Not Tested
