### ISSUE TITLE
Water coming through my tent floor

### ISSUE THREAD

**Issue by MJR1972** [Uuvana-Studios/longvinter-windows-client#667] opened 2022-04-03 18:36 UTC
**Describe the bug**
I placed a tent near the water and when I go inside water is coming through on the floor

**To Reproduce**
1. Add a tent near the water
2. Go into your tent
3. See water coming through the floor

**Expected behavior**
water should not be coming through the floor graphic

**Screenshots**
Attached video
**Desktop (please complete the following information):**
 - OS: Win11
 - Game Version 1.0.2
 - Steam Version 1.0.5

**Additional context**

https://user-images.githubusercontent.com/29164981/161442944-8d9f387d-91e9-456b-a058-3ba8269e5cd9.mp4

**Comment by faketucker** [comment] 2022-04-03 22:57
That's not water, that's your tent floor glitching with the house wall

**Comment by faketucker** [comment] 2022-04-03 22:58
Duplicate of #625

**Closed by faketucker** 2022-04-03 22:58 UTC
Labels: Bug, Not Tested
