### ISSUE TITLE
Inventory Overflow (Berries) Bug

### ISSUE THREAD

**Issue by boabab** [Uuvana-Studios/longvinter-windows-client#441] opened 2022-03-16 18:49 UTC
**Describe the bug**
When (walking and) spam-clicking a berry-bush with a nearly full inventory, and you get more than 1 berry per bush, the extra items just overflow your inventory beyond the limit (see image below).
After closing the inventory menu, the bugged items are either gone or just not visible anymore, but as long as you keep the menu open, you can consume the berries/

(someone already kinda mentioned this bug, but with an unclear description) https://github.com/Uuvana-Studios/longvinter-windows-client/issues/393

**To Reproduce**
1. Have an almost full inventory
2. Go to a berry bush
3. Spam click it (while walking)
4. Open Inventory
5. See error

**Expected behavior**
Items shouldn't be picked up with full inventory.
Inventory full error is shown :)

**Screenshots**
![InventoryOverflow](https://user-images.githubusercontent.com/89863585/158664128-e332baf4-7fdc-49b4-b0dc-e854787bb803.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Game Version: Beta 1.0.1
 - Steam Version: ![image](https://user-images.githubusercontent.com/89863585/158664952-7a51be0f-c4a2-4018-b4b6-70a732ebe97c.png)

**Additional context**
For me this bug only happened when i was walking while spam clicking the bushes, but I'm not 100% sure about that.

**Comment by faketucker** [comment] 2022-03-26 15:01
Duplicate of #319

**Closed by faketucker** 2022-03-26 15:01 UTC
Labels: bug, Not Tested
