### ISSUE TITLE
Free of Charge Outpost Cost Money

### ISSUE THREAD

**Issue by BabyDriver2** [Uuvana-Studios/longvinter-windows-client#495] opened 2022-03-19 08:58 UTC
**Describe the bug**
When going to an island and returning to the sailboat, they charge you to go back to the island that you came from even though it says you can go back free of charge. 

**To Reproduce**
1. Go to any Outpost that isn't yours
2. Click on the tugboat to go back
3. Scroll down the list of outposts including the one you're from
4. Notice how they all cost MK and your original outpost is not free despite seeing the message at the very top of the tugboat menu clearly saying it is free of charge.

**Expected behavior**
I expected to return to my original outpost free of charge and instead couldn't return to the island due to insufficient mk funds. Lost all my backpack and inventory that I had acquired on that island.

**Desktop:**
 - OS: Windows 10
 - Game Version 1.0.1
 - Steam Version 1.0.1

**Additional context**
Please fix so this doesn't happen to anybody else. Really frustrating losing so much progress for a game that already requires you to be smart with your energy and MK savings

**Comment by faketucker** [comment] 2022-03-26 16:41
The free of charge/starter outpost is your spawnpoint outpost

**Comment by faketucker** [comment] 2022-03-26 16:41
Duplicate of #362

**Closed by faketucker** 2022-03-26 16:41 UTC
Labels: bug, Not Tested
