### ISSUE TITLE
Turret randomly disappeared when I clicked place.

### ISSUE THREAD

**Issue by GitKagan26** [Uuvana-Studios/longvinter-windows-client#539] opened 2022-03-21 16:42 UTC
I don't have a lot of time to make this so I'm just letting you know that when you click to place the turret it disappeared from me and I tried to relog in relogging and I tried to pick up in the area where it disappeared but nothing worked. I was sort of near a point of interest but it shouldnt steal your turret for being a little close to that. Thanks.

**Comment by faketucker** [comment] 2022-03-26 06:33
Bug reports that are not filled in correctly will not be taken into consideration since we need steps to replicate the bugs or we have no way to fix them. Next time, please use the appropriate template that we provided.

**Comment by faketucker** [comment] 2022-03-26 06:34
Duplicate of #492

**Closed by faketucker** 2022-03-26 06:34 UTC
Labels: bug, Not Tested
