### ISSUE TITLE
compendium not saved

### ISSUE THREAD

**Issue by bstickk** [Uuvana-Studios/longvinter-windows-client#671] opened 2022-04-03 21:08 UTC
**Describe the bug**
So I was doing my compendium last night for plants and after I got all 12 I left the game, the next day it reset back to what it was like before I did my compendium for that day 
**To Reproduce**
Not sure, maybe get compendiums and log out?

**Expected behavior**
Compendiums to save and me being able to wear my farm hat
**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: [e.g. Windows] Windows 11 
 - Game Version [e.g. 1.0] Beta 1.0.2
 - Steam Version [e.g. 1.0] Latest as of April 3rd, 2022

**Additional context**
N/A

**Comment by faketucker** [comment] 2022-04-04 03:30
Duplicate of #600

**Closed by faketucker** 2022-04-04 03:30 UTC
Labels: Bug, Not Tested

**Comment by faketucker** [comment] 2022-04-13 14:04
Duplicate of #745
