### ISSUE TITLE
character seems to reset when i logg out

### ISSUE THREAD

**Issue by NoName979** [Uuvana-Studios/longvinter-windows-client#247] opened 2022-03-07 09:21 UTC
when i log out and log back in my money is reset, my progress on finding different fish in the catalog thing is reset and all my items that i had on me dissapears.

**Comment by MaruLow** [comment] 2022-03-07 10:14
s

> when i log out and log back in my money is reset, my progress on finding different fish in the catalog thing is reset and all my items that i had on me dissapears.

This happen to me also yesterday. But admin close my report because doesn't follow format

**Comment by sirNugg3ts** [comment] 2022-03-07 16:55
Duplicate of #257

**Closed by sirNugg3ts** 2022-03-07 16:55 UTC
