### ISSUE TITLE
Wending machine glitch

### ISSUE THREAD

**Issue by Joviboi** [Uuvana-Studios/longvinter-windows-client#730] opened 2022-04-10 09:22 UTC
When accesing the wending machines it's sometimes impossible to exit the buy screen. I can still move around but the accessing screen to the wending machine will be displayed in the middle of my screen. The only way to get rid of it is exiting the session which means I lose all of my progress. 

Windows 10
LongVinter Beta 1.0.2

**To Reproduce**
1. Go to a wending machine at the market place
2. Click it
4. Exit the machine

![wendingmachineerror](https://user-images.githubusercontent.com/103358814/162611534-de74952c-eec2-4988-b7e3-e99bdc6c903b.jpg)

**Comment by faketucker** [comment] 2022-04-10 10:39
Duplicate of #410

**Closed by faketucker** 2022-04-10 10:39 UTC
Labels: Bug, Not Tested
