### ISSUE TITLE
I can't see the water (lake, sea).

### ISSUE THREAD

**Issue by SJ3004** [Uuvana-Studios/longvinter-windows-client#804] opened 2022-04-19 13:43 UTC
**Describe the bug**
I'm a game user who downloaded yesterday. People with different colors of water say blue, but I'm an ambiguous color. I can't even see the fish. I can't fish anything.
**To Reproduce**
4. See an error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Game Version [e.g. 1.0]
 - Steam Version [e.g. 1.0]

**Additional context**
![Longvinter Sea](https://user-images.githubusercontent.com/104010965/164017525-8bd4fe83-2d1a-41e4-917d-4207e1fe9f7c.png)
![Longvinter Sea](https://user-images.githubusercontent.com/104010965/164017375-48d21f21-a8c5-4edd-954c-c9ea3dc5dc53.png)

**Comment by sirNugg3ts** [comment] 2022-04-19 13:58
Duplicate of #13

**Closed by sirNugg3ts** 2022-04-19 13:58 UTC
Labels: Bug, Not Tested

**Comment by faketucker** [comment] 2022-04-19 16:18
Try to toggle DX11 water in the settings. If it doesn’t work, try what the issue # 13 said.

**Comment by SJ3004** [comment] 2022-04-19 17:07
Thank u-! I fixed it!
