### ISSUE TITLE
Ocean is white, i cant see fish

### ISSUE THREAD

**Issue by NaOH-H2** [Uuvana-Studios/longvinter-windows-client#767] opened 2022-04-15 19:35 UTC
**Describe the bug**

**To Reproduce**
4. See an error

**Expected behavior**
Water is white, i have to click to find fish. i cant see fish
**Screenshots**
![image](https://user-images.githubusercontent.com/101209612/163624169-d2d9fdec-3eed-4b82-ad08-e0a3f56781ad.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows] windows 11
 - Game Version [e.g. 1.0] 1.0.3
 - Steam Version [e.g. 1.0] dont know

**Additional context**

**Comment by sirNugg3ts** [comment] 2022-04-15 19:59
Duplicate of #346

**Closed by sirNugg3ts** 2022-04-15 19:59 UTC
Labels: Bug, Not Tested

**Comment by NaOH-H2** [comment] 2022-04-15 21:01
hmm
what should i do
i dont understand your comment
