### ISSUE TITLE
Vendor Screen Stuck/ Pix's Island

### ISSUE THREAD

**Issue by megane0724** [Uuvana-Studios/longvinter-windows-client#518] opened 2022-03-20 01:28 UTC
**Describe the bug**
When I arrived to the island I tried to select the vendor which didn't work at first, but after walking away the vendor screen appeared and I could not exit (pressing Esc only brought me to the main menu).

**To (Potentially) Reproduce**
1. Go to Pix Island
2. Click on Vendor twice
3. Walk off the dock and past the bonfire
4. Error occurs (vendor screen appears then doesn't go away)

**Expected behavior**
Clicking on the vendor should bring up the menu, and I should be allowed to exit the menu via walking away or pressing Tab

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Game Version: Unsure
 - Steam Version Unsure

**Comment by sirNugg3ts** [comment] 2022-03-22 09:26
Duplicate of #410

**Closed by sirNugg3ts** 2022-03-22 09:26 UTC
Labels: bug, Not Tested
