### ISSUE TITLE
Lost my house and inventory chopping wood

### ISSUE THREAD

**Issue by annaleejones02** [Uuvana-Studios/longvinter-windows-client#375] opened 2022-03-12 07:30 UTC
Was chopping wood for my fences when the game "bugged" I was taken back to where my "house" was but had no house My inventory had a tent and nothing else. Lost all progress after hours of playing.

To be able to chop wood and lot lose all contents of house and house itself.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 11}
 - Game Version [e.g. 1.0.0]
 - Steam Version [e.g. 1.0.0]

**Comment by Kanomee** [comment] 2022-03-12 09:30
Same to me while chopping

"The game refreshed while in-game and my house (built with wood) has been removed, a tent spawned in my inventory, placing the tent, the house was gone with every item I saved inside (chests, workbench, and some decorative items)"

**Comment by faketucker** [comment] 2022-03-26 11:54
Duplicate of #360

**Closed by faketucker** 2022-03-26 11:54 UTC
Labels: bug, Not Tested
