### ISSUE TITLE
Can't place Turret in own Base - Someone Else Bug

### ISSUE THREAD

**Issue by just5L3V1N** [Uuvana-Studios/longvinter-windows-client#73] opened 2022-02-28 08:51 UTC
**Describe the bug**
Unable to place a Turret in my Base, Says its someone elses property.

**Expected behavior**
Expected to build a Turret to protect my Lotus.

**Screenshots**
![image](https://user-images.githubusercontent.com/28486181/155983058-95fcaae4-400e-4cf6-96e9-de30e4d9fb23.png)

**Desktop (please complete the following information):**
 - OS: Win11
 - Game Version 1.0.0
 - Steam Version latest

**Additional context**
Its not the normal overlapping problem, that resolves itself after a while, trying since hours to place the turret

**Comment by Jalsson** [comment] 2022-02-28 13:55
Thanks for a great picture. I can see that this bug is caused by a nearby tent. Since we are changing that turrets can only be placed near your house that you have upgraded to wooden (so not tent) I remove the turret placing check all together. Will be fixed in the next update!

**Closed by Jalsson** 2022-02-28 13:55 UTC
Labels: bug, High Priority
