### ISSUE TITLE
Lag then Server Shutdown (multiple times) uuvanA (Singapore) And after, Missing placebles inside the cabin and outside

### ISSUE THREAD

**Issue by ComradeSmol** [Uuvana-Studios/longvinter-windows-client#537] opened 2022-03-21 13:18 UTC
**Describe the bug**
A large lag spike then everyone on the server dc, happenes quite frequent. 
Also missing placeables 
**Screenshots**

**Desktop (please complete the following information):**
 - OS: windows
 - Game Version: Longvinter Beta 1.0.1
 - Steam Version [e.g. 1.0]
![Screenshot (235)](https://user-images.githubusercontent.com/102037855/159268949-63930ec0-81bc-45ec-8be9-08864bdb9c1d.png)
![Screenshot (236)](https://user-images.githubusercontent.com/102037855/159268934-179f232d-6ee0-430f-a85b-f993bfbe519d.png)

**Additional context**
Sudden lag, everyone got kick then when I reconnected, some things are missing from my base, and in my cabin

**Comment by faketucker** [comment] 2022-03-27 06:10
Duplicate of #600

**Closed by faketucker** 2022-03-27 06:10 UTC
Labels: bug, Not Tested
