### ISSUE TITLE
Water is not being rendered in the game

### ISSUE THREAD

**Issue by sauravkakshapati** [Uuvana-Studios/longvinter-windows-client#286] opened 2022-03-08 03:53 UTC
**Describe the bug**
Water is not being rendered in the game at all. i see the fishes floating on the air but there's not water.

**To Reproduce**
1. Start the game
2. You will find yourself at the dock
3. No water body is being rendered , just fishes floating on air

**Expected behavior**
- I expect water body to be rendered in the game, where fishes are floatng

**Screenshots**
![image](https://user-images.githubusercontent.com/7276026/157162758-e5bcdd2d-8d7c-4afb-bb7c-d5f6fd94a8af.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Game Version : Beta 1.0.0
 - Steam Version : Steam API v020 built March 4 2022

**Additional context**
- Playing on a 34inch widescreen setup

**Comment by sirNugg3ts** [comment] 2022-03-08 04:09
Duplicate of #13

**Closed by sirNugg3ts** 2022-03-08 04:09 UTC
Labels: bug, Not Tested
