### ISSUE TITLE
Container Missing

### ISSUE THREAD

**Issue by trulu** [Uuvana-Studios/longvinter-windows-client#527] opened 2022-03-20 16:15 UTC
**Describe the bug**
after getting my house room upgrade to a bigger space, i relocate and decorate my room, then i log out and sleep for about 1-2 hour i login again and 4 of my container is missing. all my item were gone.

**To Reproduce**
Still dont know how to do this bug all i do was decorate my room with the hard work of fighting the container duplicate bug.

**Expected behavior**

** Screenshot
sorry no screenshot before and after this bugs.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Game Version latest
 - Steam Version latest

**Additional context**
missing item and container

**Comment by L0574u5513** [comment] 2022-03-20 16:57
Same thing has happened to me for the last few days. Every time i log off i hope ill log back in with the same items but its been containers, garden beds, a line of fences, yesterday it was my held inventory, today its 3 full containers.

**Comment by FinnUnreliable** [comment] 2022-03-20 21:37
The same thing just happened to me. Had two full containers of food, one of seeds, and another of parts. Logged in today and they are gone

**Comment by Serianni** [comment] 2022-03-21 20:23
Same thing has been happening to me. First time it was just 1 container.
Today it was like 3-4 stacks of containers.
![image](https://user-images.githubusercontent.com/7494814/159357446-18489a0d-b7fd-4ea0-b751-44500a0c8544.png)

**Comment by faketucker** [comment] 2022-03-26 02:03
Sometimes, after the server update or restart, the container will go to the same spot. Try to remove all the items from it and pick the container up. You might find the missing container.

**Comment by nikonyanya** [comment] 2022-03-26 12:27
Containers are still disappearing from my house and lost containers are still lost.

**Comment by faketucker** [comment] 2022-03-26 12:40
> Containers are still disappearing from my house and lost containers are still lost.

Thanks for the information. The devs are still working on it. Thank you for your understanding and patience.

**Comment by faketucker** [comment] 2022-03-28 11:34
Duplicate of #600

**Closed by faketucker** 2022-03-28 11:34 UTC
Labels: Bug, High Priority, Not Tested
