### ISSUE TITLE
I installed the turret, but it disappeared... Spin it

### ISSUE THREAD

**Issue by shinddochi** [Uuvana-Studios/longvinter-windows-client#842] opened 2022-05-01 00:36 UTC
**Describe the bug**
[
![ss](https://user-images.githubusercontent.com/104701858/166127193-0b1e17f5-c116-4f80-91c8-3e422beb32d8.png)
](url)
**To Reproduce**
4. See an error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Game Version [e.g. 1.0]
 - Steam Version [e.g. 1.0]

**Additional context**

**Comment by faketucker** [comment] 2022-05-01 04:11
Duplicate of #492

**Closed by faketucker** 2022-05-01 04:11 UTC
Labels: Bug, Not Tested
