### ISSUE TITLE
Inventory, money, research, crate cleared

### ISSUE THREAD

**Issue by shh1n** [Uuvana-Studios/longvinter-windows-client#235] opened 2022-03-06 17:34 UTC
When logging in, I don't start at my house but on the first island. My inventory is cleared and my money. A box is missing in my house. The problem has existed since today. My research like the plants are also reset to 0 each time. This happens with every login.

EU Server 3

**Comment by sirNugg3ts** [comment] 2022-03-06 17:38
Duplicate of #120

**Closed by sirNugg3ts** 2022-03-06 17:38 UTC
Labels: bug, Not Tested
