### ISSUE TITLE
Chest Bug

### ISSUE THREAD

**Issue by shckwve2g** [Uuvana-Studios/longvinter-windows-client#1011] opened 2022-07-05 11:10 UTC
The Server started to lag and after the crash all chest are gone.
EU WEST Server 2

**To Reproduce**
4. See an error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Game Version [e.g. 1.0]
 - Steam Version [e.g. 1.0]

**Additional context**

**Comment by faketucker** [comment] 2022-07-05 11:17
Duplicate of #1006

**Closed by faketucker** 2022-07-05 11:17 UTC
Labels: Bug, Not Tested
