### ISSUE TITLE
Cant close the store after opening it 

### ISSUE THREAD

**Issue by FroggyRibbit** [Uuvana-Studios/longvinter-windows-client#716] opened 2022-04-09 08:19 UTC
**Describe the bug**
After I open the little market in-game, I can't close the page. Every time I try to close it, I'm taken to the main menu. The only way I can get it to close is by restarting the game or just disconnecting and joining back.

**To Reproduce**
1. Go to the market/store stand
2. Click on it like you're gonna buy or sell something
3. exit out of the store 
4. see the page still up and send you to the main menu each time.

**Expected behavior**
I expected to be able to play the game as normal

**Screenshots**
![Screenshot (70)](https://user-images.githubusercontent.com/103307063/162563131-c176b7af-5f3b-4694-a367-94626a24da93.png)

![Screenshot (71)](https://user-images.githubusercontent.com/103307063/162563136-b7ba6bc3-1f9b-4324-9480-f16f52511abd.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Game Version Beta 1.0.2
 - Steam Version [e.g. 1.0]

**Additional context**

**Comment by faketucker** [comment] 2022-04-09 08:33
That happened because you double clicked the vendor

**Comment by faketucker** [comment] 2022-04-09 08:33
Duplicate of #410

**Closed by faketucker** 2022-04-09 08:33 UTC
Labels: Bug, Not Tested
