### ISSUE TITLE
Out of point of interest area in Tim's outpost turret

### ISSUE THREAD

**Issue by Anitesas** [Uuvana-Studios/longvinter-windows-client#805] opened 2022-04-19 14:42 UTC
**Describe the bug**
Tim's outpost area have a lot of turret but it can build house or other buiding. I concern someting like this is bug or intention of developer. When compare to Helmo & Rose, whole island that havs turret covered point of interest area that can't buiding or place something.

**Expected behavior**
I'm expect that area aroud turret in safezone can't buid or place buiding and turret in safezone must covered only safezone. Safezone must be only in dock.

**Screenshots**
![image](https://user-images.githubusercontent.com/104014222/164029633-7168109f-6ef8-43fa-9eb7-902269df7ffc.png)

**Desktop (please complete the following information):**
Steam; Longvinter Beta 1.0.3

**Additional context**
After newest update and has Julia's Mysterious Shop. The area around that become point of interest although before there was not.

**Comment by faketucker** [comment] 2022-05-17 04:30
Duplicate of #885

**Closed by faketucker** 2022-05-17 04:30 UTC
Labels: Bug, Low Priority, Tested
