### ISSUE TITLE
after the update i lost everything

### ISSUE THREAD

**Issue by DKAres901** [Uuvana-Studios/longvinter-windows-client#466] opened 2022-03-18 14:55 UTC
**Describe the bug**
i lost money item and house why? fix it please

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Game Version [e.g. 1.0]
 - Steam Version [e.g. 1.0]

**Additional context**

**Comment by Jalsson** [comment] 2022-03-18 14:58
Which server did you play on?

**Comment by fhillipgcastillo** [comment] 2022-03-19 04:28
I was on server: [US] uuvana 6 and I lost 2 or 3 containers, they just disappear from by house, which had the most important items there. This issue happened after the update

**Comment by faketucker** [comment] 2022-03-27 03:46
Duplicate of #600

**Closed by faketucker** 2022-03-27 03:46 UTC
Labels: bug, need more info, Not Tested
