### ISSUE TITLE
locked up in a warehouse

### ISSUE THREAD

**Issue by domesticrabbit** [Uuvana-Studios/longvinter-windows-client#290] opened 2022-03-08 10:05 UTC
**Describe the bug**

**To Reproduce**
![제목 없음](https://user-images.githubusercontent.com/101180133/157214467-43cb3e76-dce7-4e57-a802-43c5642bb6f6.jpg)

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Game Version [e.g. 1.0]
 - Steam Version [e.g. 1.0]

**Additional context**

**Comment by sirNugg3ts** [comment] 2022-03-08 13:38
Bug reports that are not filled correctly will not be taken in consideration, since we need steps to replicate the bugs or we have no way to fix them.
Please create a new bug report with the appropriate template.

Also Duplicate of #200

**Closed by sirNugg3ts** 2022-03-08 13:38 UTC
Labels: bug, Not Tested
