### ISSUE TITLE
The item has disappeared.

### ISSUE THREAD

**Issue by kimmmm0814** [Uuvana-Studios/longvinter-windows-client#1629] opened 2024-05-22 01:48 UTC
**버그 설명** 버그가 무엇인지 명확하고 간결하게 설명합니다.

Once the house had disappeared. So I bought a tent and filled it up with trees. Up until then, all the furniture and decorations I had installed were in the area. I accessed it the day before yesterday and it was a surprise. The house had stayed the same, but all the decorations outside had disappeared. Other than the flowers and boxes I planted, the turret, vending machines, couch, street lamps, pumpkin decorations, mailboxes, generators, smelters and tiles are all gone. I'm not part of the any team. No one knows the password for my house. Game rules don't allow me to take any zone items that are owned by someone other than my zone. But how is this possible?

**Comment by faketucker** [comment] 2024-09-07 11:41
Duplicate of #600

**Closed as completed by faketucker** 2024-09-07 11:41 UTC
Labels: Bug, Not Tested
