### ISSUE TITLE
Character is reset every time i log on

### ISSUE THREAD

**Issue by 22GoldEn** [Uuvana-Studios/longvinter-windows-client#255] opened 2022-03-07 13:17 UTC
**Describe the bug**

**The Bug happens every time i disconnect, all my progress and all my mk i reset every time i log back in to the server [EU] Uuvana 2. them game us unplayable as long as this i happening... **

**To Reproduce**
disconnect and log back in to the server

**Expected behavior**
fix this so your progress and mk i saved

**Screenshots**

no need

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Game Version [e.g. 1.0]
 - Steam Version [e.g. 1.0]

**Additional context**

**Comment by sirNugg3ts** [comment] 2022-03-07 16:55
Duplicate of #257

**Closed by sirNugg3ts** 2022-03-07 16:55 UTC
Labels: bug, Not Tested
