### ISSUE TITLE
The Shop UI not going off

### ISSUE THREAD

**Issue by HuskyBoizz** [Uuvana-Studios/longvinter-windows-client#718] opened 2022-04-09 11:44 UTC
The shop UI is not going off and when I interact the other shop or selling machine, the UI just overlap together. I try to right click not  doing anything. Left click bring me to ESC menu, and pressing ESC also not making it off my screen. This happen at Sgt. Lake Output , the shop that sell tent.
![image](https://user-images.githubusercontent.com/86936869/162572658-8fb8cd36-d3ac-427a-870a-2f43e84f5764.png)
![image](https://user-images.githubusercontent.com/86936869/162572671-c163a2a0-7dae-447d-ad03-859d4fe80a78.png)
The second image showing 2 overlapping shop UI

**Comment by faketucker** [comment] 2022-04-09 11:55
Duplicate of #410

**Closed by faketucker** 2022-04-09 11:55 UTC
Labels: Bug, Not Tested
