### ISSUE TITLE
2 house, can't dismantle

### ISSUE THREAD

**Issue by Reis9191** [Uuvana-Studios/longvinter-windows-client#513] opened 2022-03-19 21:14 UTC
**Describe the bug**
i have 1 house and 1 tent so i can't dismantle

**To Reproduce**
1. put 1 tent
2. put the 2nd tent
3. and when you want dismantle the first tent or the second you can't, the game say you have already 2 tent when you want to put the 3th tent for dismantle the first

**Expected behavior**
can dismantle the first or 2nd tent

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows] Windows 10
 - Game Version [e.g. 1.0] Beta 1.0.1
 - Steam Version [e.g. 1.0]

**Comment by faketucker** [comment] 2022-03-26 15:51
Duplicate of #505

**Closed by faketucker** 2022-03-26 15:51 UTC
Labels: bug, Not Tested
