### ISSUE TITLE
Tent appears as a house when first loading into a server

### ISSUE THREAD

**Issue by TriplePain** [Uuvana-Studios/longvinter-windows-client#705] opened 2022-04-07 17:11 UTC
as it says in the title, when logging into a server where I had built a tent the previous day it looked as if i had a house for a few seconds. At the same time it showed the outline of the tent, and there was Z fighting on the floor. After a few seconds of this the camera glitched out and it displayed me inside a tent as normal.

**Comment by faketucker** [comment] 2022-04-08 02:58
Duplicate of #625

**Closed by faketucker** 2022-04-08 02:58 UTC
