### ISSUE TITLE
Boxes "in use" even when no one else is around

### ISSUE THREAD

**Issue by zimmyzammy** [Uuvana-Studios/longvinter-windows-client#64] opened 2022-02-27 23:47 UTC
**Describe the bug**
Container says it's in use but no one else is there

**To Reproduce**
Unsure what caused this but there's 2 boxes on the server that cannot be opened because they are "in use"
The public box has been inaccessible since joining the server hours ago. Private box was working just before the "in use" issue. 

**Expected behavior**
To be able to open the box 

**Screenshots**
![image](https://user-images.githubusercontent.com/100537304/155905069-4cc08c00-c9a1-46f3-9333-0c616b3524cf.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows] windows 10
 - Game Version [e.g. 1.0] beta 1.0.0
 - Steam Version [e.g. 1.0] 1.0.0

**Additional context**
One of the boxes is outside where all players could have access to it and the other is inside of my home where only I could access it.

**Comment by zimmyzammy** [comment] 2022-02-28 15:17
Just found another inaccessible container, this one was a dropped players bag. More and more containers seem to be locking up.

**Comment by Sewall26** [comment] 2022-02-28 16:10
I have the same issue, what caused it was using the box and then dying or using a box and then being disconnected from the server.

**Comment by sirNugg3ts** [comment] 2022-03-01 19:00
I've tried a couple of times and couldn't reproduce this bug, please give a server and place where this happens to test, else I'll have to close this issue

**Comment by Hampusloov** [comment] 2022-03-05 09:02
@sirNugg3ts 

Im having exactly the same problem ATM, 


Server: [EU] Uuvana 2
Session id: 90156758307247114
Player ID: Hampusloov










![longvinter44](https://user-images.githubusercontent.com/100993808/156876294-a1b0cd60-335b-4489-a68e-d3321a324551.png)

**Comment by Jalsson** [comment] 2022-03-07 08:43
This was happening if the player exited the game while the container was open. This is now fixed in stable branch.

**Closed by Jalsson** 2022-03-07 08:43 UTC
Labels: bug, need more info, Not Tested
