### ISSUE TITLE
집에 있는 상자가 열리지 않습니다.

### ISSUE THREAD

**Issue by IMJUNGINE** [Uuvana-Studios/longvinter-windows-client#1126] opened 2022-07-31 11:19 UTC
**Describe the bug**
My box was locked up after my house was updated.
I can't clean it up or take it out.
It contains my precious things.
Please create a new box and move it.

**To Reproduce**
4. See an error

**Expected behavior**

**Screenshots**
![ㅠㅠ](https://user-images.githubusercontent.com/110334644/182023778-f7c73e2b-d72b-4e17-8c14-bb581cce6ee2.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Game Version [e.g. 1.0]
 - Steam Version [e.g. 1.0]

**Additional context**

**Comment by faketucker** [comment] 2022-08-02 06:29
Duplicate of #1099

**Closed by faketucker** 2022-08-02 06:29 UTC
Labels: Bug, Not Tested
