### ISSUE TITLE
Relog and Reset

### ISSUE THREAD

**Issue by Beamoo** [Uuvana-Studios/longvinter-windows-client#208] opened 2022-03-05 23:34 UTC
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Game Version [e.g. 1.0]
 - Steam Version [e.g. 1.0]

**Additional context**

**Comment by Beamoo** [comment] 2022-03-05 23:35
Two times now, I have relogged and lost all my progression, money, guns, etc

**Comment by PocketDragon108** [comment] 2022-03-06 08:57
Bumping to let you know your report is not filled out, the Devs cannot find the cause with little information please help assist with provideding more details. Where did you log off? Where did you spawn when your progress was wiped? What server were you on? Official non official this kinda stuff helps!

**Comment by sirNugg3ts** [comment] 2022-03-06 14:57
Duplicate of #211

**Closed by sirNugg3ts** 2022-03-06 14:57 UTC
Labels: bug, Not Tested
