### ISSUE TITLE
Missing containers

### ISSUE THREAD

**Issue by Serianni** [Uuvana-Studios/longvinter-windows-client#547] opened 2022-03-21 20:17 UTC
**Describe the bug**
It seems like almost daily now, when I log on, containers inside my house will be missing.
A couple days ago it was 1 container, and today I logged on and 3 stacks of containers are all gone.

**To Reproduce**
No way

**Expected behavior**
I expect my containers to not disappear inside my house

**Screenshots**
![image](https://user-images.githubusercontent.com/7494814/159356654-84c7b4be-f17d-4ad4-b01d-80c3a5db7764.png)

**Comment by ComradeSmol** [comment] 2022-03-22 04:26
Yep, I have experienced the same issues, some containers even disappeared outside of my house.

**Comment by Serianni** [comment] 2022-03-22 05:57
> Yep, I have experienced the same issues, some containers even disappeared outside of my house.

Well, any container outside of your house is not protected and can be destroyed by other players, so that isn't a bug. The only bug is containers inside going missing.

**Comment by ComradeSmol** [comment] 2022-03-22 06:09
> > Yep, I have experienced the same issues, some containers even disappeared outside of my house.
> 
> Well, any container outside of your house is not protected and can be destroyed by other players, so that isn't a bug. The only bug is containers inside going missing.

Sorry I forgot to mention, the outside of my base is protected with multiple auto turrets, so it’s definitely a bug.

**Comment by sirNugg3ts** [comment] 2022-03-22 09:23
Duplicate of #527

**Closed by sirNugg3ts** 2022-03-22 09:23 UTC
Labels: bug, Not Tested
