### ISSUE TITLE
I installed an attack turret, but it disappeared.

### ISSUE THREAD

**Issue by jongseop-ko** [Uuvana-Studios/longvinter-windows-client#657] opened 2022-04-02 12:53 UTC
**Describe the bug**

**To Reproduce**
4. See an error

**Expected behavior**

I installed an attack turret, but it disappeared.
I was looking for it, but I couldn't find it, and my power plant also considers the attack turret to be there.

Please refer to my YouTube video for more details.

Please refer to my YouTube and screenshots for more details.

https://www.youtube.com/watch?v=6GDEqNwEgt4&feature=youtu.be

**Screenshots**
![아직도 전기 가 안들어옴](https://user-images.githubusercontent.com/102860284/161382320-33bcfd16-d37e-40d0-a440-b476ac1412a9.png)
![전기여유있음](https://user-images.githubusercontent.com/102860284/161382323-ceab270a-fe93-4aba-b787-f3909959dd03.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Game Version1.0.2
 - Steam Version I do not know

**Additional context**

It's sad that the attack turret is gone, but it's even more heartbreaking to demolish the house as we can't use the normal amount of electricity.

my server :[KR] DAON 2- OFFICIAL
mr id : 90157723556348935

help me..

**Comment by faketucker** [comment] 2022-04-02 13:43
Duplicate of #492

**Closed by faketucker** 2022-04-02 13:43 UTC
Labels: Bug, Not Tested
