### ISSUE TITLE
Joining Servers 3/16 

### ISSUE THREAD

**Issue by J2HPHIRE** [Uuvana-Studios/longvinter-windows-client#447] opened 2022-03-17 01:15 UTC
**Describe the bug**

Trying to join servers at the moment but the servers are down. 
1. says joining server
2. starts to load in
3. goes back to home screen

**Comment by sirNugg3ts** [comment] 2022-03-17 12:15
Is this on an official server?

**Comment by sirNugg3ts** [comment] 2022-03-17 15:30
Duplicate of #452

**Closed by sirNugg3ts** 2022-03-17 15:30 UTC
Labels: bug, need more info, Not Tested
