### ISSUE TITLE
Some boxes for storing objects disappeared inside the house

### ISSUE THREAD

**Issue by Yukita7** [Uuvana-Studios/longvinter-windows-client#521] opened 2022-03-20 02:20 UTC
**Describe the bug**
When I returned to the game after expelled, the toolboxes were gone.

**To Reproduce**
1. press space to enter the house
2. When I was inside, the 6 boxes I had were gone.
There are two left and one of them in the air.

**Expected behavior**
my expectation was to see the complete boxes

**Screenshots**
![image](https://user-images.githubusercontent.com/101904625/159144876-cd68f8a4-a85f-46de-9852-520bff4c84d8.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 
 - Game Version 1.0.1
 - Steam Version api steam v020 

**Additional context**
I hope you can fix it soon, please and thank you
![longvinter bug](https://user-images.githubusercontent.com/101904625/159145120-20919066-db20-4a13-9c13-26e941d8092f.png)

**Comment by hoak** [comment] 2022-03-20 03:28
This is easy to reproduce. Place a container, and destroy it. You will notice that the container has a bag inside it which you cannot pick up but the container is still there. This container will still allow you to put items in it but it will eventually disappear, and you will lose everythjing in it. Until this bug is fixed the workaround is to not destroy any containers. If you do accidentally, do not put anything in them for at least an hour.

**Comment by Yukita7** [comment] 2022-03-20 04:43
Thank you for you response

Oooh ok. I've never done the container destruction thing...Anyway I could
not destroy the containers because they do not appear to me, they are
invisible, so I will not move anything from the containers for now.

**Comment by DKAres901** [comment] 2022-03-20 11:43
I LOST ITEM TOO

**Comment by fhillipgcastillo** [comment] 2022-03-21 02:31
Same have happened to me 2 or 3 times, so the last 2 days, everytime I came back to the game, I've lost 2 or 3 boxes from my home, with all the items inside (with have all the most important thing on them) and that fustrating because we spend hourse to get certain things and them they just disappear.
btw the boxes that use to disappear are the one that are on the top (I stack them vertically 2 by 2), have 2 column and last night 2 boxes are gone

I'm on server [US] uuvana 6

**Comment by faketucker** [comment] 2022-03-26 06:39
Duplicate of #527

**Closed by faketucker** 2022-03-26 06:39 UTC
Labels: bug, Not Tested
