### ISSUE TITLE
Containers with items disappeared from my home

### ISSUE THREAD

**Issue by Leesa2594** [Uuvana-Studios/longvinter-windows-client#507] opened 2022-03-19 17:07 UTC
My home is on Usuvanna 5 Server.  My house is near the lake and my house name is Leesa.  Three containers in my home have disappeared.  It had lots of stuff  in them.  ONe of the previous ones that disappeared came back, but the other three there were on top of each other next to my workbench are gone.

All you have to do is go into my home to see that they are gone.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Game Version [e.g. 1.0]
 - Steam Version [e.g. 1.0]

**Additional context**

**Comment by Leesa2594** [comment] 2022-03-19 17:32
It is server us uuvana 5, and now one more has disappeared.  I only have one left in my house.  So frustrating.

**Comment by Leesa2594** [comment] 2022-03-19 17:46
I also noticed the garden fire we had in between my house and dred's house has disappeared as well.

**Comment by Leesa2594** [comment] 2022-03-19 23:54
We think we know what is going on with the not being able to move the containers.  When you right click it when it is empty, you see the top of the bag behind the container.  But, can't pick it up.  The container still is there.  Once you place a container, you cannot move it because of this situation.  Then, those containers just disappear which I think is because they are in bags and not the containers anymore.  But  you can go back and open the containers and put stuff in them

This doesn't explain that some containers just disappear with all the stuff in it.

**Comment by faketucker** [comment] 2022-03-26 07:53
> I also noticed the garden fire we had in between my house and dred's house has disappeared as well.
Someone might destroy it by shooting over the fences.

> We think we know what is going on with the not being able to move the containers. When you right click it when it is empty, you see the top of the bag behind the container. But, can't pick it up. The container still is there. Once you place a container, you cannot move it because of this situation. Then, those containers just disappear which I think is because they are in bags and not the containers anymore. But you can go back and open the containers and put stuff in them

This occurred because two containers were placed in the same spot and should be fixed by the latest update; you can no longer place two items in the same spot anymore. You should be able to pick it up after the server restarts.

> Containers with items disappeared from my home
Duplicate of #527

**Closed by faketucker** 2022-03-26 07:53 UTC
Labels: bug, Not Tested
