### ISSUE TITLE
James General Store

### ISSUE THREAD

**Issue by BananaMan001** [Uuvana-Studios/longvinter-windows-client#647] opened 2022-04-01 19:17 UTC
**Describe the bug**
After selling everything from your inventory When tying to close James General Store you are sent to the screen youd be sent to when pressing "esc"

**To Reproduce**
1. Go to 'James general store'
2. Click on 'the x'

**Expected behavior**
I expected to go back to the game and continue playing

**Desktop (please complete the following information):**
 - OS: Windows
 - Game Version 1.0.2
 - Steam Version 2.10.91.91

**Comment by BananaMan001** [comment] 2022-04-01 19:21
When trying to do it again once relogging it seemed to have fixed itself

**Comment by faketucker** [comment] 2022-04-02 03:10
This happened because you double clicked the vendor, so it stuck because there were two windows popping up. I believe if the double click at the vendor bug is fixed, you won't face this problem again.

**Comment by faketucker** [comment] 2022-04-02 03:11
Duplicate of #410

**Closed by faketucker** 2022-04-02 03:11 UTC
Labels: Bug, Not Tested
