### ISSUE TITLE
"Rug: Grey Persian" is invisble inside your house

### ISSUE THREAD

**Issue by MrJuli449** [Uuvana-Studios/longvinter-windows-client#900] opened 2022-05-25 20:09 UTC
https://user-images.githubusercontent.com/106277672/170357922-d44dd574-bb57-4137-ae5b-51c1bb2ca305.mp4

**Describe the bug**
If you place the "Rug: Grey Persian" inside your house it is invisble. Also you can´t see where the Rug will be placed.

**To Reproduce**
Try to place a "Rug: Grey Persian" inside your house.

**Expected behavior**
To see the carpet/see where it will be placed.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Game Version 1.0.6
 - Steam Version up to date

**Comment by faketucker** [comment] 2022-05-26 04:25
Duplicate of #522

**Closed** 2022-05-26 07:43 UTC
Labels: Bug, Not Tested
