### ISSUE TITLE
Tent items inaccesbile.

### ISSUE THREAD

**Issue by Chasedoesstuff** [Uuvana-Studios/longvinter-windows-client#605] opened 2022-03-28 02:43 UTC
My tent items were down left from the top. The items were placed from before the decay update. The tent is new. I have to respectfully say that I don't know how to replicate this.

 - OS: windows
 - Game Version 1.0.2
 - Steam Version v020
![Longvinter   3_27_2022 10_16_19 PM](https://user-images.githubusercontent.com/101988897/160317528-0acc6280-8aa4-4255-b117-c29d56416acb.png)

**Comment by faketucker** [comment] 2022-03-28 02:45
Duplicate of #354

**Comment by Chasedoesstuff** [comment] 2022-03-28 19:22
Hello, I hope this email finds you well. I believe this issue is not closed. My items are inaccessible because my items are inside the void. The issue you said my report was a copy of had the items still inaccessible in their house. I was able to interact with the workbench and the right container in my screenshot. I am sorry for the inconvenience.

**Comment by Chasedoesstuff** [comment] 2022-03-28 19:28
I’m sorry for my last email. I’d like to reiterate and say that the issue was similar. My issue has still not been resolved.
-best regards, Chase

**Comment by faketucker** [comment] 2022-03-28 23:03
> Hello, I hope this email finds you well. I believe this issue is not closed. My items are inaccessible because my items are inside the void. The issue you said my report was a copy of had the items still inaccessible in their house. I was able to interact with the workbench and the right container in my screenshot. I am sorry for the inconvenience.

The main purpose of bug fixes is to prevent the bugs from happening again. The items that got stuck in the void from tent decay before the update shouldn't be able to get back since tent decay is supposed to remove everything in the tents. I'll reopen this again. Thanks for the information.

**Comment by faketucker** [comment] 2022-03-29 00:35
Or you should place a new workbench in and try to dismantle your tent and place it again more down left.

**Closed** 2022-03-31 04:36 UTC
Labels: Bug, High Priority

**Comment by Chasedoesstuff** [comment] 2022-10-11 07:07
Hello, I hope this email finds you well. I believe this issue is not closed. My items are inaccessible because my items are inside the void. The issue you said my report was a copy of had the items still inaccessible in their house. I was able to interact with the workbench and the right container in my screenshot. I am sorry for the inconvenience.
