### ISSUE TITLE
Memory leaks

### ISSUE THREAD

**Issue by camarena4** [Uuvana-Studios/longvinter-windows-client#1036] opened 2022-07-08 12:04 UTC
every so often my game crashes and uses 99% of the RAM 💀  Played on [EU-WEST] Uuvana 1
![Captura de pantalla 2022-07-08 010732](https://user-images.githubusercontent.com/108935541/177988706-7c1635de-2df5-4d19-8ba2-2771c68d6fb0.png)

**Comment by faketucker** [comment] 2022-07-09 13:51
There have been reports of memory leaks, devs are working on this issue

**Comment by Jalsson** [comment] 2022-11-10 13:27
This issue was caused by creating too many UI elements. Fixed by creating them only when needed

**Closed by Jalsson** 2022-11-10 13:27 UTC
Labels: Bug, High Priority
