### ISSUE TITLE
tent and Workbench duplication glitch on Isla Inocentes

### ISSUE THREAD

**Issue by chamsco** [Uuvana-Studios/longvinter-windows-client#496] opened 2022-03-19 09:21 UTC
i posed  a tent and when i tried  to dismantle it, with some woods  on the bench (28 to be exact) , the tent stayed there with the work bench but i had them in my inventory

**Comment by Sammieyy** [comment] 2022-03-19 15:36
Same thing happened here

**Comment by faketucker** [comment] 2022-03-26 15:51
Duplicate of #505

**Closed by faketucker** 2022-03-26 15:51 UTC
