### ISSUE TITLE
Plant compendium vendor menu stuck open.

### ISSUE THREAD

**Issue by mcsolar466** [Uuvana-Studios/longvinter-windows-client#756] opened 2022-04-14 19:33 UTC
**Describe the bug**
Plant compendium vendor doesnt have an x button in the corner. I guess you usually tab out or something. But it wouldnt close no matter how far I walked from it. In the screen shot you can see that I am at the dock and the buy menu is still open and wont close.

**To Reproduce**
don't know how
**Expected behavior**
i expected to be able to close the buy menu

**Screenshots**

![glitch1](https://user-images.githubusercontent.com/58825665/163462890-11dfb95c-bf18-46f5-bd62-830759b2cdbf.png)

**Desktop (please complete the following information):**
windows 10 
beta 1.0.2

**Additional context**
none :/ sorry. Just want to help

**Comment by faketucker** [comment] 2022-04-15 05:17
Duplicate of #410

**Closed by faketucker** 2022-04-15 05:17 UTC
Labels: Bug, Not Tested
