### ISSUE TITLE
Water Looks Like a Landmass

### ISSUE THREAD

**Issue by DawnieDragon** [Uuvana-Studios/longvinter-windows-client#180] opened 2022-03-04 03:48 UTC
**Describe the bug**
My water looks like a Landmass and if it wasn't for the fishes and stuff swimming, i wouldn't be able to tell its water

**To Reproduce**
This is something i do not know the steps to reproduce. it just happened randomly and i don't know how to fix it. I know i was tweaking settings to fit my computer.
**Expected behavior**
I was expecting my world to contain water

**Screenshots**

![20220303192627_1](https://user-images.githubusercontent.com/100893633/156695685-514b36ac-fb6a-4926-b8b2-1b853969fbc1.jpg)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Game Version Unknown
 - Steam Version Unknown

**Additional context**

**Comment by sirNugg3ts** [comment] 2022-03-04 11:44
Duplicate of #13

**Closed by sirNugg3ts** 2022-03-04 11:44 UTC
Labels: bug, Not Tested
