### ISSUE TITLE
I cant upgrade second floor 

### ISSUE THREAD

**Issue by ppastelito** [Uuvana-Studios/longvinter-windows-client#1140] opened 2022-08-04 04:15 UTC
![lv](https://user-images.githubusercontent.com/109627277/182761551-8c25af4b-b8cc-4d60-9c49-9a7ec17e8fae.png)
![lv2](https://user-images.githubusercontent.com/109627277/182761559-71d2e4bb-a603-4c9d-af9c-2e6262403da0.png)
![lv3](https://user-images.githubusercontent.com/109627277/182761564-8a20a7f7-76d6-446e-81c7-f0dadf047560.png)
  
I can't upgrade my house because it says I don't have space outside

Windows 10 
Game version 1.0.8b

**Comment by faketucker** [comment] 2022-08-04 05:51
Duplicate of #1131

**Closed by faketucker** 2022-08-04 05:51 UTC
Labels: Bug, Not Tested
