### ISSUE TITLE
Overlapping Houses

### ISSUE THREAD

**Issue by FrostShai** [Uuvana-Studios/longvinter-windows-client#203] opened 2022-03-05 21:18 UTC
**Describe the bug**
When I was building my base, I place 2 tents side by side. When I went inside one of the tents, the second tent overlaps the corner of the first tent. That corner is completely unusable as it wont let me walk into the corner because I run into the wall in both homes. 

**To Reproduce**
1. Get 2 tents
2. Place both tents side by side facing the same way
3. Walk inside the tent

**Expected behavior**
I want the tents to be fixed and they each are in their own place.

**Screenshots**
![image](https://user-images.githubusercontent.com/101021904/156900186-f842a549-6fb1-4fd5-9763-b7a0186c0c89.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Game Version 1.0.0
 - Steam Version 1.0.0

**Additional context**
I dont know if others are having this issue, but this is really annoying as I just wanted another space within my base for a chest room.

**Comment by sirNugg3ts** [comment] 2022-03-06 15:08
Duplicate of #220

**Closed by sirNugg3ts** 2022-03-06 15:08 UTC
Labels: bug, Not Tested
