### ISSUE TITLE
Home disappears when server reboots

### ISSUE THREAD

**Issue by wdefsdfwfd** [Uuvana-Studios/longvinter-windows-client#1156] opened 2022-08-09 13:39 UTC
Home disappears when server reboots
![캡처](https://user-images.githubusercontent.com/110180749/183659257-b78a7565-148a-4de0-8cf9-0a89ef331594.JPG)

**Comment by faketucker** [comment] 2022-08-11 13:42
Duplicate of #600

**Closed by faketucker** 2022-08-11 13:42 UTC
Labels: Bug, Not Tested
