### ISSUE TITLE
US7 character reset after server was down

### ISSUE THREAD

**Issue by kylyco** [Uuvana-Studios/longvinter-windows-client#261] opened 2022-03-07 17:28 UTC
**Describe the bug**
After the server was down all day yesterday i logged onto US 7. I loaded into the black area of the tent realm in an location not even close to one of my tents. I walked into someone else's tent to exit into the normal world and noticed my character was completely reset. No  books complete, 100mk instead of the thousands i had before, no inventory, etc. 

**To Reproduce**
Log into US7 server after it was down?

**Expected behavior**
I was hoping to be in my house and have my compendium still filled and belongings in my inventory. At bare minimum would have been nice not to lose my compendium completion. 

**Desktop (please complete the following information):**
 - OS: Windows 10 21H1
 - Game Version whichever one came out today
 - Steam Version unsure but the most recent version

**Additional context**
I also went to pick up my turret and it disappeared which im guessing is either to do with the new turret update or is because my compendium wasnt complete. not sure which.

**Comment by sirNugg3ts** [comment] 2022-03-07 17:30
Duplicate of #120

Between updates stuff might get wiped, we have warned about this countless time and addressed it on yesterday's Q&A

**Closed by sirNugg3ts** 2022-03-07 17:30 UTC
Labels: bug, Not Tested
