### ISSUE TITLE
Tiles & turrets despawned

### ISSUE THREAD

**Issue by worthij92** [Uuvana-Studios/longvinter-windows-client#1227] opened 2022-09-19 23:08 UTC
**Describe the bug**
After the update I noticed my tiles and turrets have despawned. It will not allow me to place tiles where I had once placed them, and won't allow me to pick them up so for the tiles its as if they disappeared but are still invisible and won't let me replace them. 

**To Reproduce**
4. See an error

**Expected behavior**
Tiles to be there and turrets to not despawn =)

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Game Version [1.0.9]
 - Steam Version [up to date]

**Additional context**

**Comment by criticalthot** [comment] 2022-09-19 23:14
Same thing happened to me in EU WEST pve server. all tiles gone except for 3 which seem to be covered by the ground (picture attached). I CAN remove the tiles that are partly visible but only those few. 


![tileshit](https://user-images.githubusercontent.com/113949807/191135028-fc01c7bb-c93a-4ae6-9534-020ee974bddb.png)

**Comment by faketucker** [comment] 2024-09-03 11:21
Duplicate of #600

**Closed by faketucker** 2024-09-03 11:21 UTC
Labels: Bug, Not Tested
