### ISSUE TITLE
The store can't close because of bugs.

### ISSUE THREAD

**Issue by dohansol** [Uuvana-Studios/longvinter-windows-client#660] opened 2022-04-02 20:42 UTC
**Describe the bug**
The store can't close because of bugs.

**To Reproduce**
1. Go to 'move to a store'
2. Click on 'click on the main store'
4. The store can't close because of bugs.

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/101974473/161400223-4c21105d-c465-4107-8adf-2fd74e77afef.png)

**Desktop (please complete the following information):**
 - Steam Version [1.0.2]

**Additional context**
I'm waiting for you to solve it. I can't close click on many stores. This is a bug that you have to fix. You can fix it. store is everything open  ,continuously

**Comment by faketucker** [comment] 2022-04-03 01:12
The only way now is to close and reopen the game

**Comment by faketucker** [comment] 2022-04-03 01:12
Duplicate of #410

**Closed by faketucker** 2022-04-03 01:12 UTC
Labels: Bug, Not Tested
