### ISSUE TITLE
rollback

### ISSUE THREAD

**Issue by abovexe** [Uuvana-Studios/longvinter-windows-client#1158] opened 2022-08-09 14:23 UTC
**Describe the bug**
hi I was rollbacked after logging out one day, lost my money, quests and items. Sorry my english is not perfect but if someone know what happened to me, thanks to help me :)

**Desktop (please complete the following information):**
 - windows 10

**Comment by BonesIsLive** [comment] 2022-08-11 07:30
Make sure you haven't changed your Steam account or your Steam name.

**Comment by faketucker** [comment] 2022-09-18 12:55
Duplicate of #600

**Closed by faketucker** 2022-09-18 12:55 UTC
Labels: Bug, Not Tested
