### ISSUE TITLE
My containers disappear

### ISSUE THREAD

**Issue by beamarag** [Uuvana-Studios/longvinter-windows-client#1632] opened 2024-06-01 04:27 UTC
My containers disappear as well as my items in there, I put it in my tent, and it duplicates my tent I don't have my items and the items that I put were from the starting point axe, pickaxe, guidebook, fishing rod and my achievements disappear.

**Comment by faketucker** [comment] 2024-09-03 11:39
Duplicate of #600

**Closed as completed by faketucker** 2024-09-03 11:39 UTC
Labels: Bug, Not Tested
