### ISSUE TITLE
Can't access certain containers after upgrading from tent to house

### ISSUE THREAD

**Issue by Serianni** [Uuvana-Studios/longvinter-windows-client#608] opened 2022-03-28 07:14 UTC
**Describe the bug**
If you stack containers 3 high in a tent and then upgrade to a house, you won't be able to access the top containers anymore.

**To Reproduce**
1. Build tent
2. stack containers 3 high
3. upgrade tent to a house
4. cannot access top container of 3 high stack

**Expected behavior**
You should be able to access you containers

**Screenshots**
![image](https://user-images.githubusercontent.com/7494814/160344750-f19ef00a-c6c1-47f3-b0a5-111d08e88c78.png)

**Desktop (please complete the following information):**
 - Windows 10 Pro
 - Beta 1.0.2
 - Not sure where to find the steam version number

**Comment by faketucker** [comment] 2022-03-28 08:03
Duplicate of #354

**Closed by faketucker** 2022-03-28 08:03 UTC
Labels: Bug, Not Tested
