### ISSUE TITLE
Turrets not reliably shooting 

### ISSUE THREAD

**Issue by JiHounHuh** [Uuvana-Studios/longvinter-windows-client#428] opened 2022-03-15 17:37 UTC
**Describe the bug**
Turrets don't see to be hitting or registering hits onto players (even at close range) There is the occasional sweetspot where it does hit but other than that, it doesn't seem to work. 

**To Reproduce**
1. Go to turret
2. Watch it shoot
3. You can walk around and discover there there is a certain distance where it hits but other than that, nothing.
4. Enjoy a light show

**Expected behavior**
Turret should be hitting when shooting at least 80% of the shots, right?

**Screenshots**

https://user-images.githubusercontent.com/25492217/158437862-4ffb3740-4e77-4703-a12a-8b30f162132f.mp4

https://user-images.githubusercontent.com/25492217/158437911-d844309b-0fe8-4022-9c3a-2b0463875f3c.mp4

**Desktop (please complete the following information):**
 - OS: Windows 10 (hosted on LogicServers)
 - Game Version 1.0.1
 - Steam Version 1.0.1

**Additional context**
Not sure if it's because I'm an admin on the server or not...

**Comment by faketucker** [comment] 2022-03-26 14:49
Duplicate of #377

**Closed by faketucker** 2022-03-26 14:49 UTC
Labels: bug, Not Tested
