### ISSUE TITLE
My house is GONE including the fences.

### ISSUE THREAD

**Issue by MrsMinzi** [Uuvana-Studios/longvinter-windows-client#1190] opened 2022-08-25 16:51 UTC
After the new update my house disappeared. My neighbor decided to build a house there after, because they thought I moved out. I mean they could be lying and guess the code but the location of my house was slightly different! My house definitely didn't decay. This all happened at night, after the downtime. My neighbor gave me his code and I entered, all my stuff was showing behind his. He removed his house, and I placed a tent. Couldn't do the same location I had previously. Now I can't even enter my tent without jumping on a bench. Can I get my old house and items back!? Why did my house disappear? 

https://user-images.githubusercontent.com/111882439/186724175-476f155b-8da5-4010-9c7c-c4eca1363779.MOV

![image](https://user-images.githubusercontent.com/111882439/186724194-54ba2e45-bead-4253-a4b8-7b63ccb8fecc.jpeg)

![image](https://user-images.githubusercontent.com/111882439/186724219-9ef439a7-5541-42e7-a823-ea92dcc2772a.jpeg)

![image](https://user-images.githubusercontent.com/111882439/186724250-afeb0fcb-b81c-418b-8213-851b39007de9.jpeg)

![image](https://user-images.githubusercontent.com/111882439/186724268-e6a34326-43f1-4018-8e73-2e5c0c20a416.jpeg)

![image](https://user-images.githubusercontent.com/111882439/186732461-87605723-45b3-4fca-b35f-cccd44e3e269.jpeg)

![image](https://user-images.githubusercontent.com/111882439/186724287-22247f8b-9e1f-46d2-ba94-45e2a1a3cbf2.jpeg) no

Game Version [e.g. 1.0.8.b

**Comment by faketucker** [comment] 2022-08-28 09:41
houses or progress can be lost due to the server crashes or restarts, and there's nothing we can do to bring them back.

**Comment by faketucker** [comment] 2022-08-28 09:41
Duplicate of #600

**Closed by faketucker** 2022-08-28 09:41 UTC
Labels: Bug, Not Tested
