### ISSUE TITLE
Double click on vending machines, interface bug

### ISSUE THREAD

**Issue by Queso924** [Uuvana-Studios/longvinter-windows-client#697] opened 2022-04-06 19:13 UTC
**Describe the bug**
If you make several clicks on the vending machines, the menu opens 2 times and then does not close

**To Reproduce**
1. Go to one vending machine
2. Several clicks on the vending machine
3. Click ESC one time
4. You can move with the menu in the screen

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Game Version: beta 1.0.2]
 - Steam Version: I don't know

**Additional context**
it is solved when leaving and re-entering the server, I think it is a lag problem

**Comment by faketucker** [comment] 2022-04-06 22:44
Duplicate of #410

**Closed by faketucker** 2022-04-06 22:44 UTC
Labels: Bug, Not Tested
