### ISSUE TITLE
James General Store screen, "x" leads to Home screen and won't close store screen

### ISSUE THREAD

**Issue by CYNCHO** [Uuvana-Studios/longvinter-windows-client#672] opened 2022-04-04 01:04 UTC
**Describe the bug**

**To Reproduce**
1. Go to Jame's General Store
2. Click on Vending Machine buy/sell and click "x" to exit 
4. See an error

**Expected behavior**
Clicking on red X should close General Store screen 

**Screenshots**
![image](https://user-images.githubusercontent.com/102932737/161457857-7a5f0b10-0610-45c7-91af-166f0b72278b.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Game Version [e.g. 1.0]
 - Steam Version [e.g. 1.0]

**Additional context**
The general store screen won't close and you have to leave the game, it doesn't happen every time, but it has happened 3 times during an hour of game play.  When clicking the x it goes to the "esc" screen

**Comment by faketucker** [comment] 2022-04-04 01:22
This happened because you double clicked the vendor, so it stuck because there were two windows popping up. I believe if the double click at the vendor bug is fixed, you won't face this problem again.

**Comment by faketucker** [comment] 2022-04-04 01:22
Duplicate of #410

**Closed by faketucker** 2022-04-04 01:22 UTC
Labels: Bug, Not Tested
