### ISSUE TITLE
AutoDefender randomly went up into the sky when placed near fence

### ISSUE THREAD

**Issue by DandelionBill** [Uuvana-Studios/longvinter-windows-client#753] opened 2022-04-13 22:21 UTC
**Describe the bug**
when i went to place my autodefender next to my fence I thought it disappeared but then i noticed its shadow and its hovering high above my garden and i cant click on it to get it down to put it somewhere else

this is in the west desert biome

**Comment by faketucker** [comment] 2022-04-14 01:59
Duplicate of #492

**Closed by faketucker** 2022-04-14 01:59 UTC
Labels: Bug, Not Tested
