### ISSUE TITLE
Shop Can't Be Closed

### ISSUE THREAD

**Issue by Brewer5700x** [Uuvana-Studios/longvinter-windows-client#367] opened 2022-03-12 02:24 UTC
**Describe the bug**
A's Farming shop can't be closed

**To Reproduce**
1. Go to 'A's Farming Shop'
2. Click on the shop twice in quick succession

**Expected behavior**
The shop can't be closed even if you walk away.

**Screenshots**
![image](https://user-images.githubusercontent.com/88564659/158000137-8c61da3d-337d-46df-809f-55c26880a212.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Game Version 1.0.0
 - Steam Version 020

**Comment by lejcart** [comment] 2022-03-13 04:43
![image](https://user-images.githubusercontent.com/101491036/158045383-829865e2-2547-4278-b9c0-f9ce533225ca.png)

Having the same issue. Haven't found any fix aside from leaving and going back in.

**Comment by faketucker** [comment] 2022-03-25 12:13
Duplicate of #410

**Closed** 2022-03-25 12:14 UTC
Labels: bug, Not Tested
