### ISSUE TITLE
House missing after update. Interior of missing home visible from another house's interior.

### ISSUE THREAD

**Issue by miwlky** [Uuvana-Studios/longvinter-windows-client#1015] opened 2022-07-05 11:47 UTC
**Describe the bug**
House missing after update. Interior of the house that is missing is still visible while inside the interior of my second house in the top left corner.
US-West 1

**To Reproduce**
Before the update: Located inside missing house. 
After the update: Located at Sgt. Lake's Outpost
Took the boat to Artur's Outpost to walk towards home and house was missing. 

**Expected behavior**
For the house to be there. 

**Screenshots**
Missing house's interior visible in top left of another home:
![image](https://user-images.githubusercontent.com/108734380/177319679-7c065818-d0f5-465a-a217-3d268e96adf3.png)
Where the house should be located: 
![image](https://user-images.githubusercontent.com/108734380/177321252-77b4b0a8-be79-4798-9d68-735a40d021d8.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Home
 - Game Version [e.g. 1.0] - 1.0.8
 - Steam Version [e.g. 1.0] - 
![image](https://user-images.githubusercontent.com/108734380/177320276-c08e4b69-13cb-4b2d-b41d-d9317b0de4a9.png)

**Additional context**
Missing house color was yellow.

**Comment by miwlky** [comment] 2022-07-05 11:56
It gets buggier. I placed a new tent in the area where the missing house is and I now have access to all my stuff again, although slightly off-centered (probably due to not being in the exact spot). 
![image](https://user-images.githubusercontent.com/108734380/177321913-34135d8f-7b09-4477-bf1f-db259623fc3e.png)

**Comment by faketucker** [comment] 2022-07-05 16:07
Duplicate of #600

**Closed by faketucker** 2022-07-05 16:07 UTC
Labels: Bug, Not Tested
