### ISSUE TITLE
Duplication Glitch - Equipment

### ISSUE THREAD

**Issue by Cyndergate** [Uuvana-Studios/longvinter-windows-client#1025] opened 2022-07-06 18:56 UTC
Issue: 
Equipment duplicates if you drop all items during high ping/high turret fire amounts.

Replication:
- High Turret Fire [Atleast 2 Turrets]
- Drop All Items
- Pick Items Back Up
- You can use your equipment, equipment tab is empty, all equipment is in inventory like normal

Possible Causes:
High Ping?

**Comment by Cyndergate** [comment] 2022-07-06 19:02
This glitch causes your entire inventory to wipe after you relog, apparently.

I relogged in, entire inventory.. empty. I didn't die. I was right where I was.

**Comment by faketucker** [comment] 2022-07-11 06:02
Duplicate of #961

**Closed by faketucker** 2022-07-11 06:02 UTC
