### ISSUE TITLE
The achievement for 100 kills is granted on Steam on the first kill

### ISSUE THREAD

**Issue by cambeius** [Uuvana-Studios/longvinter-windows-client#814] opened 2022-04-21 20:08 UTC
**Describe the bug**
When killing your first player, steam grants the "Mixed feelings" and the "I wish there was more PVE" achievement, while the second one should be achieved by killing 100 players.

**To Reproduce**
1. Get a shotgun
2. Kill a player in a PvP zone
3. Steam will award the two achievements mentioned above

**Expected behavior**
Only the "Mixed feelings" achievement should be awarded on a first kill.

**Screenshots**
![image](https://user-images.githubusercontent.com/54690836/164542562-43008607-871f-4fc7-a879-2c9460c662b5.png)

**Desktop:**
 - OS: Windows 11 21H2
 - Game Version: 4.26.0.0
 - Steam Version: 7.20.35.49

**Additional context**
I was playing on EU Uuvana 3

**Comment by faketucker** [comment] 2022-04-22 10:49
Duplicate of #421

**Closed by faketucker** 2022-04-22 10:49 UTC
Labels: Bug, Not Tested
