### ISSUE TITLE
Turret (auto defender) gets blocked and stops tracking

### ISSUE THREAD

**Issue by natamru** [Uuvana-Studios/longvinter-windows-client#663] opened 2022-04-03 05:17 UTC
Conditions
-Turret is on the same level as a fence
-Turret is on top of something (doesn't need to be a fence)
-Player walks towards fence

Issue:
When a player walks towards a fence first the turret gets blocked and then it stops tracking

https://user-images.githubusercontent.com/16938875/161412706-7bd87310-2716-4f8e-a599-9ffa985af28c.mp4

https://user-images.githubusercontent.com/16938875/161413132-684ccd6f-03e6-43bc-a3ae-14ccd4136792.mp4

Expected behavior:
-turret continues to track enemy
-turret damages enemy

Suggested resolution:
Make the turret taller than the fence.
Better line of sight algorithm.

System tested:
Windows 8
Windows 8.1
Windows 10 21H2

__________________________________________________________________________________________________________________________________________

Feature Request:
Give turret two modes, passive and active, in passive mode it will only shoot when enemy weapon is draw/active like in safe zones.

**Comment by faketucker** [comment] 2022-04-03 17:01
> Feature Request:
> Give turret two modes, passive and active, in passive mode it will only shoot when enemy weapon is draw/active like in safe zones.

If you have any suggestions about this game, you can submit your suggestions [the official forum](https://forum.uuvana.com/t/suggestions). Make sure to read the sticky posts before posting

**Comment by faketucker** [comment] 2022-04-03 17:02
Duplicate of #377

**Closed by faketucker** 2022-04-03 17:02 UTC
Labels: Bug, Not Tested
