### ISSUE TITLE
Us West uuvanna 1

### ISSUE THREAD

**Issue by Diabl01** [Uuvana-Studios/longvinter-windows-client#970] opened 2022-06-28 20:07 UTC
The server is not working and I can not go in my base or leave or my things dont work can we get this fixed

**Comment by faketucker** [comment] 2022-06-30 04:50
Can you try it now? It should be better now.

**Comment by faketucker** [comment] 2022-06-30 04:50
Duplicate of #974

**Closed by faketucker** 2022-06-30 04:50 UTC
Labels: Bug, Not Tested
