### ISSUE TITLE
I cant loot backpack in the water

### ISSUE THREAD

**Issue by Ocesguan** [Uuvana-Studios/longvinter-windows-client#1139] opened 2022-08-04 03:50 UTC
**Describe the bug**

**To Reproduce**
4. See an error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Game Version [e.g. 1.0]
 - Steam Version [e.g. 1.0]

**Additional context**

**Comment by faketucker** [comment] 2022-08-04 05:49
Duplicate of #450

**Closed by faketucker** 2022-08-04 05:49 UTC
Labels: Bug, Not Tested
