### ISSUE TITLE
I cant place outside stuff

### ISSUE THREAD

**Issue by cmod31** [Uuvana-Studios/longvinter-windows-client#509] opened 2022-03-19 18:53 UTC
When i want to place turrets or fences they teleport to the water and drop as items.

I was near Diogo Docks pretty near where you can start building.

![Screenshot 2022-03-19 195242](https://user-images.githubusercontent.com/80621863/159134655-9ab66fd1-90b1-4a82-8d48-8f0a4ed1b1a7.png)

**Comment by cmod31** [comment] 2022-03-19 18:55
not only in the water they teleport around and land on other peoples property and trees

**Comment by faketucker** [comment] 2022-03-26 01:49
Duplicate of #492

**Closed by faketucker** 2022-03-26 01:49 UTC
Labels: bug, Not Tested
