### ISSUE TITLE
You can still controll the game in the pause video

### ISSUE THREAD

**Issue by cmod31** [Uuvana-Studios/longvinter-windows-client#337] opened 2022-03-10 20:15 UTC
Hey you can still do everything in the game and even open other menus when you are in the pause menu.
Here is a video but when i wanted to show that the bug still happens in the admin panel the admin panel just stopped working so thats also a bug somehow

https://user-images.githubusercontent.com/80621863/157746999-83e9b34c-351e-4d19-a8c2-1df75d859496.mp4

**Comment by TophC7** [comment] 2022-03-10 22:22
The menus opening and etc should probably be fixed but i understood this as a feature not a bug. Since the game is live and people can literally shoot you i see player movement even in the pause menu important. I can start running away even if pause and then unpause quickly and react to whatever is happening.

**Comment by cmod31** [comment] 2022-03-13 14:45
But it still doesn't look high quality

**Comment by Jalsson** [comment] 2022-11-09 16:24
Menus can no longer be clicked trough the main menu screen. Fixed in next update. Movement will not be disabled while in menu because this is a multiplayer game

**Closed by Jalsson** 2022-11-09 16:24 UTC
Labels: Bug, Low Priority, Tested
