### ISSUE TITLE
When I use Item the game logs out

### ISSUE THREAD

**Issue by bmoreira0** [Uuvana-Studios/longvinter-windows-client#253] opened 2022-03-07 12:32 UTC
**Describe the bug**
Whenever I click on something on my inventory, the game goes back to the start screen.

**To Reproduce**
1. Enter the game, chose a server
2. Click tab to open the inventory
3. Click on any item on the inventory
4. The game logs out

**Expected behavior**
I should not be logged out when trying to use itens

**Screenshots**

https://user-images.githubusercontent.com/2228589/157035090-8028f543-f163-4d3d-9a27-59d790382407.mp4

**Desktop (please complete the following information):**
 - OS: Wiondows
 - Game Version 1.0.0
 - Steam Version [e.g. 1.0]

**Additional context**

**Comment by TwinkieShip** [comment] 2022-03-07 12:33
Bug Invalid: Read the patch notes

**Comment by Ekhalal** [comment] 2022-03-07 12:34
Same problems with friends

**Comment by Mayahze** [comment] 2022-03-07 12:38
Exactement pareil

**Comment by MonsterFudgy** [comment] 2022-03-07 12:39
Same issue

**Comment by TheJudeAbides** [comment] 2022-03-07 12:41
same here - even when transferring things from storage into my inventory.

**Comment by TredaCheese** [comment] 2022-03-07 12:45
Same bug happening with me, as soon as I open inventory and left click I am gone

**Comment by kORNZERth** [comment] 2022-03-07 12:47
SAME

**Comment by lisabei** [comment] 2022-03-07 12:47
Same bug for me

**Comment by sikkidu** [comment] 2022-03-07 12:53
same bug for me that happen 10 times when I do that and I'm about to finish quest then is bug happen and also all quest is gone TT

**Comment by sirNugg3ts** [comment] 2022-03-07 12:57
Server or client is not updated. Please update both

**Comment by sikkidu** [comment] 2022-03-07 13:03
i did that but still keep happen

**Comment by DragonfireLeo** [comment] 2022-03-07 13:03
same bug are the official severs been updated because can replicate bug on (AUS) Uuvana 1

**Comment by Mayahze** [comment] 2022-03-07 13:04
Not all servers have been updated with the new version yet    

Ca a était dit sur le discord

**Comment by FluffyWiener** [comment] 2022-03-07 13:09
Yeah i even deleted the game completely and redownloaded it and still not working

**Comment by moatib** [comment] 2022-03-07 14:54
same bug on my private server.
it come with this message on server log : 
[2022.03.07-14.47.43:561][828]LogNet: Error: ReceivedRPC: ReceivePropertiesForRPC - Mismatch read. Function: RemoveItemFromCraftingInventoryServer, Object: InventoryComponent_C /Game/Maps/LongvinterIsland.LongvinterIsland:PersistentLevel.ThirdPersonCharacter_C_2147471260.InventoryComponent
[2022.03.07-14.47.43:562][828]LogNet: Error: UActorChannel::ProcessBunch: Replicator.ReceivedBunch failed.  Closing connection. RepObj: InventoryComponent_C /Game/Maps/LongvinterIsland.LongvinterIsland:PersistentLevel.ThirdPersonCharacter_C_2147471260.InventoryComponent, Channel: 3

**Comment by FluffyWiener** [comment] 2022-03-07 15:41
Anyone know why when i try to equip a fishing rod i get disconnected from the server?

**Comment by Jalsson** [comment] 2022-03-07 15:54
The update is now released so update your servers and all the disconnecting should end. We have not yet encountered a problem where the player disconnect was NOT caused by a version mismatch

**Closed by Jalsson** 2022-03-07 15:54 UTC
Labels: bug, Not Tested

**Comment by cmod31** [comment] 2022-03-07 16:04
no i still got this and i updated. i'm using https://github.com/Uuvana-Studios/longvinter-linux-server

**Comment by cmod31** [comment] 2022-03-07 16:16
nevermind the experimental build of the client game doesnt work just yet
