### ISSUE TITLE
vending machine window wont close if double clicked 

### ISSUE THREAD

**Issue by ryhoquist44** [Uuvana-Studios/longvinter-windows-client#490] opened 2022-03-19 04:49 UTC
**Describe the bug**
every time you double click the vender you can interact but it wont let you close out of it.

**To Reproduce**
1. double click any vending machine

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Game Version latest
 - Steam Version latest

**Additional context**

**Comment by faketucker** [comment] 2022-03-26 15:55
Duplicate of #410

**Closed by faketucker** 2022-03-26 15:55 UTC
Labels: bug, Not Tested
