### ISSUE TITLE
집한채만 남고 템이란 템은 싹 다 사라졌습니다.

### ISSUE THREAD

**Issue by qortmddbs** [Uuvana-Studios/longvinter-windows-client#1675] opened 2024-09-01 06:45 UTC
![스크린샷 2024-08-29 222754](https://github.com/user-attachments/assets/6680cf0a-9622-4647-b14c-4f2bb4bb926a)
사진속이 원래 저희집이였는데 집만 남고 울타리부터 보관함 포탑등등 아이템이 싹다 사라졌습니다 ㅠㅠ
스팀아이디: yoon4648
닉네임: 팔득

**Comment by qortmddbs** [comment] 2024-09-01 06:47
> ![스크린샷 2024-08-29 222754](https://private-user-images.githubusercontent.com/180073396/363464664-6680cf0a-9622-4647-b14c-4f2bb4bb926a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUxNzM1MDIsIm5iZiI6MTcyNTE3MzIwMiwicGF0aCI6Ii8xODAwNzMzOTYvMzYzNDY0NjY0LTY2ODBjZjBhLTk2MjItNDY0Ny1iMTRjLTRmMmJiNGJiOTI2YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwMVQwNjQ2NDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zZTQ4ZmVkZThjZDdmZTUxNjNiZDgzZWNlNGI2MWIxOTFjMzU2NzhkZGZmNmM5M2E1MWMxNzc0MDcwMGQ3Yjk3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.CPBv3Ajhncng1IKAd8MJ1Wm0WcqyVvZWtYURwVsX1ck) 사진속이 원래 저희집이였는데 집만 남고 울타리부터 보관함 포탑등등 아이템이 싹다 사라졌습니다 ㅠㅠ 
스팀아이디: yoon4648 
닉네임: 팔득 
서버: (kr)uuvana1 pvp

**Comment by faketucker** [comment] 2024-09-03 11:10
Duplicate of #600

**Closed as completed by faketucker** 2024-09-03 11:10 UTC
Labels: Bug, Not Tested
