### ISSUE TITLE
in bangkok 2 a lot of house lost somethings went i come in server

### ISSUE THREAD

**Issue by iamamimai** [Uuvana-Studios/longvinter-windows-client#1159] opened 2022-08-09 14:58 UTC
![image](https://user-images.githubusercontent.com/104903750/183684252-6675665b-2acf-4000-97f2-93b39cf23c5c.png)

**Comment by faketucker** [comment] 2022-08-11 13:32
Duplicate of #1164

**Closed by faketucker** 2022-08-11 13:32 UTC
Labels: Bug, Not Tested
