### ISSUE TITLE
[SG] Uuvana 1 server bug or lag?

### ISSUE THREAD

**Issue by Demon-Boi** [Uuvana-Studios/longvinter-windows-client#1205] opened 2022-09-04 06:34 UTC
**Describe the bug**
Server is unplayable since 30 Aug 2022. at artic region but no energy drops for awhile, but after a few minutes i see my energy dropped by a few bars. Unable to pick up items, houses and self installed turrets are invisible as well. Ping seems fine but just unplayable

**Expected behavior**
Server should be running smoothly with houses and other props placed loaded properly

**Screenshots**
![image](https://user-images.githubusercontent.com/106092342/188300707-1edd60b2-91b7-41e7-a784-93c1d2b9ed7f.png)
![image](https://user-images.githubusercontent.com/106092342/188300731-e7a327be-0590-4a4b-b7dd-fdef1e85b0c7.png)

**Desktop (please complete the following information):**
OS: Win 11
Game Version 1.0.8b

**Comment by faketucker** [comment] 2022-09-04 07:46
Duplicate of #1164

**Closed by faketucker** 2022-09-04 07:46 UTC
Labels: Bug, Not Tested
