### ISSUE TITLE
money is loss after cabinnets loss 

### ISSUE THREAD

**Issue by Aralyftg** [Uuvana-Studios/longvinter-windows-client#1013] opened 2022-07-05 11:29 UTC
**Describe the bug**

**To Reproduce**
4. See an error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Game Version [e.g. 1.0]
 - Steam Version [e.g. 1.0]

**Additional context**

**Comment by faketucker** [comment] 2022-07-05 16:11
Progress might be rolled back because of the update

**Comment by faketucker** [comment] 2022-07-05 16:11
Duplicate of #600

**Closed by faketucker** 2022-07-05 16:11 UTC
Labels: Bug, Not Tested
