### ISSUE TITLE
 steam achievements not awarding after reaching goals

### ISSUE THREAD

**Issue by BloodRaven308** [Uuvana-Studios/longvinter-windows-client#794] opened 2022-04-17 19:39 UTC
**Describe the bug**
Multiple steam achievements are not awarding properly. i have completed the objectives for Deforestation, Chicken of Longvinter, MIxed feelings, Community Cultivator. i have completed all the objectives multiple times without it awarding correctly. 

**Expected behavior** 
Complete steam objective be awarded achievement. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows] Windows 10
 - Game Version [e.g. 1.0] 1.0.3
 -  - Steam Version [e.g. 1.0]

**Additional context**
completed the listed objectives multiple times without  game issuing achievements

**Comment by faketucker** [comment] 2022-04-17 23:34
Duplicate of #421

**Closed by faketucker** 2022-04-17 23:34 UTC
Labels: Bug, Not Tested
