### ISSUE TITLE
Item Error Glitch

### ISSUE THREAD

**Issue by 1deadblawer** [Uuvana-Studios/longvinter-windows-client#212] opened 2022-03-06 01:51 UTC
**Describe the bug**
After cleaning out my inventory, I reopened the chest I dropped the items in and had an item with no name and a white box

**To Reproduce**
I have no idea how I managed this

**Expected behavior**
I expected to see the items I had just dumped in that chest

**Screenshots**
[Link to the Screenshot](https://steamcommunity.com/sharedfiles/filedetails/?id=2774047516)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro | Version  10.0.19044 Build 19044
 - Game build: Beta 1.0.0
 - Steam Build: v020 

**Additional context**
I tried to reproduce the bug with the same chest and different items, but nothing happened. I am wondering if maybe the server just lost the item and gave the weird box as a filler.

**Comment by sirNugg3ts** [comment] 2022-03-17 12:36
Duplicate of #395

**Closed by sirNugg3ts** 2022-03-17 12:36 UTC
Labels: bug, Not Tested
