### ISSUE TITLE
vending machine menu doesent close

### ISSUE THREAD

**Issue by Aprim3** [Uuvana-Studios/longvinter-windows-client#739] opened 2022-04-11 08:32 UTC
**Describe the bug**
The vending machine menu wont close

**To Reproduce**
1. Go to 'a vending machine'
2. Click on 'use it'
3. Scroll down to 'try to close it'
4. See an error

**Expected behavior**
I expected the red X or TAB would close the vending machine menu but instead sends me to the game menu

**Desktop (please complete the following information):**
 - OS: [Windows 11]
 - Game Version [1.0.2]
 - Steam package version [1647446817]
 - Steam API version [020]
 
**Additional context**
When i try to die with the menu up it dosent close when i respawn

**Comment by sirNugg3ts** [comment] 2022-04-11 09:27
Duplicate of #410

**Closed by sirNugg3ts** 2022-04-11 09:27 UTC
Labels: Bug, Not Tested
