### ISSUE TITLE
Box Duplication Bug

### ISSUE THREAD

**Issue by mysticmasterfin** [Uuvana-Studios/longvinter-windows-client#156] opened 2022-03-03 04:24 UTC
**Describe the bug**
Duplicating boxes what cannot be moved when loot bad appears in the middle.
The box has loot bag in the middle and you cant get it out. but when trying it pulls out more crates/boxes.
**To Reproduce**
1. Go to 'may happen if go between homes and in inventory there is box.'
2. Click on 'right and left mouse button also spacebar, spamming the buttons makes it happen.'
3. Scroll down to 'um, down?'
4. See error: in your ways?

**Expected behavior**
there should be only one box, the one who rules them all.  ..wait wrong movie.
**Screenshots**
If applicable,
add screenshots to help explain your problem. 
![Capture 2022-03-03 at 04 24 25 739](https://user-images.githubusercontent.com/100821214/156496076-02bea1de-ae2f-452f-a080-033fc849ab55.png)
Im sure if you try to remove these they will start dublicating. and they will not move.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows] yes
 - Game Version [e.g. 1.0] yes
 - Steam Version [e.g. 1.0] uh yes?

**Additional context**
patch made in 2.3.2022 may have something to do with it
![Capture 2022-02-28 at 01 22 05 706](https://user-images.githubusercontent.com/100821214/156495812-44ba32d6-30d9-461b-b386-de78ce5edc5b.png)
.

**Comment by mysticmasterfin** [comment] 2022-03-04 02:33
Sorry I'm traveling and without pc. Also my shadowplay recording is not
liking to work. Maybe it was only in eu uuvana 2 server in east northern
side, snow area. Or maybe it was my friend Boxx who accidentally created
the bug. It may be act like a virus when you interact with the bugged
container. Sorry that I can't help more, right now to locate the issue.
Next time I try make video of bug's. 🐜

- Mystic-

**Comment by Genewolf** [comment] 2022-03-05 22:23
Hi, I've accidently reproduce this little glitch and... I find it funny so I did it again and again... and actually, all of the boxes insine of my house are filled with boxes... by doing it without stoping, I think I found from where do this glitch come from: the house system is like an alternative universe where you can put object for houses, but it's directly linked with the "real universe" so for me, this glitch come from a problem at the moment the box is looted, maybe it collapse with an object of the other universe and respawning with the looted one...
I prefer to excuse myself now if there is some mistakes in my sentences, I'm french and I'm not really good in english ^^'
![Capture](https://user-images.githubusercontent.com/79755741/156901694-77bcb180-3642-4c78-a792-8697941ab988.PNG)

**Comment by mysticmasterfin** [comment] 2022-03-05 23:04
Yes, you clearly found it. I see the loot bag, glitching inside the box.
And that is now unmovable object. Good work. Door to the dimension of
boxverse has been found, let's hope we don't find the evil box. Maybe we
should close this door before that happens. :P good luck.

**Comment by mysticmasterfin** [comment] 2022-03-15 03:06
https://user-images.githubusercontent.com/100821214/158297964-5b215543-ff2a-479a-8999-756473436213.mp4

**Comment by mysticmasterfin** [comment] 2022-03-15 03:10
Tried to dup in private server it was way harder to do. but we were able to do it. not sure why it works only some places at private.
How it activates is unknown. some boxes work like normal. This bug is difficult to replicate.

**Comment by faketucker** [comment] 2022-03-26 06:56
This occurred because two containers were placed in the same spot and should be fixed by the latest update; you can no longer place two items in the same spot anymore. You should be able to pick it up after the server restarts.

**Closed by faketucker** 2022-03-26 06:56 UTC
Labels: bug, High Priority, Not Tested
