### ISSUE TITLE
invisible cooker.

### ISSUE THREAD

**Issue by grimmy707** [Uuvana-Studios/longvinter-windows-client#984] opened 2022-07-02 04:50 UTC
game version 1.0.8
after placing the cooker i just went and cut wood etc doing longvinter stuff. Then later when i came back the cooker was missing, 
I thought someone took it but in the place i put it their was an invisible object i could not walk through. So i tried tapping it and i could use the cooker but could still not see the cooker.

**Comment by faketucker** [comment] 2022-07-02 05:03
Duplicate of #978

**Closed by faketucker** 2022-07-02 05:03 UTC
Labels: Bug, Low Priority
