### ISSUE TITLE
My Character is reset. I lost all the in game cash and item in inventory.

### ISSUE THREAD

**Issue by MaruLow** [Uuvana-Studios/longvinter-windows-client#232] opened 2022-03-06 16:18 UTC
**Describe the bug**
I lost connection with the server. And then reconnect , my item dissapear and all the ingame cash that i grind from fishing is gone. It's heart breaking.

**To Reproduce**
1. Go to 'disconnected from the server because wifi problems'
2. Click on 'wifi fix  , and then reconnect, my character literally lost all the cash i've made from fishing all day long, plus with the items'

**Expected behavior**
I thot this bug is already been fixed it.

**Desktop (please complete the following information):**
 - OS:  Windows
 - Game Version [e.g. 1.0]
 - Steam Version [e.g. 1.0]
  
**Additional context**
Now because of this bug, later i will withdraw the money and save it on boxes. Plus when you try to upgrade your tent , if you disconnect from the game and come back in, all your woods that have been deposit into workbench for upgrade are ALSO RESET back to ZERO

**Comment by sirNugg3ts** [comment] 2022-03-06 17:32
Duplicate of #120

**Closed by sirNugg3ts** 2022-03-06 17:32 UTC
Labels: bug, Not Tested
