### ISSUE TITLE
cant close popup (ex. vending machine, backpack)

### ISSUE THREAD

**Issue by koreayoutuber** [Uuvana-Studios/longvinter-windows-client#615] opened 2022-03-28 17:03 UTC
**Describe the bug**

**To Reproduce**
4. See an error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Game Version [e.g. 1.0]
 - Steam Version [e.g. 1.0]

**Additional context**

**Comment by faketucker** [comment] 2022-03-28 17:50
Duplicate of #410

**Closed by faketucker** 2022-03-28 17:50 UTC
Labels: Bug, Not Tested
