### ISSUE TITLE
Item glitch when moving tons of items at once

### ISSUE THREAD

**Issue by natamru** [Uuvana-Studios/longvinter-windows-client#659] opened 2022-04-02 16:31 UTC
Condition:
Move lots of items rapidly from bag to storage or storage to bag

Issue:
Item glitch when moving tons of items at once this results in either one or a combination of:
-Item duplication
-Item merging
-Additional storage
-a white square

![Capture](https://user-images.githubusercontent.com/16938875/161392300-96ba2de5-8bd8-4c8e-be45-de5b66a7d5de.JPG)
![Capture 2](https://user-images.githubusercontent.com/16938875/161392302-be4fe61c-41de-468e-9b05-11d23e7ae3f5.JPG)

System tested:
Windows 8
Windows 8.1
Windows 10 21H2

**Comment by sirNugg3ts** [comment] 2022-04-02 17:06
Duplicate of #212 and #441

**Closed by sirNugg3ts** 2022-04-02 17:06 UTC
Labels: Bug, Not Tested

**Comment by natamru** [comment] 2022-04-02 17:12
Let me add that my ping is 50ms to the server and the jitter is under 10ms
