### ISSUE TITLE
Half my base vanished.

### ISSUE THREAD

**Issue by Luxembourg89** [Uuvana-Studios/longvinter-windows-client#612] opened 2022-03-28 15:57 UTC
**Describe the bug**
Half my base is gone after the last patch.
![insidelongvinter](https://user-images.githubusercontent.com/102540175/160438714-c9af3c83-22de-4466-b96a-2b61128d6d18.jpg)
![outsidelongvinter](https://user-images.githubusercontent.com/102540175/160438744-40952092-0bab-4146-a6b9-f5a75defc117.jpg)

**Comment by Luxembourg89** [comment] 2022-03-28 16:00
![outsidelongvinter](https://user-images.githubusercontent.com/102540175/160439269-adee2229-4f20-42f3-a57b-66b248dfe7f3.jpg)
someone else's tent appeared beside my other house

**Comment by faketucker** [comment] 2022-03-28 16:35
Duplicate of #600

**Closed by faketucker** 2022-03-28 16:35 UTC
Labels: Bug, Not Tested
