### ISSUE TITLE
Fire in air

### ISSUE THREAD

**Issue by hoak** [Uuvana-Studios/longvinter-windows-client#485] opened 2022-03-18 23:31 UTC
**Describe the bug**
Fire got place in midair

**To Reproduce**
1. Place fire
2. it is in mideair and unusable

**Expected behavior**
Expect it to be on ground

**Screenshots**
![Capture](https://user-images.githubusercontent.com/14806514/159096734-0cc1dfe4-bf85-459c-9dbd-deb40355cf60.PNG)

**Desktop (please complete the following information):**
 - OS: window s10
 - Game Version march 18th
 - Steam Versionmarch 18th
**Additional context**
I was able to place a working one just below it as seen in screenshot

**Comment by faketucker** [comment] 2022-03-26 10:21
This seems to only happen when you place things in some spots in the new biome.

**Comment by faketucker** [comment] 2022-03-26 10:21
Duplicate of #492

**Closed by faketucker** 2022-03-26 10:21 UTC
Labels: bug, Not Tested
