### ISSUE TITLE
My character is stuck in the middle of river

### ISSUE THREAD

**Issue by CalvinZoe** [Uuvana-Studios/longvinter-windows-client#451] opened 2022-03-17 08:11 UTC
**Describe the bug**
My character is stuck in the river, cant move or swim. I was swimming then it lagged out then when i enter i am stuck back. And i keep disconnect or quit and reenter, still the same.

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/101794230/158765113-88d40b33-1349-4f3b-8c03-aaa9462987f8.jpg)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Game Version [e.g. 1.0]
 - Steam Version [e.g. 1.0]

**Additional context**

**Comment by lolkds** [comment] 2022-03-17 13:37
maybe try entering kill/ I do believe youll die tho, youll be unstuck tho

**Comment by faketucker** [comment] 2022-03-26 15:11
Duplicate of #565

**Closed by faketucker** 2022-03-26 15:11 UTC
Labels: bug, Not Tested
