### ISSUE TITLE
Vendow window will not close

### ISSUE THREAD

**Issue by candyseeker** [Uuvana-Studios/longvinter-windows-client#713] opened 2022-04-08 14:45 UTC
When accessing a vendor, the window will not close. Pressing X on the menu itself or ESC key only pulls up the main menu. The only fix is disconnecting from the server and logging back on.

**Comment by faketucker** [comment] 2022-04-08 15:54
Duplicate of #410

**Closed by faketucker** 2022-04-08 15:54 UTC
