### ISSUE TITLE
Server list is empty and blank

### ISSUE THREAD

**Issue by Mongulusus** [Uuvana-Studios/longvinter-windows-client#405] opened 2022-03-14 12:13 UTC
**Describe the bug**
The server list is emty and dont show any Server.
Even after waiting for (30 minutes), restart the game or reinstalled it.
Thtas why you cant join a server and cant play the game.

**To Reproduce**
1. Start the game
2. go to "Play"
3. See a empty list with no servers

**Expected behavior**
I ecpected that on the sever list are servers, which i can join to play the game.

**Desktop (please complete the following information):**
 - Windows 10
 - Game Version 1.0.0

**Additional context**
![Screenshot 2022-03-14 131036](https://user-images.githubusercontent.com/101561507/158169553-542f576d-9bda-42a6-862b-5bda8f678275.png)

**Comment by sirNugg3ts** [comment] 2022-03-17 12:27
This seems to be more a connection issue than a bug with the game, plase be sure that you don't have firewall issues or NAT issues.

**Comment by sirNugg3ts** [comment] 2022-03-17 15:35
Duplicate of #238

**Closed by sirNugg3ts** 2022-03-17 15:35 UTC
Labels: bug, need more info, Not Tested

**Comment by Bunnbunnnn** [comment] 2022-03-18 12:05
Player had similar problems and found these similar threads in discord: 
https://discord.com/channels/846308806870695967/846308807386464268/954221364821241886
https://discord.com/channels/846308806870695967/934069436216918017/953762740978216971

This peson cannot either and just had to opt to connect only via session id 
https://discord.com/channels/846308806870695967/934069436216918017/953139544641925150
