### ISSUE TITLE
Can't Close Out of Tim's Outpost

### ISSUE THREAD

**Issue by lrogier** [Uuvana-Studios/longvinter-windows-client#568] opened 2022-03-24 00:47 UTC
**Describe the bug**
I opened Tim's Outpost, I walked away, and now I can't get the tab to close, but I can open a second tab.

**To Reproduce**
1. Go to Tim's Outpost
2. Click on it
3. Walk away
4. Window is now stuck open.

**Expected behavior**
I expected the outpost tab to go away.

**Screenshots**
See below

**Desktop (please complete the following information):**
 - OS: Windows
 - Game Version 1.0.1
 -  Steam Version  ?

**Additional context**
![2022-03-23 (3)](https://user-images.githubusercontent.com/102268084/159819921-da210fb1-164a-4181-bc68-e09c5cacf4e2.png)

![2022-03-23 (2)](https://user-images.githubusercontent.com/102268084/159819913-098392b8-cbdf-467f-959c-3f132e2c8f13.png)

**Comment by sirNugg3ts** [comment] 2022-03-24 09:16
Duplicate of #410

**Closed by sirNugg3ts** 2022-03-24 09:16 UTC
Labels: bug, Not Tested
