### ISSUE TITLE
Tent has weird wall glitch

### ISSUE THREAD

**Issue by iFernandez96** [Uuvana-Studios/longvinter-windows-client#649] opened 2022-04-01 21:45 UTC
Tent has a weird wall glitch. Makes it really hard to do anything in it.
![image](https://user-images.githubusercontent.com/51539200/161345426-04b452da-66d2-40dc-9658-1511e0272276.png)

**Comment by faketucker** [comment] 2022-04-02 02:50
Duplicate of #625

**Closed by faketucker** 2022-04-02 02:50 UTC
