### ISSUE TITLE
The house wall is glitching outside/inside of the tent

### ISSUE THREAD

**Issue by byoohoo** [Uuvana-Studios/longvinter-windows-client#625] opened 2022-03-29 14:48 UTC
**Describe the bug**
Logged on to the [US] uuvana 5 server on 3/29/2022 @ 10:15 EST and found my primary house (along with all items and furniture inside) was gone. I am thinking this is due to an issue that I observed on the day prior when I had placed down a tent for my secondary home and upgraded into a house. When placing my secondary home, I placed and dismantled the tent once or twice to adjust the location. When I was doing this, the tent was placed down strangely and visually appeared to have house walls bugged onto the tent model. When I entered my bugged tent, it glitched and teleported me back to the main island. After going back to the location where I had placed my tent, that tent was gone nowhere to be seen. I then went on to place another tent I had, to re-place my "second" home that had disappeared, and then saw no further issue with my secondary home. However the day after, I found that my primary home disappeared with all items inside.

**To Reproduce**
N/A - I am unsure what the cause of the issue. Only speculations described above.

**Expected behavior**
N/A

**Screenshots**
![bug](https://user-images.githubusercontent.com/83621224/160636833-3778f6c8-d900-4523-a1eb-1fd6c2f3322a.png)

**Desktop (please complete the following information):**
 - Windows 10 64 Bit
 - Longvinter Beta 1.0.2
 - Steam API: v020
 - Steam Package version 1647746817

**Additional context**
N/A

**Comment by faketucker** [comment] 2022-03-29 15:30
For the house disappering bug. I'm afraid you can't get you house back. But you can try to place a tent where your house disappeared. You might find all the items in the void and dismantle and place them till all the items are in your tent. The devs are working on this to prevent it from happening again. Also a duplicate of #600.

![1](https://user-images.githubusercontent.com/28383557/160645118-77fe368f-4299-49b5-854e-5d48c024745f.png)

And for the visually house wall bug, it seems new. I faced this once when I placed a tent where I used to dismantle the house, but I couldn't find a way to replicate it. I just dismantled it and placed it again. I'm going to leave this issue open so that the devs can look into it and possibly find a solution.

**Comment by Mikooboy** [comment] 2022-06-14 11:50
House interior visibility should be set more reliably which should help prevent this in the next update.

**Closed by Mikooboy** 2022-06-14 11:50 UTC
Labels: Bug, High Priority, Tested
