### ISSUE TITLE
Bug problem to upgrade the house

### ISSUE THREAD

**Issue by shshady3** [Uuvana-Studios/longvinter-windows-client#1180] opened 2022-08-21 20:30 UTC
**Describe the bug**
It says that we don't have enough space, but we have

here are the screenshoot
![Captura de pantalla 2022-08-21 213649](https://user-images.githubusercontent.com/111583547/185809679-50d115c9-624d-49be-b5c3-baab19a68db3.png)
![Captura de pantalla 2022-08-21 213707](https://user-images.githubusercontent.com/111583547/185809682-d6e991b3-a8b3-4fa3-8084-eed3e3083051.png)
![HighresScreenshot00000](https://user-images.githubusercontent.com/111583547/185809687-e39c2821-fbb4-401d-ad3d-b8493608acb6.png)
s

**Comment by faketucker** [comment] 2022-08-21 23:21
Duplicate of #1131

**Closed by faketucker** 2022-08-21 23:21 UTC
Labels: Bug, Not Tested

**Comment by shshady3** [comment] 2022-08-22 00:21
Where is the solution?
