### ISSUE TITLE
stacked wheat

### ISSUE THREAD

**Issue by Plant2** [Uuvana-Studios/longvinter-windows-client#104] opened 2022-03-01 03:10 UTC
**Describe the bug**
stacked wheat when planting

**To Reproduce**
1. plant new seed on full grown wheat
2. harvest full grown wheat
3. replace with new seed

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Game Version [e.g. 1.0]
 - Steam Version [e.g. 1.0]

**Additional context**
![Longvinter   2_28_2022 9_07_20 PM](https://user-images.githubusercontent.com/100554730/156097608-a16454e1-b609-46d0-ac69-d7d26474120c.png)

**Comment by Jalsson** [comment] 2022-03-02 15:01
Cannot reproduce anymore. Seems to fixed by other changes we made to placing

**Closed by Jalsson** 2022-03-02 15:01 UTC
Labels: bug, Not Tested
