### ISSUE TITLE
Data has been reverted to its previous state

### ISSUE THREAD

**Issue by deok9ya** [Uuvana-Studios/longvinter-windows-client#1686] opened 2024-09-17 15:28 UTC
The server was turned off and on on Wednesday, September 18, 2024, Korean time.

I played the game until 12:00 (05:10~12:00).

I set the alarm for the time when the supply came out and played the game really hard.

I ate a lot of items and decorated my house too hard, but

All the data has been reverted to the previous state.

All the items have disappeared and my house has been reverted to the state before I decorated it.

The player server is [KR] Uuvana 1 server and my player ID is
"외계인", "인간". Please restore the data.

I translated it with Google Translate, so the translation may not be correct.
I'm sorry.

Windows 10 update is the latest, game version 1.14, Steam version is the latest.

**Comment by lasdah** [comment] 2024-09-17 23:41
Clicking anywhere in game causes the window to tab out, controller is unplugged game has be reinstalled before still same issue. I cannot change any In game setting as well because anything I click on causes tab out

**Comment by faketucker** [comment] 2024-10-29 03:41
Duplicate of #600

**Closed as completed by faketucker** 2024-10-29 03:41 UTC
Labels: Bug, Not Tested
