### ISSUE TITLE
Equip satellite communicator - Steam achievement not unlocking

### ISSUE THREAD

**Issue by Anneweetwel** [Uuvana-Studios/longvinter-windows-client#20] opened 2022-02-26 16:27 UTC
**Describe the bug**
Equip satellite communicator - Steam achievement not unlocking after equipping the satellite communicator.

**To Reproduce**
1. Buy the satellite communicator
2. Equip the satellite communicator
3. See the coordinates showing up at the top-right
4. Not seeing the Steam achievement popping up

**Expected behavior**
I expected the steam achievement to pop up after equipping the satellite communicator, this pop up didn't happen and the steam achievement is still locked for me.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Game Version Beta 1.0.0
 - Steam Version 

**Additional context**

**Comment by sirNugg3ts** [comment] 2022-02-28 12:10
Duplicate of #35

**Closed by sirNugg3ts** 2022-02-28 12:10 UTC
Labels: bug, Low Priority
