### ISSUE TITLE
Turrets are not working properly with the electricity system

### ISSUE THREAD

**Issue by WeGotAJungler** [Uuvana-Studios/longvinter-windows-client#585] opened 2022-03-25 17:19 UTC
So, I updated the server for the new patch and now a large portion of Auto-Turrets are now disabled?!

**To Reproduce**
1. Go to Server Control Panel
2. Click on Update Server
3. Log on to the Server
![20220325101439_1](https://user-images.githubusercontent.com/102380051/160169703-392da0a4-73ad-422e-9afd-4bf43135f702.jpg)

Also Picking up the Auto-Turret and placing it back down does not change the fact it is still disabled

**Comment by biffotmc** [comment] 2022-03-25 17:20
This is not a bug, you need electricity to power your turrets now.

**Comment by WeGotAJungler** [comment] 2022-03-25 17:56
> This is not a bug, you need electricity to power your turrets now.

Negative i have my base's electricity fully upgraded so that's not it

**Comment by WeGotAJungler** [comment] 2022-03-25 17:59
> This is not a bug, you need electricity to power your turrets now.

I have 60/60 Power, fully upgraded. Only TWO Turrets will run off of 60 Electricity? See what I am saying? That's why what you are saying it not accurate. I have power.... 60... only two turrets work.

**Comment by ewrogers** [comment] 2022-03-25 22:51
I have the same issue. I removed all of my 5 turrets and tried to replace them with 60/60 energy (turbine+solar). Even replacing them one by one and waiting a minute has no effect. At first I thought maybe it was a range issue but I tried placing it next to the front door.

It would be great to see some kind of "energy consumption" over the turret when you're placing it. How much power does one even use? And also how much power is each source generating? I've noticed I have 60/60 and 60/80 at times (during the day, I assume solar is +20 during daylight, but unclear).

**Comment by faketucker** [comment] 2022-03-27 09:23
The whole electricity thing seems pretty bugged right now. I tried it with all six of my houses, and none of them worked properly. Most of them do not show electricity usage correctly. Some houses got one turret working, some got two, some got none.

> |Electricity|Amount|
> |----------|-------------------|
> |Solar Panels| +20 ⚡️|
> |Wind Turbine| +60 ⚡️ |
> |AutoTurret (x5)| -40 ⚡️|
> |**Total Utilization**| **40/80** ⚡️|

And this is a nice suggestion. Thank you, @ewrogers ! Sven has already planned to add all the info, so this might be implemented soon and this bug should be fixed by that time.

**Comment by faketucker** [comment] 2022-03-28 11:18
Fixed by the latest update.

**Closed by faketucker** 2022-03-28 11:18 UTC
Labels: Bug, Fixed
