### ISSUE TITLE
Can't close the shop window

### ISSUE THREAD

**Issue by xColine** [Uuvana-Studios/longvinter-windows-client#580] opened 2022-03-25 15:48 UTC
Hi guys
Sorry for my english, I'm French :)
Since yesterday, when I buy ou sell something, I'm not able to close the shop window. I can move, but the window is still here in the middle of my screen and i can't do anything until I reboot the game

**Comment by faketucker** [comment] 2022-03-25 15:56
Duplicate of #410 
This happens when you open the shop window more than once

**Closed by faketucker** 2022-03-25 15:56 UTC
