### ISSUE TITLE
Really bad lag on Uuvana east server 6

### ISSUE THREAD

**Issue by MrsMinzi** [Uuvana-Studios/longvinter-windows-client#1204] opened 2022-09-04 01:52 UTC
**Describe the bug**

1.Items & houses are gone. Will re appear after couple mins. 
2. Can't leave or enter the house. Few minutes later I'm inside, but its empty.
3. Hair color is mixture of brown and white. 
4. Ping is normal & no one is on yet the island seems like its erasing itself or gone invis.

**Expected behavior**
To run smoothly. 

**Screenshots**
![20220903214005_1](https://user-images.githubusercontent.com/111882439/188293723-f0dc9439-bb2d-49d7-b89b-e59b2a4a8df6.jpg)
![20220903213356_1](https://user-images.githubusercontent.com/111882439/188293724-94bd05a6-9b20-419d-98d3-90ed32ecb015.jpg)
![20220903213200_1](https://user-images.githubusercontent.com/111882439/188293727-06afac63-9bb6-4db1-b482-e916c39c662d.jpg)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Game Version [e.g. 1.0.8b]
 - Steam Version current version

**Additional context**
this is happening to 2 accounts on different computers.

**Comment by k8dogg** [comment] 2022-09-04 01:57
I also am experiencing this exact same bug on UV6

**Comment by Demon-Boi** [comment] 2022-09-04 06:36
same here on [SG] Uuvana 1

**Comment by faketucker** [comment] 2022-09-04 07:47
Duplicate of #1164

**Closed by faketucker** 2022-09-04 07:47 UTC
Labels: Bug, Not Tested
