### ISSUE TITLE
[EU] Uuvana 1 - Despawning, Losing Money and MORE

### ISSUE THREAD

**Issue by iamCry** [Uuvana-Studios/longvinter-windows-client#564] opened 2022-03-23 19:35 UTC
**Describe the bug**
My house keeps reverting back to a tent when I relog back into the server, Despite numerous hours pumped into the server I have lost all progress, logs stay inside the workbench however items are missing from my chests when relogging back into the server, I had 3 chests in there which one had guns, ammo and turrets for when I get electricity however this despawned and all items are lost as the house goes back to a tent.

When I use the ferry it doubles the fee sometimes as the ferry glitches out along with just spawning me in the middle of nowhere causing me to lose large loot runs to go back to my main base.

**Desktop (please complete the following information):**
 - OS: Windows
 - Game Version 1.0.1
 - Steam Version 1.0.1

**Additional context**
Is there a way to be reciprocated for items lost as there was two of us doing alot of work and putting items into the chests and losing items to ferry glitches and server crashes. IGN is ItZCrymZ

**Comment by iamCry** [comment] 2022-03-24 00:23
UPDATE - This happened again, full house was stacked with chests. Farmed for a few hours gaterhing everything, had the house fully upgraded and a chest full of turrets and one for bullets and then server crashed and I went back to having a tent. Had to farm all the wood again just to upgrade and see the Workbench back to standard. Ridiculous.

**Comment by faketucker** [comment] 2022-03-27 03:47
Duplicate of #600

**Closed by faketucker** 2022-03-27 03:47 UTC
Labels: bug, Not Tested
