### ISSUE TITLE
again I can not take my things!!!

### ISSUE THREAD

**Issue by Ksenia2703** [Uuvana-Studios/longvinter-windows-client#1111] opened 2022-07-29 11:13 UTC
![132543645674564](https://user-images.githubusercontent.com/90321080/181747443-02e37f2b-ff03-4e1a-a3fb-7f3ab115c78e.png)

**Comment by faketucker** [comment] 2022-07-29 12:57
Duplicate of #1099

**Closed by faketucker** 2022-07-29 12:57 UTC
Labels: Bug, Not Tested
