### ISSUE TITLE
Not letting me drop any items

### ISSUE THREAD

**Issue by feedmeimstoned** [Uuvana-Studios/longvinter-windows-client#489] opened 2022-03-19 03:34 UTC
**Describe the bug**
Not letting me drop/equip any items.

**To Reproduce**
1. Go to inventory
2. Click on any item to try and drop/equip
3.  It will not drop or equip.

**Expected behavior**
When you right click an item, it should be able to drop whatever item. When I click on something to equip, it should equip.

**Additional context**
Have not tested using it to aim gun, will update. 
This is happening on US uuvana 4

Edit: Cannot even equip gun, current item equipped is fishing pole, cannot unequip.

**Comment by faketucker** [comment] 2022-03-26 08:36
Duplicate of #494

**Closed by faketucker** 2022-03-26 08:36 UTC
Labels: bug, Not Tested
