### ISSUE TITLE
Bug of hair

### ISSUE THREAD

**Issue by shshady3** [Uuvana-Studios/longvinter-windows-client#1179] opened 2022-08-21 14:14 UTC
I have put on the ponytail and it comes out when I connect the hat on the left of the ponytail and my brother changed the hair too and the same thing appears

**Comment by faketucker** [comment] 2022-08-21 23:20
Duplicate of #1031

**Closed by faketucker** 2022-08-21 23:20 UTC
Labels: Bug, Not Tested

**Comment by shshady3** [comment] 2022-08-22 00:21
And the solution??
