### ISSUE TITLE
Decorative Round Table(Juniper) turns to Wood after placing and picking back up

### ISSUE THREAD

**Issue by kitchuwin** [Uuvana-Studios/longvinter-windows-client#1030] opened 2022-07-07 17:25 UTC
Placing down the table initially was Juniper, but when right clicked and then picked up, turned to regular wood in inventory and is now placed as regular wood color.

**Comment by faketucker** [comment] 2022-07-08 02:17
Duplicate of #1004

**Closed by faketucker** 2022-07-08 02:17 UTC
Labels: Bug, Not Tested
