### ISSUE TITLE
Stove Dissapearing

### ISSUE THREAD

**Issue by OrangeJuiceWSalt** [Uuvana-Studios/longvinter-windows-client#1000] opened 2022-07-03 21:21 UTC
When I Enter My House Wether its Upgraded or not . after i place my stove first time it doesnot dissapear but when i leave my houst and enter again it disappears

**Comment by OrangeJuiceWSalt** [comment] 2022-07-03 21:23
![image](https://user-images.githubusercontent.com/104396033/177057638-67b752ee-04cf-4fe8-b966-d55e939ee754.png)
![image](https://user-images.githubusercontent.com/104396033/177057644-11b9b7c3-24c5-448f-8d9c-134a007206d9.png)

**Comment by faketucker** [comment] 2022-07-04 03:52
Duplicate of #978

**Closed by faketucker** 2022-07-04 03:52 UTC
Labels: Bug, Not Tested
