### ISSUE TITLE
Vendor wont close after I open the UI

### ISSUE THREAD

**Issue by JohnPizzaCrust** [Uuvana-Studios/longvinter-windows-client#735] opened 2022-04-10 16:33 UTC
Whenever I go to an outpost vendor, I sell my stuff and try to get out, but it refuses to exit out of the UI no matter how hard I try. (this also happened at a dock too, and I tried every button on my PC to get it to close.

**Comment by sirNugg3ts** [comment] 2022-04-10 17:13
Duplicate of #410

**Closed by sirNugg3ts** 2022-04-10 17:13 UTC
Labels: Bug, Not Tested
