### ISSUE TITLE
All of my storage containers (in house) are gone!

### ISSUE THREAD

**Issue by NIZKDEE** [Uuvana-Studios/longvinter-windows-client#526] opened 2022-03-20 14:02 UTC
**MISSING CONTAINERS**
The containers in my house are missing and all of the items I have collected disappeared with them.

**To Reproduce**
Just loaded in to game.

**Expected behavior**
I expected to load into the game at my house and see that nothing was missing.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 - Game Version Beta 1.01

**Additional context**
I've lost everything I owned. Please fix this.

**Comment by sirNugg3ts** [comment] 2022-03-21 18:02
Duplicate of #527

**Closed by sirNugg3ts** 2022-03-21 18:02 UTC
Labels: bug, Not Tested
