### ISSUE TITLE
Chat message repeats twice after boat voyage from secret shop to sgt lake and back

### ISSUE THREAD

**Issue by hoak** [Uuvana-Studios/longvinter-windows-client#388] opened 2022-03-12 23:52 UTC
**Describe the bug**
A typed chat message keeps popping up long after you type it when you take a boat trip.

**To Reproduce**
1. TYpe a message like "Hi dude"  and wait for the message to go away.
2. Walk around the bog rock north of the Secret shop in the snow for like 8 seconds towards a boat at The secret shop boat.
3. Take the boat to Sgtl Lake.
4. Get off the boat, the message you typed pops up again as soon as you leave the boat.
5. The message goes away, buy some stuff, take as long as you like.
6. Get back on the boat to the secret shop.
7. As soon as you get off the boat the same message pops up again.

**Expected behavior**
When you type a message it should display once and not again twice again later.

**Screenshots**
I don't have one as this is easy to understand and reproducable it happend three times at different game periods, even after relogs.

**Desktop (please complete the following information):**
 - OS:Windows 10
 - Game Version 1.0.0
 - Steam Version 1.0.0

Nothing else to add it is easy to understand.

**Comment by KoalaBoy** [comment] 2022-03-13 22:50
#230

**Comment by faketucker** [comment] 2022-03-25 14:14
Duplicate of #230

**Closed by faketucker** 2022-03-25 14:14 UTC
Labels: bug, Low Priority, Tested
