### ISSUE TITLE
GAME-BREAKING BUG: Character Progression Is Wiped When Disconnecting From Game in Certain Situations

### ISSUE THREAD

**Issue by HelloFro** [Uuvana-Studios/longvinter-windows-client#211] opened 2022-03-06 01:38 UTC
**Describe the bug**
Character Compendium, Inventory, & MK hard reset when disconnecting from game while character is still inside house while server is max capacity AND multiple users try to join at same time you disconnect.

**To Reproduce**
1. Go inside tent/house.
2. Press esc to check player count is maxed (i.e. 50/50).
3. Disconnect or exit game.
4. Rejoin and character will be hard reset to initial spawning location.

**Expected behavior**
Log back in and character progression and location is maintained.

**Screenshots**
Screenshots irrelevant due to nature of bug.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Game Version 1.0.0
 - Steam Version 1.0.0

**Additional context**
- Your tents/houses are still registered to you and persist even when this happens. Just a lose a lot of access to shops and have to regrind for each compendium  completion.
- This bug may still occur without a full server, but untested thus far.

**Comment by LeMexicain** [comment] 2022-03-06 04:21
I just had the same bug, I lost all my progression...

**Comment by LeMexicain** [comment] 2022-03-06 07:20
Again twice in a day :( so much things lost...

**Comment by sirNugg3ts** [comment] 2022-03-06 15:15
Duplicate of #120

**Closed by sirNugg3ts** 2022-03-06 15:15 UTC
Labels: bug, Not Tested
