### ISSUE TITLE
Dismantling workstation (Tent/workstation Farming) 💯 

### ISSUE THREAD

**Issue by isnowcloud** [Uuvana-Studios/longvinter-windows-client#475] opened 2022-03-18 18:09 UTC
**Describe the bug**
Scenario:
If a user has 2 workstations in a house and tries to dismantle one/both the system returns the tent/workstation to the user(as many times as the user tries to dismantle the home), (resets)kicks them out of the house but the house is still in the same spot and can be accessed. 
**To Reproduce**
1. place two workstations in a household 
2. dismantle one of the work stations 
3. display inventory tab
4. workstation and tent are returned but house still exists on the property 

**Expected behavior**

**Screenshots**
![Screenshot (8)](https://user-images.githubusercontent.com/101480909/159059361-0229efc0-ea03-440a-a47d-9851ce67e016.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Game Version [e.g. 1.0.1]
 - Steam Version [e.g. 1.0]

**Additional context**

**Comment by Bunnbunnnn** [comment] 2022-03-20 10:52
These ones sound somewhat similar 
https://github.com/Uuvana-Studios/longvinter-windows-client/issues/513
https://github.com/Uuvana-Studios/longvinter-windows-client/issues/505
https://github.com/Uuvana-Studios/longvinter-windows-client/issues/496
https://discord.com/channels/846308806870695967/934069436216918017/955051271960789052

**Comment by faketucker** [comment] 2022-03-26 15:50
This seems to be caused by another reason, not because you have two workbenchs in the same tent.

**Comment by faketucker** [comment] 2022-03-26 15:50
Duplicate of #505

**Closed by faketucker** 2022-03-26 15:50 UTC
Labels: bug, Not Tested
