### ISSUE TITLE
Inside House visible outside

### ISSUE THREAD

**Issue by MJR1972** [Uuvana-Studios/longvinter-windows-client#800] opened 2022-04-18 20:10 UTC
**Describe the bug**
I'm not sure if this has been reported previously. I didn't see anything. but Inside house is coming through to the outside.

**To Reproduce**
1. On various houses the inside comes out and is visible to the outside.

**Expected behavior**
Shouldn't see inside of houses

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Win 11
 - Game Version 1.0.3
 - Steam Version 1.0.3

**Additional context**
This happens randomly.

https://user-images.githubusercontent.com/29164981/163870329-cfa0015a-8e1a-4092-bed5-3d21ba928969.mp4

**Comment by faketucker** [comment] 2022-04-19 00:34
Duplicate of #625

**Closed by faketucker** 2022-04-19 00:34 UTC
Labels: Bug, Not Tested
