### ISSUE TITLE
Containers and items within disappearing

### ISSUE THREAD

**Issue by LiquidChernobyl** [Uuvana-Studios/longvinter-windows-client#535] opened 2022-03-20 23:24 UTC
**Describe the bug**

**To Reproduce**

**Expected behavior**
I expected to log back in and see all my builds in place

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Game Version [e.g. 1.0]
 - Steam Version [e.g. 1.0]

**Additional context**
I don't understand how i have containers missing that were set up earlier in the beginning of my longvinter play then the most recent stuff, now hours of farming are all gone, i cant even go chop wood missing my chainsaws and axes.

**Comment by sirNugg3ts** [comment] 2022-03-21 17:56
Duplicate of #527

**Closed by sirNugg3ts** 2022-03-21 17:56 UTC
Labels: bug, Not Tested
