### ISSUE TITLE
All houses gone

### ISSUE THREAD

**Issue by Plant2** [Uuvana-Studios/longvinter-windows-client#81] opened 2022-02-28 17:03 UTC
**Describe the bug**
All houses on US uuvana6 are gone from yesterdays players

**To Reproduce**
1. Log on to us uuvana 6

**Expected behavior**
There should be houses but only planter boxes and fences remain

**Screenshots**

**Desktop (please complete the following information):**
 -1.0
Windows 10

**Additional context**
![Longvinter   2_28_2022 11_02_30 AM](https://user-images.githubusercontent.com/100554730/156025901-bead9698-167a-4f54-8c28-a1935f32f4f2.png)

**Comment by sirNugg3ts** [comment] 2022-03-01 18:57
Duplicate of #90

**Closed by sirNugg3ts** 2022-03-01 18:57 UTC
Labels: bug
