### ISSUE TITLE
Auto Defender disappear after placing

### ISSUE THREAD

**Issue by ZehFuge** [Uuvana-Studios/longvinter-windows-client#1049] opened 2022-07-09 20:19 UTC
**Describe the bug**
After placing Auto Defenders, they disappear. 3 of 4 Auto defender already disappeared. They placed on my property and had enough electricity. I even checked, if they were placed in the air, but they arent. It really destroys some of the fun the game makes.

**To Reproduce**
1. Farm or craft Auto Defender
2. Place it on your property (and have enough electricity)
3. Auto defender disappears and all your work is gone (3 out of 4 times)

**Expected behavior**
It should not disappear, because we farm hard to make our base safe. So we can farm with protection and start building a big base with friends because the game is really awesome.

**Screenshots**
Not included

**Desktop (please complete the following information):**
 - OS: Win 10 Home
 - Game Version: 1.0.8
 - Steam Version: 7.30.20.28

**Additional context**
It happend on Uvana 1 on different days.

**Comment by faketucker** [comment] 2022-07-11 06:03
Duplicate of #492

**Closed by faketucker** 2022-07-11 06:03 UTC
Labels: Bug, Not Tested
