### ISSUE TITLE
Entire homes vanished

### ISSUE THREAD

**Issue by e4Nf3Bb5** [Uuvana-Studios/longvinter-windows-client#508] opened 2022-03-19 17:29 UTC
US uuvana7, new autumn island. My home and several others near it (single upgrade from tent to house) have disappeared along with everything in them and the land now reads as able to be claimed.

I had walked from my home down to the south of the island to buy fences. The game lagged out and I disconnected. On reconnect, I continued play until another lag/dc. When I reconnected the second time, my player was in a previous location between my home and the southmost point. I continued south, re-bought items, and went back north....and all of the homes were gone. Multiple reconnects have not fixed it.

**Comment by e4Nf3Bb5** [comment] 2022-03-19 17:30
![20220319132125_1](https://user-images.githubusercontent.com/4843229/159131794-76d83ffc-0606-4f61-9fb5-f319cf270a6f.jpg)

**Comment by e4Nf3Bb5** [comment] 2022-03-19 17:35
placing a tent on the property shows the house...sort of
![20220319133453_1](https://user-images.githubusercontent.com/4843229/159132005-c573314a-7bc9-4fa2-b55c-e56f1fd0a00c.jpg)

**Comment by e4Nf3Bb5** [comment] 2022-03-19 17:40
Attempting to dismantle dupes it while leaving the tent in place, so I can't test putting the tend where the h
![20220319134018_1](https://user-images.githubusercontent.com/4843229/159132239-bf209dc1-ed30-43f2-aa28-36fa2b69f7c2.jpg)
ouse was

**Comment by e4Nf3Bb5** [comment] 2022-03-19 17:41
but by placing my duped tent on my friends house...I'm now in his house
![20220319134129_1](https://user-images.githubusercontent.com/4843229/159132279-7e4f5123-7c80-4b99-9227-c129cdccdec7.jpg)
.

**Comment by Slashnine** [comment] 2022-03-20 17:12
It happened to me too, my house near the bridge just disappeared and my friend is missing 2 crate inside his house. We also lost a couple of fences.

**Comment by faketucker** [comment] 2022-03-27 03:02
This could occur during a server update or restart and houses save file may have been rollbacked

**Comment by faketucker** [comment] 2022-03-27 03:47
Duplicate of #600

**Closed by faketucker** 2022-03-27 03:47 UTC
Labels: bug, Not Tested
