### ISSUE TITLE
total electricity bug(whenever close sever and reopen for maintenance)

### ISSUE THREAD

**Issue by kevinan2** [Uuvana-Studios/longvinter-windows-client#1203] opened 2022-09-01 07:59 UTC
it's been several month already. but no one report this. so i would like to inform to Dev and Admin.

Here is problem. 

whenever they close server for maintenance and re open it, number of total electricity gets wrong. 

example) one house should be able to run 4 turret .and turret was working well be4 close server for maintenance but after they close server and reopen, it turn to one turret die.  so need to place one additional generator to run one more turret.  what if they have 5 houses and turret was fully working? 5 turret will die. and u need to place 5 generator again to run fully functioned.

some of other players misunderstand that their neighbor house steal their energy. but its not. if they close server and reopen again, energy will be reduce more again, and we will need to place more generator to run turret which was functioned well before close server.

i've noticed this problem since many months ago.  i would like to ask for fix this asap to Dev and Admin.  i know Big update is interesting and it will make new players and old players to join this game again. but if they can't fix basic problems, they will leave and they won't come back. like when server ping was unstable few weeks ago and so many players quit this game already.  

but there are still a lot of people who love this game. and waiting for this game to improve more. i've been playing this game for so long.  i believe that there r lot of possibility to improve this game better and more fun. so i and Fan will wait for it. 
Thank u. have a great day.

**Comment by Jalsson** [comment] 2022-11-10 13:18
This issue was caused by two things:
1. Other player bases were stealing energy from neighbouring houses
2. When the server restarted it would sometimes duplicate the turrets and this is why it required more energy

The issue has been fixed in the current build

**Closed by Jalsson** 2022-11-10 13:18 UTC
Labels: Bug, Not Tested
