### ISSUE TITLE
character reset

### ISSUE THREAD

**Issue by IpolarbearI** [Uuvana-Studios/longvinter-windows-client#1603] opened 2024-02-13 16:44 UTC
**Describe the bug**
I have played game for few hours in sg Uuvana 1. But when I reconnect to my character has reseted. All of my money, items, compendium have all reset. But all the other buildings and even my house is still fine. (When I entered my house, all furnitures and boxes were gone.)

**To Reproduce**
4. See an error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Game Version 1.12b
 - Steam Version [e.g. 1.0]

**Additional context**

**Comment by faketucker** [comment] 2024-09-03 15:40
Duplicate of #600

**Closed as completed by faketucker** 2024-09-03 15:40 UTC
Labels: Bug, Not Tested
