### ISSUE TITLE
stuck in the river

### ISSUE THREAD

**Issue by swingzerg** [Uuvana-Studios/longvinter-windows-client#500] opened 2022-03-19 15:06 UTC
**Describe the bug**
stuck in the river

**To Reproduce**
1. open the shop window
2. move down fall into the river
3. relogin
4. stuck in the river

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Game Version [e.g. 1.0]
 - Steam Version [e.g. 1.0]

**Additional context*
![1](https://user-images.githubusercontent.com/101938298/159126427-8c5c5c81-9abf-49ce-9f5f-3894fcf241e2.png)
*

**Comment by faketucker** [comment] 2022-03-26 16:42
Duplicate of #565

**Closed by faketucker** 2022-03-26 16:42 UTC
Labels: bug, Not Tested
