### ISSUE TITLE
Problem with money achievements on steam.

### ISSUE THREAD

**Issue by AlmondSlinky519** [Uuvana-Studios/longvinter-windows-client#620] opened 2022-03-28 23:39 UTC
I was able to get the 20k and 10k money achievement but was unable to get the 5k money achievement, as well as there, were a few other achievements that I did the stuff for but was unable to get. I know this isn't a major problem but something you might want to eventually look into.

**Comment by faketucker** [comment] 2022-03-28 23:51
Duplicate of #421

**Closed by faketucker** 2022-03-28 23:51 UTC
Labels: Bug, Not Tested
