### ISSUE TITLE
House and Tent

### ISSUE THREAD

**Issue by HTAbaddon** [Uuvana-Studios/longvinter-windows-client#927] opened 2022-06-13 22:46 UTC
**Describe the bug**

Both the house and the tent are inside of each-other when entering the tent

**To Reproduce**

I left the game and rejoined, the game then sent me to a spawn far away from my tent. 
When i arrived back at my tent, the tent and house buildings where inside of each-other

**Expected behavior**

There should only be the tent rather than the tent and house appearing. when entering the tent.

**Screenshots**

![Screenshot (283)](https://user-images.githubusercontent.com/107442568/173459778-45d7ebf1-49cc-4b8c-a0a3-9054aaa781a3.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Game Version Beta 1.0.7
 - Steam Version 2.10.91.91

**Additional context**
 None

**Comment by faketucker** [comment] 2022-06-14 04:45
Duplicate of #625

**Closed by faketucker** 2022-06-14 04:45 UTC
Labels: Bug, Not Tested
