### ISSUE TITLE
Can't place my tent

### ISSUE THREAD

**Issue by Electri93** [Uuvana-Studios/longvinter-windows-client#279] opened 2022-03-08 00:05 UTC
**Describe the bug**
No matter how much distance I seem to have from other tents it never lets me place my tent, I included a few images of spots I attempted that seemed to have enough space

**To Reproduce**

**Expected behavior**

**Screenshots**
![274630346_451023416766336_7443515849767526662_n](https://user-images.githubusercontent.com/101152565/157139165-3c5e2df3-55fe-40d6-bf2a-f771818e5a08.jpg)

![274951077_2051379125029683_3128362038256646996_n](https://user-images.githubusercontent.com/101152565/157139180-659373c8-cb65-4938-b5f9-964bc7040d74.jpg)

![274126438_637295230896193_3068049848520036185_n](https://user-images.githubusercontent.com/101152565/157139187-54f4beec-44ea-4ef9-8710-5a2bbfa2c1ca.jpg)

![274888160_4777851849000711_242635411740649725_n](https://user-images.githubusercontent.com/101152565/157139199-3e0d8557-310f-4502-8d71-909d761e0a96.jpg)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Game Version [e.g. 1.0]
 - Steam Version [e.g. 1.0]

**Additional context**

**Comment by sirNugg3ts** [comment] 2022-03-08 00:07
Duplicate of #241

**Closed by sirNugg3ts** 2022-03-08 00:07 UTC
Labels: bug, Not Tested
