### ISSUE TITLE
menu for buying wont close 

### ISSUE THREAD

**Issue by mdy13** [Uuvana-Studios/longvinter-windows-client#413] opened 2022-03-14 22:50 UTC
**Describe the bug**
menu for buying wont close 

**To Reproduce**
1. Go to 'a shop'
2. Click on 'the shop'
3. press the exit button

**Expected behavior**
when your try to close the menu it thinks in closing the game

**Comment by sirNugg3ts** [comment] 2022-03-17 12:19
Duplicate of #410

**Closed by sirNugg3ts** 2022-03-17 12:19 UTC
Labels: bug, Not Tested
