### ISSUE TITLE
Getting kicked from game and losing all items, compendium, etc

### ISSUE THREAD

**Issue by Doughy-Boy** [Uuvana-Studios/longvinter-windows-client#514] opened 2022-03-19 21:18 UTC
**Describe the bug**
Server crashed maybe? Not sure.
This resulted in losing all items. Happened again a few moments later to all players on the server. After the second crash could not rejoin the server. The houses were still there, but everyones credits, compendium, and items were erased.

**To Reproduce**
No idea

**Expected behavior**
Im guessing that the save for players is located in a separate location from the base files. I think the server crashed and reset from last saves. This resulted in reloading the bases, but not reloading players inventories.

**Screenshots**
Dont have screenshots

**Desktop (please complete the following information):**
 - OS: windows
 - Game Version 1.01

**Additional context**
I think that the game should have server admins or devs that can revert previous player inventories. Ie: an admin mode to return players items or at look at player data to see what accomplishments etc they have done or had. While i accept that the game will have tons of bugs, I think ensuring that players dont lose all interest in playing from a game ruining bug is vital. Yes things happen and progress is lost, but i believe its vital to have a fail safe should something like that happen.

**Comment by faketucker** [comment] 2022-03-27 03:47
Duplicate of #600

**Closed by faketucker** 2022-03-27 03:47 UTC
Labels: bug, Not Tested
