### ISSUE TITLE
[JP] Uuvana #PVE BUG

### ISSUE THREAD

**Issue by kitty0610** [Uuvana-Studios/longvinter-windows-client#1677] opened 2024-09-03 14:25 UTC
On Tuesday, September 3rd, 23:10, Korean time, Long Vinter updated. The game went out and my items and money were safe, but the bait fishing rod was not safe. The bait fishing rod is gone. Please help me!!!!

**Comment by faketucker** [comment] 2024-09-03 15:23
Progress and items may be lost during the update or when the server restarts. We cannot fully compensate everyone. Please contact our community manager via [Discord](https://discord.gg/longvinter) or [live chat](https://longvinter.channel.io/home) for further assistance.

**Comment by faketucker** [comment] 2024-09-03 15:23
Duplicate of #600

**Closed as completed by faketucker** 2024-09-03 15:23 UTC
Labels: Bug, Not Tested
