### ISSUE TITLE
Nonupgraded and Upgraded Housing ar both bugged

### ISSUE THREAD

**Issue by Queet256** [Uuvana-Studios/longvinter-windows-client#1107] opened 2022-07-28 19:02 UTC
These updated should have been added after a wipe because now I cant access most of my storage inside of my houses....
![LV1](https://user-images.githubusercontent.com/108912330/181617061-9ddc65f4-ff93-45cb-bc28-d9790cbab02b.PNG)
![LV2](https://user-images.githubusercontent.com/108912330/181617072-95a71d66-3c6e-496f-9dbe-0fdfb4ec531c.PNG)

**Comment by vEpic7** [comment] 2022-07-28 19:04
which one is fuel and which is wind power ?

**Comment by Queet256** [comment] 2022-07-28 19:06
one without the upgrade is fuel, upgraded is solar

**Comment by Queet256** [comment] 2022-07-28 19:07
also if houses are gonna be that massive there should be an increase added to the property line

**Comment by vEpic7** [comment] 2022-07-28 19:22
> also if houses are gonna be that massive there should be an increase added to the property line

true

**Comment by vEpic7** [comment] 2022-07-28 19:22
> one without the upgrade is fuel, upgraded is solar

did u upgraded the fuel one ?

**Comment by Queet256** [comment] 2022-07-28 19:28
was going to yesterday but the game was unplayable. might try to work on it today if the lag gets fixed soon

**Comment by faketucker** [comment] 2022-08-02 06:47
Duplicate of #1099

**Closed by faketucker** 2022-08-02 06:47 UTC
