### ISSUE TITLE
The boat doesn't move.

### ISSUE THREAD

**Issue by ssmedison** [Uuvana-Studios/longvinter-windows-client#699] opened 2022-04-07 09:50 UTC
**Describe the bug**

**To Reproduce**
1. GO To The boat doesn't move.
2. Click on 'when you click'
3. Scroll down to have to go out
4. GO To The boat doesn't move.

**Expected behavior**

Maybe the boat menu button hasn't been pressed since the store bought it.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows] Windows
 - Game Version [e.g. 1.0]
 - Steam Version [e.g. 1.0]

**Additional context**

**Comment by ssmedison** [comment] 2022-04-07 09:54
get on a boat -> Mouse button is pressed -> Click does not work. -> come out -> Click -> cumbersome

**Comment by ssmedison** [comment] 2022-04-07 09:54
get on a boat -> Mouse button is pressed -> Click does not work. -> game come out -> Click -> cumbersome

**Comment by faketucker** [comment] 2022-04-07 10:03
Duplicate of #666

**Closed by faketucker** 2022-04-07 10:03 UTC
Labels: Bug, Not Tested
