### ISSUE TITLE
Untimely deletion from my inventory.

### ISSUE THREAD

**Issue by DidierNassami** [Uuvana-Studios/longvinter-windows-client#969] opened 2022-06-28 17:24 UTC
Hello, 

I play on the EU-WEST Uuvana 2 server.

So here it is, when I rent someone or even without doing anything at times my inventory on totally deleted I only keep my money.

Do you have a solution to this?

PS: I am left handed so my keyboard is on the right and my mouse is on the left. Would it be possible to make the keys functional as it currently does not work:
I: Forward
K: Backwards
J : Left
L : Right
U : say hello
O : sit down
SHIFT : for the inventory  

Also, I am French, so try to write well so that I can translate more simply <3

Kind regards.

**Comment by faketucker** [comment] 2022-06-30 04:53
> So here it is, when I rent someone or even without doing anything at times my inventory on totally deleted I only keep my money.

I'm not sure what you mean here, but your items will drop when you die.

About the inputs, they are bugged right now. The devs might be working on it soon.

**Comment by faketucker** [comment] 2022-06-30 04:54
Duplicate of #228

**Closed by faketucker** 2022-06-30 04:54 UTC
Labels: Bug, Not Tested
