### ISSUE TITLE
No water bug

### ISSUE THREAD

**Issue by NazmiSam** [Uuvana-Studios/longvinter-windows-client#294] opened 2022-03-08 14:20 UTC
**Describe the bug**
The water gone after click auto detect setting

**To Reproduce**
1. Go to options
2. Click on auto detect
3.  Set to epic back
4.  the water gone forever
5. See error

**Expected behavior**
After setting to epic the water is there back

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Game Version 1.0.0
 - Steam Version 

**Additional context**
-

**Comment by sirNugg3ts** [comment] 2022-03-08 14:35
Duplicate of #13

**Closed by sirNugg3ts** 2022-03-08 14:35 UTC
Labels: bug, Not Tested
