### ISSUE TITLE
Spam Clicking Berry Bushes 

### ISSUE THREAD

**Issue by ConnorBAdams** [Uuvana-Studios/longvinter-windows-client#393] opened 2022-03-13 04:45 UTC
**Describe the bug**
Spam clicking berry bushes can give 2+ berries instead of 1. The same applies to beets and I assume all produce.

**To Reproduce**
1. Go to a berry bush
2. Spam click (click as fast as you can) on the bust
3. Receive 2+ berries, often the second showing up after the bush is gone
4. Bonus points: If you only had 1 slot in your bag it will overflow (see screenshot)

**Expected behavior**
A bush should only give 1 berry, is I click a bush once it is consumed but by spam clicking I can get extra. 

**Screenshots**
![image](https://user-images.githubusercontent.com/1358951/158045495-41836e66-d3d6-4879-b9b1-89063e135e93.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Game Version [e.g. 1.0] 1.0
 - Steam Version [e.g. 1.0] 1.0

**Additional context**
It appears to not work on wheat. When the inventory overflows I can then consume the overflowed item, if I close the inventory it is lost.

**Comment by sirNugg3ts** [comment] 2022-03-17 12:37
Duplicate of #319 
Not exactly the same procedures but the underlying bug is the same.

**Closed by sirNugg3ts** 2022-03-17 12:37 UTC
Labels: bug, Not Tested
