### ISSUE TITLE
Houses disappeared 

### ISSUE THREAD

**Issue by Sammieyy** [Uuvana-Studios/longvinter-windows-client#501] opened 2022-03-19 15:31 UTC
**Describe the bug**
So me and my friend both had 2 houses on pix island. After the update the island changed and two of our houses disappeared that were on the right side. 

**To Reproduce**
1. Have a house. 
2. Game gets updates
3. Don't have a house? 😂

**Expected behavior**
Please make it so then when areas get changed the houses don't disappear, or atleast give players the opportunity to replace the house. 

![20220319_145331](https://user-images.githubusercontent.com/101938031/159127500-3214dd06-d476-4bd8-8582-9285f8f2723b.jpg)

**Comment by Sammieyy** [comment] 2022-03-19 15:38
![20220319_163733](https://user-images.githubusercontent.com/101938031/159127755-52a26ead-1b1a-4b4a-bb60-e5ab9f90115c.jpg)

Now when i enter the new tent I've placed near the location of the old one i suddenly see this. I see my old stuff a bit above the tent and the interior is a tent mixed with a house?

**Comment by faketucker** [comment] 2022-03-27 06:17
Duplicate of #600

**Closed by faketucker** 2022-03-27 06:17 UTC
Labels: bug, Not Tested
