### ISSUE TITLE
why I have such a big ping

### ISSUE THREAD

**Issue by AJIbPHA** [Uuvana-Studios/longvinter-windows-client#1178] opened 2022-08-21 12:18 UTC
Why I have such a big ping, it's hard to play and it's impossible to shoot. everything was fine before the last wipes.
![2022-08-21 (18)](https://user-images.githubusercontent.com/111048398/185790490-de47d260-f558-4e21-b606-1db3e176c932.png)

**Comment by faketucker** [comment] 2022-08-21 23:18
Duplicate of #1164

**Closed by faketucker** 2022-08-21 23:18 UTC
Labels: Bug, Not Tested
