### ISSUE TITLE
stuck on vendor screen

### ISSUE THREAD

**Issue by aestheticvllyy** [Uuvana-Studios/longvinter-windows-client#819] opened 2022-04-24 05:51 UTC
**Describe the bug**
after visiting a vendor, the UI is stuck. i've tried walking away, opening my inventory, trying to close it using the keybind, to no avail
**To Reproduce**
1. Go to any vendor
2. Try to exit it

**Expected behavior**
The vendors screen is stuck meanwhile opening the inventory or the pause menu is still functional
**Screenshots**
![image](https://user-images.githubusercontent.com/104292336/164958600-3d1e434c-b245-499e-b63e-0d7f0aeba908.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Game Version [e.g. 1.0]
 - Steam Version [e.g. 1.0]

**Additional context**

**Comment by faketucker** [comment] 2022-04-24 06:03
Duplicate of #410

**Closed by faketucker** 2022-04-24 06:03 UTC
Labels: Bug, Not Tested
