### ISSUE TITLE
Turret (auto defender) fires in safe zones

### ISSUE THREAD

**Issue by natamru** [Uuvana-Studios/longvinter-windows-client#680] opened 2022-04-04 17:13 UTC
Conditions:
-player stands in safe zone
-turret is near safe zone

Issue:
The turret tracks and fires on the player, sometimes there's damage sometimes there's none, in this video there is no damage.

https://user-images.githubusercontent.com/16938875/161596484-a6480e37-d59b-47e3-aedc-e34a023244d8.mp4

Expected behavior:
The turret should not track nor fire at the player.

System tested:
Windows 8
Windows 8.1
Windows 10 21H2

**Comment by faketucker** [comment] 2022-04-04 23:41
I'm pretty sure this has nothing to do with safe zones. Turrets just can't shoot at some angles.

**Comment by faketucker** [comment] 2022-04-04 23:42
Duplicate of #377

**Closed by faketucker** 2022-04-04 23:42 UTC
Labels: Bug, Not Tested
