### ISSUE TITLE
The turrets are gone to sky or somewhere in digo isanland

### ISSUE THREAD

**Issue by PJ0525** [Uuvana-Studios/longvinter-windows-client#870] opened 2022-05-07 09:04 UTC
location: digo island, 12N 38W
![image](https://user-images.githubusercontent.com/105104030/167247136-dccb86de-2456-4818-8b4e-f08b8a25edf4.png)

session server: jeju island

my nickname: 삐제
my steam id url: https://steamcommunity.com/id/sexy0525/
my steam friend code: 276475820

issue: when I install the turrets on my house, the turrets are gone to sky 
and somewhere near to someone's house. 
I already lost 4 turrets with this issue. I am really tired of this. 
so I begin you give my turrets back

attaching some captures please refer to under images.
![image](https://user-images.githubusercontent.com/105104030/167247371-5648a08a-d63d-4f73-b150-618c7475f578.png)
![image](https://user-images.githubusercontent.com/105104030/167247379-92d68904-4567-4d9a-9715-04e6203ca01d.png)

**Comment by faketucker** [comment] 2022-05-08 04:35
Duplicate of #492

**Closed by faketucker** 2022-05-08 04:35 UTC
Labels: Bug, Not Tested

**Comment by PJ0525** [comment] 2022-05-08 07:40
> Duplicate of #492

so what. compensation it

**Comment by PJ0525** [comment] 2022-05-08 08:16
2 turrets are gone again!!!
