### ISSUE TITLE
Turrets duplicate, activate, and deactivate occasionally

### ISSUE THREAD

**Issue by biffotmc** [Uuvana-Studios/longvinter-windows-client#588] opened 2022-03-25 21:11 UTC
**Describe the bug**
Turrets duplicate when they turn on and off from energy usage

**To Reproduce**
Steps to reproduce the behaviour:
1. Place some turrets
2. Make some energy using turbine or fuel
3. Wait for turrets to activate/deactivate
4. Duplication in same spot and you can pick up both

**Expected behavior**
Turrets should not duplicate when turning on and off

**Screenshots**
![image](https://user-images.githubusercontent.com/86079175/160201071-acf9edc0-2ac8-4a41-823b-cde079b4c0ff.png)
Image of duplicated turret

**Desktop (please complete the following information):**
 - OS: [Windows 11]
 - Game Version [1.0.2]
 - Steam Version []

**Additional context**
This might also be possible with other electrical items when they turn on and off but that hasn't been tested

**Comment by faketucker** [comment] 2022-03-27 23:10
Can't find a way to replicate, but since @biffotmc confirmed it, I'm pretty sure it can happen and has something to do with the electricity system, so I'm going to put this together with the issue #585

**Comment by faketucker** [comment] 2022-03-30 07:10
Welp, this still happens after the electricity system fix. Turrets activate and deactivate occasionally, and sometimes when you shoot till it's disabled, it becomes active again.

**Comment by faketucker** [comment] 2022-04-16 04:57
> Fixed a bug where a turret woke up too quickly after being disabled with gun
I believe this was fixed by the last update. Reopen this issue again if you're still facing this issue.

**Comment by faketucker** [comment] 2022-04-16 05:32
Just tested. It's not LMAO.

**Comment by Jalsson** [comment] 2022-11-07 13:23
This issue was caused by the server saving duplicate turrets. Closing this one

**Closed by Jalsson** 2022-11-07 13:23 UTC
Labels: Bug, High Priority, Tested
